#reloadable

import crafttweaker.data.IData;
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

static EFFECTS as IData = {
    "careerbees.acceleration": "Accelerate",
    "careerbees.armorer": "Armorer",
    "careerbees.artist": "Painting",
    "careerbees.assassin": "Assassin",
    "careerbees.buisnessman": "Business",
    "careerbees.butcher": "Butcher",
    "careerbees.clock": "Clockwinding",
    "careerbees.collectors": "Wombling",
    "careerbees.cook": "HoneyGlazing",
    "careerbees.crusher": "Crusher",
    "careerbees.devil": "Burning",
    "careerbees.digging.fortune": "FortunateMining",
    "careerbees.digging.silky": "SilkyMining",
    "careerbees.digging": "Mining",
    "careerbees.electrician": "Electrifying",
    "careerbees.energy": "RFInducing",
    "careerbees.engineer": "None",
    "careerbees.graduate": "Retraining",
    "careerbees.honey_smelter": "IronHoneyification",
    "careerbees.husbandry": "Husbandry",
    "careerbees.junk_seller": "JunkSale",
    "careerbees.lumber": "DarkBiter",
    "careerbees.mad_scientist": "Science!!!!",
    "careerbees.mason": "Masonry",
    "careerbees.nca": "ExplosionPrevention",
    "careerbees.phd": "Retraining",
    "careerbees.plaguedoctor": "Curative",
    "careerbees.police": "Policing",
    "careerbees.politician": "FundRaising",
    "careerbees.priest": "Priest",
    "careerbees.quantum_charm": "Teleposition",
    "careerbees.quantum_strange": "Teleposition",
    "careerbees.rainbow": "None",
    "careerbees.repair": "Repair",
    "careerbees.robot": "None",
    "careerbees.science": "None",
    "careerbees.sharpening": "Sharpening",
    "careerbees.smelter": "Smelting",
    "careerbees.student": "None",
    "careerbees.taxcollector": "Taxation",
    "careerbees.thief": "Yoink!",
    "careerbees.yente": "None",
    "extrabees.species.abyss": "Wither",
    "extrabees.species.acidic": "Acidic",
    "extrabees.species.alcohol": "Drunkard",
    "extrabees.species.ancient": "None",
    "extrabees.species.arid": "None",
    "extrabees.species.artic": "Freezing",
    "extrabees.species.barren": "None",
    "extrabees.species.basalt": "Aggression",
    "extrabees.species.bauxite": "None",
    "extrabees.species.black": "None",
    "extrabees.species.blooming": "Growth",
    "extrabees.species.blue": "None",
    "extrabees.species.blutonium": "Unstable",
    "extrabees.species.boggy": "Slowness",
    "extrabees.species.bone": "Skeletons",
    "extrabees.species.brown": "None",
    "extrabees.species.caustic": "Acidic",
    "extrabees.species.celebratory": "Fireworks",
    "extrabees.species.cinnabar": "None",
    "extrabees.species.classical": "None",
    "extrabees.species.coal": "None",
    "extrabees.species.coffee": "None",
    "extrabees.species.copper": "None",
    "extrabees.species.corrosive": "Acidic",
    "extrabees.species.creeper": "Creepers",
    "extrabees.species.creosote": "None",
    "extrabees.species.cyan": "None",
    "extrabees.species.cyanite": "Unstable",
    "extrabees.species.darkened": "Darkness",
    "extrabees.species.decomposing": "None",
    "extrabees.species.desolate": "Hunger",
    "extrabees.species.diamond": "None",
    "extrabees.species.distilled": "None",
    "extrabees.species.ecstatic": "Power",
    "extrabees.species.emerald": "None",
    "extrabees.species.energetic": "Lightning",
    "extrabees.species.excited": "Lightning",
    "extrabees.species.farm": "None",
    "extrabees.species.freezing": "Freezing",
    "extrabees.species.fruit": "Ripening",
    "extrabees.species.fuel": "None",
    "extrabees.species.fungal": "Mushroom",
    "extrabees.species.glowstone": "Aggression",
    "extrabees.species.glutinous": "Ectoplasm",
    "extrabees.species.gnawing": "None",
    "extrabees.species.gold": "None",
    "extrabees.species.granite": "None",
    "extrabees.species.gray": "None",
    "extrabees.species.greek": "None",
    "extrabees.species.green": "None",
    "extrabees.species.growing": "None",
    "extrabees.species.hazardous": "Creeper",
    "extrabees.species.infectious": "Poison",
    "extrabees.species.ink": "Water",
    "extrabees.species.iron": "None",
    "extrabees.species.jaded": "Beatific",
    "extrabees.species.lapis": "None",
    "extrabees.species.latex": "None",
    "extrabees.species.lead": "None",
    "extrabees.species.lightblue": "None",
    "extrabees.species.lightgray": "None",
    "extrabees.species.limegreen": "None",
    "extrabees.species.magenta": "None",
    "extrabees.species.malicious": "Poison",
    "extrabees.species.marble": "None",
    "extrabees.species.milk": "None",
    "extrabees.species.mineral": "None",
    "extrabees.species.mystical": "None",
    "extrabees.species.nickel": "None",
    "extrabees.species.nuclear": "Unstable",
    "extrabees.species.ocean": "Water",
    "extrabees.species.oil": "None",
    "extrabees.species.orange": "None",
    "extrabees.species.pink": "None",
    "extrabees.species.platinum": "None",
    "extrabees.species.prehistoric": "None",
    "extrabees.species.primeval": "None",
    "extrabees.species.purple": "None",
    "extrabees.species.pyrite": "None",
    "extrabees.species.quantum": "None",
    "extrabees.species.radioactive": "Unstable",
    "extrabees.species.red": "None",
    "extrabees.species.relic": "None",
    "extrabees.species.resin": "None",
    "extrabees.species.ripening": "None",
    "extrabees.species.river": "Water",
    "extrabees.species.rock": "None",
    "extrabees.species.roman": "None",
    "extrabees.species.rotten": "Zombies",
    "extrabees.species.ruby": "None",
    "extrabees.species.sapphire": "None",
    "extrabees.species.shadow": "Darkness",
    "extrabees.species.silver": "None",
    "extrabees.species.sodalite": "None",
    "extrabees.species.spatial": "Gravity",
    "extrabees.species.sphalerite": "None",
    "extrabees.species.sticky": "Ectoplasm",
    "extrabees.species.stone": "None",
    "extrabees.species.sugar": "None",
    "extrabees.species.swamp": "Slowness",
    "extrabees.species.sweet": "None",
    "extrabees.species.tempered": "Meteor",
    "extrabees.species.thriving": "None",
    "extrabees.species.tin": "None",
    "extrabees.species.titanium": "None",
    "extrabees.species.tungstate": "None",
    "extrabees.species.unstable": "Unstable",
    "extrabees.species.unusual": "Gravity",
    "extrabees.species.virulent": "Poison",
    "extrabees.species.viscous": "Ectoplasm",
    "extrabees.species.volcanic": "Meteor",
    "extrabees.species.water": "Water",
    "extrabees.species.white": "None",
    "extrabees.species.yellorium": "Unstable",
    "extrabees.species.yellow": "None",
    "extrabees.species.zinc": "None",
    "forestry.speciesAgrarian": "Fertile",
    "forestry.speciesAustere": "Creeper",
    "forestry.speciesAvenging": "Radioactive",
    "forestry.speciesBoggy": "Mycophilic",
    "forestry.speciesCommon": "None",
    "forestry.speciesCultivated": "None",
    "forestry.speciesDemonic": "Flammable",
    "forestry.speciesDiligent": "None",
    "forestry.speciesEdenic": "Explorer",
    "forestry.speciesEnded": "Ends",
    "forestry.speciesExotic": "Poison",
    "forestry.speciesFarmerly": "None",
    "forestry.speciesFiendish": "Aggression",
    "forestry.speciesForest": "None",
    "forestry.speciesFrugal": "None",
    "forestry.speciesGlacial": "Freezing",
    "forestry.speciesHermitic": "Repulsion",
    "forestry.speciesHeroic": "Heroic",
    "forestry.speciesIcy": "Freezing",
    "forestry.speciesImperial": "Beatific",
    "forestry.speciesIndustrious": "None",
    "forestry.speciesMajestic": "None",
    "forestry.speciesMarshy": "None",
    "forestry.speciesMeadows": "None",
    "forestry.speciesMiry": "None",
    "forestry.speciesModest": "None",
    "forestry.speciesMonastic": "None",
    "forestry.speciesNoble": "None",
    "forestry.speciesPhantasmal": "Ressurection",
    "forestry.speciesRural": "None",
    "forestry.speciesSecluded": "None",
    "forestry.speciesSinister": "Aggression",
    "forestry.speciesSpectral": "Reanimation",
    "forestry.speciesSteadfast": "None",
    "forestry.speciesTropical": "Poison",
    "forestry.speciesUnweary": "None",
    "forestry.speciesValiant": "None",
    "forestry.speciesVengeful": "Radioactive",
    "forestry.speciesVindictive": "Radioactive",
    "forestry.speciesWintry": "Freezing",
    "gendustry.bee.Agricultural": "None",
    "gendustry.bee.Alchemical": "None",
    "gendustry.bee.Apothecary": "Science!!!!",
    "gendustry.bee.Armored": "None",
    "gendustry.bee.Artillery": "Flammable",
    "gendustry.bee.Baguette": "None",
    "gendustry.bee.Balanced": "None",
    "gendustry.bee.black": "None",
    "gendustry.bee.blue": "None",
    "gendustry.bee.Bomber": "Flammable",
    "gendustry.bee.brown": "None",
    "gendustry.bee.Buried": "None",
    "gendustry.bee.Chevron": "None",
    "gendustry.bee.Controller": "None",
    "gendustry.bee.Crepuscular": "None",
    "gendustry.bee.cyan": "None",
    "gendustry.bee.Darkness": "IronHoneyification",
    "gendustry.bee.Deeplearner": "None",
    "gendustry.bee.derpious": "None",
    "gendustry.bee.Experienced": "None",
    "gendustry.bee.Fear": "Policing",
    "gendustry.bee.Feesh": "None",
    "gendustry.bee.Fiotic": "None",
    "gendustry.bee.Fissile": "Flammable",
    "gendustry.bee.Flux": "None",
    "gendustry.bee.Formic": "None",
    "gendustry.bee.Gorgon": "None",
    "gendustry.bee.Gravity": "None",
    "gendustry.bee.gray": "None",
    "gendustry.bee.green": "None",
    "gendustry.bee.GunDevil": "Flammable",
    "gendustry.bee.Gunman": "Flammable",
    "gendustry.bee.Helplessness": "Accelerate",
    "gendustry.bee.Heraldry": "None",
    "gendustry.bee.Herblore": "Flammable",
    "gendustry.bee.Isekai": "None",
    "gendustry.bee.lightblue": "None",
    "gendustry.bee.lime": "None",
    "gendustry.bee.Luctor": "None",
    "gendustry.bee.magenta": "None",
    "gendustry.bee.Meatball": "None",
    "gendustry.bee.Necronomibee": "None",
    "gendustry.bee.orange": "None",
    "gendustry.bee.Oxygen": "None",
    "gendustry.bee.pink": "None",
    "gendustry.bee.purple": "None",
    "gendustry.bee.Pyramid": "Aggression",
    "gendustry.bee.Pyromaniacal": "Burning",
    "gendustry.bee.Radiant": "None",
    "gendustry.bee.red": "None",
    "gendustry.bee.Restlessclam": "None",
    "gendustry.bee.Ringbearer": "None",
    "gendustry.bee.Ryleyan": "None",
    "gendustry.bee.Salty": "None",
    "gendustry.bee.Sandman": "None",
    "gendustry.bee.Sanitizing": "None",
    "gendustry.bee.Shadow": "None",
    "gendustry.bee.Shyre": "None",
    "gendustry.bee.silver": "None",
    "gendustry.bee.Sniper": "Flammable",
    "gendustry.bee.Solitude": "Retraining",
    "gendustry.bee.Soulsucking": "None",
    "gendustry.bee.Springwater": "None",
    "gendustry.bee.Stargazer": "None",
    "gendustry.bee.Stormborn": "None",
    "gendustry.bee.Thorium": "None",
    "gendustry.bee.Trinity": "None",
    "gendustry.bee.Twilight": "None",
    "gendustry.bee.Uranium": "None",
    "gendustry.bee.Uselessforce": "None",
    "gendustry.bee.Warrior": "None",
    "gendustry.bee.white": "None",
    "gendustry.bee.yellow": "None",
    "gendustry.bee.ThermallyExpanded": "None",
    "magicbees.speciesAbandoned": "Repulsion",
    "magicbees.speciesAESkystone": "Flammable",
    "magicbees.speciesAluminium": "None",
    "magicbees.speciesApatite": "None",
    "magicbees.speciesArcane": "None",
    "magicbees.speciesArdite": "None",
    "magicbees.speciesAttuned": "None",
    "magicbees.speciesAware": "None",
    "magicbees.speciesBatty": "Batty",
    "magicbees.speciesBeef": "Bovine",
    "magicbees.speciesBigbad": "Canine",
    "magicbees.speciesBOTAlfheim": "Dreaming",
    "magicbees.speciesBOTBlossom": "None",
    "magicbees.speciesBOTBotanic": "None",
    "magicbees.speciesBOTDreaming": "SlowSpeed",
    "magicbees.speciesBOTFloral": "None",
    "magicbees.speciesBOTRooted": "None",
    "magicbees.speciesBOTSomnolent": "SlowSpeed",
    "magicbees.speciesBOTVazbee": "None",
    "magicbees.speciesBronze": "None",
    "magicbees.speciesCatty": "Catty",
    "magicbees.speciesCertus": "None",
    "magicbees.speciesCharmed": "None",
    "magicbees.speciesChicken": "Chicken",
    "magicbees.speciesCobalt": "None",
    "magicbees.speciesCopper": "None",
    "magicbees.speciesCrumbling": "Crumbling",
    "magicbees.speciesDiamond": "None",
    "magicbees.speciesDoctoral": "Heroic",
    "magicbees.speciesDraconic": "Ends",
    "magicbees.speciesEarthy": "None",
    "magicbees.speciesEldritch": "None",
    "magicbees.speciesElectrum": "None",
    "magicbees.speciesEmerald": "None",
    "magicbees.speciesEnchanted": "None",
    "magicbees.speciesEsoteric": "None",
    "magicbees.speciesEthereal": "None",
    "magicbees.speciesFirey": "None",
    "magicbees.speciesFluix": "None",
    "magicbees.speciesForlorn": "Repulsion",
    "magicbees.speciesGhastly": "Ghastly",
    "magicbees.speciesGold": "None",
    "magicbees.speciesHateful": "Ends",
    "magicbees.speciesHorse": "Horse",
    "magicbees.speciesInfernal": "Aggression",
    "magicbees.speciesInvar": "Flammable",
    "magicbees.speciesInvisible": "Invisible",
    "magicbees.speciesIron": "None",
    "magicbees.speciesLead": "None",
    "magicbees.speciesLordly": "Drunkard",
    "magicbees.speciesManyullyn": "None",
    "magicbees.speciesMutable": "None",
    "magicbees.speciesMysterious": "None",
    "magicbees.speciesMystical": "None",
    "magicbees.speciesNameless": "Aggression",
    "magicbees.speciesNickel": "None",
    "magicbees.speciesOblivion": "Aggression",
    "magicbees.speciesOsmium": "None",
    "magicbees.speciesPlatinum": "Flammable",
    "magicbees.speciesPork": "Porcine",
    "magicbees.speciesPupil": "None",
    "magicbees.speciesRSAFluxed": "Flammable",
    "magicbees.speciesSavant": "None",
    "magicbees.speciesScholarly": "None",
    "magicbees.speciesSheepish": "Sheep",
    "magicbees.speciesSilicon": "None",
    "magicbees.speciesSilver": "None",
    "magicbees.speciesSkulking": "None",
    "magicbees.speciesSorcerous": "None",
    "magicbees.speciesSoul": "None",
    "magicbees.speciesSpirit": "None",
    "magicbees.speciesSpiteful": "Ends",
    "magicbees.speciesSupernatural": "None",
    "magicbees.speciesTEAmped": "SpawnBlitz",
    "magicbees.speciesTEBlizzy": "Freezing",
    "magicbees.speciesTECoal": "None",
    "magicbees.speciesTEDante": "Flammable",
    "magicbees.speciesTEDestabilized": "None",
    "magicbees.speciesTEEndearing": "None",
    "magicbees.speciesTEGelid": "SpawnBlizz",
    "magicbees.speciesTEGrounded": "None",
    "magicbees.speciesTELux": "Flammable",
    "magicbees.speciesTEPyro": "Flammable",
    "magicbees.speciesTERocking": "SpawnBasalz",
    "magicbees.speciesTEShocking": "None",
    "magicbees.speciesTEWinsome": "None",
    "magicbees.speciesTimely": "SlowSpeed",
    "magicbees.speciesTin": "None",
    "magicbees.speciesTransmuting": "Transmuting",
    "magicbees.speciesUnusual": "None",
    "magicbees.speciesWatery": "None",
    "magicbees.speciesWindy": "None",
    "magicbees.speciesWithering": "Withering"
} as IData;

static EFFECT_DESCRIPTIONS as IData = {
    "Accelerate": "Speeds up tick rate of nearby tileEntities.",
    "Acidic": "Decays blocks around it: dirt/grass -> sand, and stone/cobblestone -> gravel.",
    "Aggression": "Damages nearby entities. Ignores items.",
    "Armorer": "Armor items placed on nearby flower pedastals gain a boost to the armor stat, up to 100% per piece. This applies to all armor points, not only the armor on the affected piece.",
    "Assassin": "Kills bees in nearby beehives. Use this in the bee-bee gun; if placed inside of an apiary, it will delete itself without giving drones or a princess.",
    "Batty": "Spawns bats nearby.",
    "Beatific": "Gives nearby players the regeneration effect.",
    "Bovine": "Spawns cows nearby.",
    "Burning": "Fire spreads nearby.",
    "Business": "Sells items in adjacent inventories for emeralds using villager trades.",
    "Butcher": "Kills nearby animals until it's left with only a pair.",
    "Canine": "Spawns wolves nearby.",
    "Catty": "Should spawn ocelots nearby. However, this doesn't seem to function.",
    "Chicken": "Spawns chickens nearby.",
    "Clockwinding": "Automatically winds nearby Clockwork Engines to yellow.",
    "Creeper": "Damages player as if hit by creeper explosion.",
    "Creepers": "Spawns creepers nearby.",
    "Crumbling": "Decays blocks around it: stone -> cobblestone -> moss stone, and stone bricks -> cracked stone bricks -> mossy stone bricks.",
    "Crusher": "Turns metal ore placed on nearby flower pedastal into 2-4 dust of that metal.",
    "Curative": "Removes negative potion effects and slightly heals nearby entities.",
    "DarkBiter": "Takes tree bark resources from nearby trees, and puts them in housing.",
    "Darkness": "Gives nearby players the blindness effect.",
    "Dreaming": "Automatically converts nearby logs or stone blocks into livingwood and livingrock.",
    "Drunkard": "Gives nearby players the nausea effect.",
    "Ectoplasm": "Randomly spawns ectoplasm in the bee's territory on solid blocks.",
    "Electrifying": "Damages nearby entities as if they were struck by lightning.",
    "Ends": "Damages nearby players.",
    "Explorer": "Gives nearby players XP.",
    "ExplosionPrevention": "Spawns creepers afflicted with wither. These do not drop items.",
    "Fertile": "Should stimulate randomTicks to nearby blocks, but seems to be broken, although the code looks correct.",
    "Fireworks": "If housing sees sky, spawn fireworks nearby.",
    "Flammable": "Sets nearby entities on fire. Ignores items.",
    "FortunateMining": "Automatically mines ores with fortune 3 within its territory while also ignoring the y-restriction of its territory. Mining speed is affected by the bee's speed and any external production modifiers.",
    "Freezing": "Freezes any water source blocks into ice.",
    "FundRaising": "Does nothing :)",
    "Ghastly": "Spawns ghasts nearby.",
    "Gravity": "Moves nearby entities around.",
    "Growth": "Applies the bone meal effect to nearby saplings.",
    "Heroic": "Damages nearby hostile mobs.",
    "HoneyGlazing": "Honey Glazing will add the Honey Glazing modifier to food placed on nearby flower pedastals. This will give you a certain number of absorption hearts based on which food is used and how long it is kept on the flower pedastal.",
    "Horse": "Should spawn horses nearby. However, this doesn't seem to function.",
    "Hunger": "Gives nearby players the hunger effect.",
    "Husbandry": "Breeds nearby animals.",
    "Invisible": "Gives nearby players the invisibility effect.",
    "IronHoneyification": "Turns iron on nearby flower pedastals into honey-comb ingots.",
    "JunkSale": "Automatically trades emeralds placed in adjacent inventory for random items using villager trades.",
    "Lightning": "Lightning strikes nearby. Ignores weather, and can start fires.",
    "Masonry": "Automatically converts nearby cobblestone into stone, then stone bricks. This also turns andesite, granite, and diorite into their polished versions.",
    "Meteor": "If housing sees the sky, rains fire charges.",
    "Mining": "Automatically mines ores within its territory while also ignoring the y-restriction of its territory. Mining speed is affected by the bee's speed and any external production modifiers.",
    "Mushroom": "Applies the bone meal effect to nearby mushrooms.",
    "Mycophilic": "Randomly turns nearby grass blocks into mycelium, grows mushrooms, and turns cows into mooshrooms.",
    "None": "This bee does nothing!",
    "Painting": "Creates paintings on nearby walls.",
    "Poison": "Gives nearby players the poison effect.",
    "Policing": "Kills nearby hostile mobs and obtains items with high luck.",
    "Porcine": "Spawns pigs nearby.",
    "Power": "Slowly charges nearby buildcraft machines with power.",
    "Priest": "Enchants items on nearby flower pedastals. Level of enchantment is affected by bookshelves.",
    "Radioactive": "Damages nearby entities. Destroys nearby blocks.",
    "Reanimation": "Spawns skeletons, zombies, or blazes if their drops are on the ground.",
    "Repair": "Automatically repairs items placed on nearby flower pedastals. Rate of repair is affected by the bee's speed and external production modifiers.",
    "Repulsion": "Nearby mobs try to move away from players.",
    "Ressurection": "Spawns creepers, endermen, spiders, cave spiders, ghasts, or ender dragons if their drops are on the ground.",
    "Retraining": "Restores effect gene on bees placed on nearby flower pedastals.",
    "RFInducing": "Generates RF to adjacent blocks.",
    "Ripening": "Applies the bone meal effect to nearby leaves that produce fruit.",
    "Science!!!!": "Creates explosions that don't effect tile entities nearby.",
    "Sharpening": "Swords placed on nearby flower pedastals gain a boost to their attack damage, up to 5 damage.",
    "Sheep": "Spawns sheep nearby.",
    "SilkyMining": "Automatically mines ores with silk touch within its territory while also ignoring the y-restriction of its territory. Mining speed is affected by the bee's speed and any external production modifiers.",
    "Skeletons": null,
    "Slowness": "Gives nearby players the slowness effect.",
    "SlowSpeed": "Gives nearby players the slowness effect. Doesn't seem to work.",
    "Smelting": "Automatically smelts items placed in nearby flower pedastals.",
    "SpawnBasalz": "Spawns basalz nearby.",
    "SpawnBlitz": "Spawns blitz nearby.",
    "SpawnBlizz": "Spawns blizz nearby.",
    "Taxation": "Gives the drops of nearby mobs without killing them.",
    "Teleposition": "Switches nearby blocks to other nearby blocks with the same material. This ignores all tileEntities.",
    "Transmuting": "Turns sand into sandstone if in desert, and stone/cobblestone into quarried stone or abyssal stone where they spawn naturally.",
    "Unstable": "Damages nearby players.",
    "Water": "Fills nearby tanks with water.",
    "Wither": "Gives nearby players the wither effect.",
    "Withering": "Gives nearby players the wither effect.",
    "Wombling": "Collects nearby items and inserts them into housing.",
    "Yoink!": "Steals items from nearby players.",
    "Zombies": "Spawns zombies nearby."
} as IData;





function effectDescription(stack as IItemStack, showDescription as bool, shift as bool) as string {
    if (isNull(stack.tag) || isNull(stack.tag.Genome) || isNull(stack.tag.Genome.Chromosomes)) return null;
    val species as IData = stack.tag.Genome.Chromosomes[0] as IData;
    val dominant as string = species.UID0.asString();
    val recessive as string = species.UID1.asString();

    if (dominant != recessive) return null;

    val effectData as IData = EFFECTS.memberGet(dominant);
    if (isNull(effectData)) {
        if (showDescription) { return null; }
        return "Effect: §cMISSING (" + dominant + ")§r";
    }
    val effect as string = effectData.asString();
    
    if (!showDescription) { return "Effect: " + effect; }
    if (!shift) { return "§8§oHold Shift to show effect description§r"; }

    val descriptionData = EFFECT_DESCRIPTIONS.memberGet(effect);
    if (isNull(descriptionData)) return "§cMISSING DESCRIPTION (" + dominant + ")§r";
    return descriptionData.asString();
}

val beeItems = [<forestry:bee_princess_ge:0>, <forestry:bee_drone_ge:0>, <forestry:bee_queen_ge:0>] as IIngredient[];

for beeItem in beeItems {
    beeItem.addAdvancedTooltip(function(item) { return effectDescription(item, false, false); });
    beeItem.addShiftTooltip(
        function(item) { return effectDescription(item, true, true); }, 
        function(item) { return effectDescription(item, true, false); }
    );
}

/* for beeItem in beeItems {
    beeItem.addAdvancedTooltip(function(item) {   
        val species = item.tag.Genome.Chromosomes[0];
        return species.UID0.asString() + " - " + species.UID1.asString();
    });
} */