#reloadable

import crafttweaker.data.IData;
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

static EFFECTS as IData = {
    "careerbees.acceleration": "瞬世",
    "careerbees.armorer": "铸甲师",
    "careerbees.artist": "绘画",
    "careerbees.assassin": "刺客",
    "careerbees.buisnessman": "行商",
    "careerbees.butcher": "屠夫",
    "careerbees.clock": "上发条",
    "careerbees.collectors": "小小Womble",
    "careerbees.cook": "蜜釉",
    "careerbees.crusher": "碎矿",
    "careerbees.devil": "燃烧[职业蜜蜂]",
    "careerbees.digging.fortune": "时运采掘",
    "careerbees.digging.silky": "精准采掘",
    "careerbees.digging": "采掘",
    "careerbees.electrician": "缠雷",
    "careerbees.energy": "RF感生",
    "careerbees.engineer": "无",
    "careerbees.graduate": "复职培训",
    "careerbees.honey_smelter": "铁锭蜜化",
    "careerbees.husbandry": "畜牧",
    "careerbees.junk_seller": "废品贩售",
    "careerbees.lumber": "树皮叮咬者",
    "careerbees.mad_scientist": "科学！！！",
    "careerbees.mason": "石匠",
    "careerbees.nca": "“阻止”爆炸",
    "careerbees.phd": "复职培训",
    "careerbees.plaguedoctor": "治愈",
    "careerbees.police": "治安维持",
    "careerbees.politician": "募集捐款",
    "careerbees.priest": "牧师",
    "careerbees.quantum_charm": "转位",
    "careerbees.quantum_strange": "转位",
    "careerbees.rainbow": "无",
    "careerbees.repair": "修复",
    "careerbees.robot": "无",
    "careerbees.science": "无",
    "careerbees.sharpening": "砺刃",
    "careerbees.smelter": "熔炼",
    "careerbees.student": "无",
    "careerbees.taxcollector": "征税",
    "careerbees.thief": "嗖嗖，到手了！",
    "careerbees.yente": "无",
    "extrabees.species.abyss": "凋零[更多蜜蜂]",
    "extrabees.species.acidic": "酸液",
    "extrabees.species.alcohol": "沉醉",
    "extrabees.species.ancient": "无",
    "extrabees.species.arid": "无",
    "extrabees.species.artic": "冻结",
    "extrabees.species.barren": "无",
    "extrabees.species.basalt": "举世皆敌",
    "extrabees.species.bauxite": "无",
    "extrabees.species.black": "无",
    "extrabees.species.blooming": "生长",
    "extrabees.species.blue": "无",
    "extrabees.species.blutonium": "不稳定",
    "extrabees.species.boggy": "缓慢",
    "extrabees.species.bone": "生成骷髅",
    "extrabees.species.brown": "无",
    "extrabees.species.caustic": "酸液",
    "extrabees.species.celebratory": "烟火",
    "extrabees.species.cinnabar": "无",
    "extrabees.species.classical": "无",
    "extrabees.species.coal": "无",
    "extrabees.species.coffee": "无",
    "extrabees.species.copper": "无",
    "extrabees.species.corrosive": "酸液",
    "extrabees.species.creeper": "生成爬行者",
    "extrabees.species.creosote": "无",
    "extrabees.species.cyan": "无",
    "extrabees.species.cyanite": "不稳定",
    "extrabees.species.darkened": "黑暗",
    "extrabees.species.decomposing": "无",
    "extrabees.species.desolate": "饥饿",
    "extrabees.species.diamond": "无",
    "extrabees.species.distilled": "无",
    "extrabees.species.ecstatic": "能量",
    "extrabees.species.emerald": "无",
    "extrabees.species.energetic": "雷击",
    "extrabees.species.excited": "雷击",
    "extrabees.species.farm": "无",
    "extrabees.species.freezing": "冻结",
    "extrabees.species.fruit": "成熟",
    "extrabees.species.fuel": "无",
    "extrabees.species.fungal": "蘑菇",
    "extrabees.species.glowstone": "举世皆敌",
    "extrabees.species.glutinous": "胶化",
    "extrabees.species.gnawing": "无",
    "extrabees.species.gold": "无",
    "extrabees.species.granite": "无",
    "extrabees.species.gray": "无",
    "extrabees.species.greek": "无",
    "extrabees.species.green": "无",
    "extrabees.species.growing": "无",
    "extrabees.species.hazardous": "爆炸就是艺术",
    "extrabees.species.infectious": "剧毒",
    "extrabees.species.ink": "蓄水",
    "extrabees.species.iron": "无",
    "extrabees.species.jaded": "皆大欢喜",
    "extrabees.species.lapis": "无",
    "extrabees.species.latex": "无",
    "extrabees.species.lead": "无",
    "extrabees.species.lightblue": "无",
    "extrabees.species.lightgray": "无",
    "extrabees.species.limegreen": "无",
    "extrabees.species.magenta": "无",
    "extrabees.species.malicious": "剧毒",
    "extrabees.species.marble": "无",
    "extrabees.species.milk": "无",
    "extrabees.species.mineral": "无",
    "extrabees.species.mystical": "无",
    "extrabees.species.nickel": "无",
    "extrabees.species.nuclear": "不稳定",
    "extrabees.species.ocean": "蓄水",
    "extrabees.species.oil": "无",
    "extrabees.species.orange": "无",
    "extrabees.species.pink": "无",
    "extrabees.species.platinum": "无",
    "extrabees.species.prehistoric": "无",
    "extrabees.species.primeval": "无",
    "extrabees.species.purple": "无",
    "extrabees.species.pyrite": "无",
    "extrabees.species.quantum": "无",
    "extrabees.species.radioactive": "不稳定",
    "extrabees.species.red": "无",
    "extrabees.species.relic": "无",
    "extrabees.species.resin": "无",
    "extrabees.species.ripening": "无",
    "extrabees.species.river": "蓄水",
    "extrabees.species.rock": "无",
    "extrabees.species.roman": "无",
    "extrabees.species.rotten": "生成僵尸",
    "extrabees.species.ruby": "无",
    "extrabees.species.sapphire": "无",
    "extrabees.species.shadow": "黑暗",
    "extrabees.species.silver": "无",
    "extrabees.species.sodalite": "无",
    "extrabees.species.spatial": "重力",
    "extrabees.species.sphalerite": "无",
    "extrabees.species.sticky": "胶化",
    "extrabees.species.stone": "无",
    "extrabees.species.sugar": "无",
    "extrabees.species.swamp": "缓慢",
    "extrabees.species.sweet": "无",
    "extrabees.species.tempered": "流星",
    "extrabees.species.thriving": "无",
    "extrabees.species.tin": "无",
    "extrabees.species.titanium": "无",
    "extrabees.species.tungstate": "无",
    "extrabees.species.unstable": "不稳定",
    "extrabees.species.unusual": "重力",
    "extrabees.species.virulent": "剧毒",
    "extrabees.species.viscous": "胶化",
    "extrabees.species.volcanic": "流星",
    "extrabees.species.water": "蓄水",
    "extrabees.species.white": "无",
    "extrabees.species.yellorium": "不稳定",
    "extrabees.species.yellow": "无",
    "extrabees.species.zinc": "无",
    "forestry.speciesAgrarian": "丰饶",
    "forestry.speciesAustere": "爆炸就是艺术",
    "forestry.speciesAvenging": "辐射",
    "forestry.speciesBoggy": "嗜菇",
    "forestry.speciesCommon": "无",
    "forestry.speciesCultivated": "无",
    "forestry.speciesDemonic": "燃烧[林业]",
    "forestry.speciesDiligent": "无",
    "forestry.speciesEdenic": "探索",
    "forestry.speciesEnded": "末影",
    "forestry.speciesExotic": "剧毒",
    "forestry.speciesFarmerly": "无",
    "forestry.speciesFiendish": "举世皆敌",
    "forestry.speciesForest": "无",
    "forestry.speciesFrugal": "无",
    "forestry.speciesGlacial": "冻结",
    "forestry.speciesHermitic": "抗拒",
    "forestry.speciesHeroic": "勇士",
    "forestry.speciesIcy": "冻结",
    "forestry.speciesImperial": "皆大欢喜",
    "forestry.speciesIndustrious": "无",
    "forestry.speciesMajestic": "无",
    "forestry.speciesMarshy": "无",
    "forestry.speciesMeadows": "无",
    "forestry.speciesMiry": "无",
    "forestry.speciesModest": "无",
    "forestry.speciesMonastic": "无",
    "forestry.speciesNoble": "无",
    "forestry.speciesPhantasmal": "复苏",
    "forestry.speciesRural": "无",
    "forestry.speciesSecluded": "无",
    "forestry.speciesSinister": "举世皆敌",
    "forestry.speciesSpectral": "重生",
    "forestry.speciesSteadfast": "无",
    "forestry.speciesTropical": "剧毒",
    "forestry.speciesUnweary": "无",
    "forestry.speciesValiant": "无",
    "forestry.speciesVengeful": "辐射",
    "forestry.speciesVindictive": "辐射",
    "forestry.speciesWintry": "冻结",
    "gendustry.bee.Agricultural": "无",
    "gendustry.bee.Alchemical": "无",
    "gendustry.bee.Apothecary": "科学！！！",
    "gendustry.bee.Armored": "无",
    "gendustry.bee.Artillery": "燃烧[林业]",
    "gendustry.bee.Baguette": "无",
    "gendustry.bee.Balanced": "无",
    "gendustry.bee.black": "无",
    "gendustry.bee.blue": "无",
    "gendustry.bee.Bomber": "燃烧[林业]",
    "gendustry.bee.brown": "无",
    "gendustry.bee.Buried": "无",
    "gendustry.bee.Chevron": "无",
    "gendustry.bee.Controller": "无",
    "gendustry.bee.Crepuscular": "无",
    "gendustry.bee.cyan": "无",
    "gendustry.bee.Darkness": "铁锭蜜化",
    "gendustry.bee.Deeplearner": "无",
    "gendustry.bee.derpious": "无",
    "gendustry.bee.Experienced": "无",
    "gendustry.bee.Fear": "治安维持",
    "gendustry.bee.Feesh": "无",
    "gendustry.bee.Fiotic": "无",
    "gendustry.bee.Fissile": "燃烧[林业]",
    "gendustry.bee.Flux": "无",
    "gendustry.bee.Formic": "无",
    "gendustry.bee.Gorgon": "无",
    "gendustry.bee.Gravity": "无",
    "gendustry.bee.gray": "无",
    "gendustry.bee.green": "无",
    "gendustry.bee.GunDevil": "燃烧[林业]",
    "gendustry.bee.Gunman": "燃烧[林业]",
    "gendustry.bee.Helplessness": "瞬世",
    "gendustry.bee.Heraldry": "无",
    "gendustry.bee.Herblore": "燃烧[林业]",
    "gendustry.bee.Isekai": "无",
    "gendustry.bee.lightblue": "无",
    "gendustry.bee.lime": "无",
    "gendustry.bee.Luctor": "无",
    "gendustry.bee.magenta": "无",
    "gendustry.bee.Meatball": "无",
    "gendustry.bee.Necronomibee": "无",
    "gendustry.bee.orange": "无",
    "gendustry.bee.Oxygen": "无",
    "gendustry.bee.pink": "无",
    "gendustry.bee.purple": "无",
    "gendustry.bee.Pyramid": "举世皆敌",
    "gendustry.bee.Pyromaniacal": "燃烧[职业蜜蜂]",
    "gendustry.bee.Radiant": "无",
    "gendustry.bee.red": "无",
    "gendustry.bee.Restlessclam": "无",
    "gendustry.bee.Ringbearer": "无",
    "gendustry.bee.Ryleyan": "无",
    "gendustry.bee.Salty": "无",
    "gendustry.bee.Sandman": "无",
    "gendustry.bee.Sanitizing": "无",
    "gendustry.bee.Shadow": "无",
    "gendustry.bee.Shyre": "无",
    "gendustry.bee.silver": "无",
    "gendustry.bee.Sniper": "燃烧[林业]",
    "gendustry.bee.Solitude": "复职培训",
    "gendustry.bee.Soulsucking": "无",
    "gendustry.bee.Springwater": "无",
    "gendustry.bee.Stargazer": "无",
    "gendustry.bee.Stormborn": "无",
    "gendustry.bee.Thorium": "无",
    "gendustry.bee.Trinity": "无",
    "gendustry.bee.Twilight": "无",
    "gendustry.bee.Uranium": "无",
    "gendustry.bee.Uselessforce": "无",
    "gendustry.bee.Warrior": "无",
    "gendustry.bee.white": "无",
    "gendustry.bee.yellow": "无",
    "gendustry.bee.ThermallyExpanded": "无",
    "magicbees.speciesAbandoned": "抗拒",
    "magicbees.speciesAESkystone": "燃烧[林业]",
    "magicbees.speciesAluminium": "无",
    "magicbees.speciesApatite": "无",
    "magicbees.speciesArcane": "无",
    "magicbees.speciesArdite": "无",
    "magicbees.speciesAttuned": "无",
    "magicbees.speciesAware": "无",
    "magicbees.speciesBatty": "古怪",
    "magicbees.speciesBeef": "牛群",
    "magicbees.speciesBigbad": "嚎叫",
    "magicbees.speciesBOTAlfheim": "梦境",
    "magicbees.speciesBOTBlossom": "无",
    "magicbees.speciesBOTBotanic": "无",
    "magicbees.speciesBOTDreaming": "时光扭曲",
    "magicbees.speciesBOTFloral": "无",
    "magicbees.speciesBOTRooted": "无",
    "magicbees.speciesBOTSomnolent": "时光扭曲",
    "magicbees.speciesBOTVazbee": "无",
    "magicbees.speciesBronze": "无",
    "magicbees.speciesCatty": "野猫",
    "magicbees.speciesCertus": "无",
    "magicbees.speciesCharmed": "无",
    "magicbees.speciesChicken": "鸡",
    "magicbees.speciesCobalt": "无",
    "magicbees.speciesCopper": "无",
    "magicbees.speciesCrumbling": "崩溃",
    "magicbees.speciesDiamond": "无",
    "magicbees.speciesDoctoral": "勇士",
    "magicbees.speciesDraconic": "末影",
    "magicbees.speciesEarthy": "无",
    "magicbees.speciesEldritch": "无",
    "magicbees.speciesElectrum": "无",
    "magicbees.speciesEmerald": "无",
    "magicbees.speciesEnchanted": "无",
    "magicbees.speciesEsoteric": "无",
    "magicbees.speciesEthereal": "无",
    "magicbees.speciesFirey": "无",
    "magicbees.speciesFluix": "无",
    "magicbees.speciesForlorn": "抗拒",
    "magicbees.speciesGhastly": "幽魂",
    "magicbees.speciesGold": "无",
    "magicbees.speciesHateful": "末影",
    "magicbees.speciesHorse": "马",
    "magicbees.speciesInfernal": "举世皆敌",
    "magicbees.speciesInvar": "燃烧[林业]",
    "magicbees.speciesInvisible": "隐身",
    "magicbees.speciesIron": "无",
    "magicbees.speciesLead": "无",
    "magicbees.speciesLordly": "沉醉",
    "magicbees.speciesManyullyn": "无",
    "magicbees.speciesMutable": "无",
    "magicbees.speciesMysterious": "无",
    "magicbees.speciesMystical": "无",
    "magicbees.speciesNameless": "举世皆敌",
    "magicbees.speciesNickel": "无",
    "magicbees.speciesOblivion": "举世皆敌",
    "magicbees.speciesOsmium": "无",
    "magicbees.speciesPlatinum": "燃烧[林业]",
    "magicbees.speciesPork": "猪群",
    "magicbees.speciesPupil": "无",
    "magicbees.speciesRSAFluxed": "燃烧[林业]",
    "magicbees.speciesSavant": "无",
    "magicbees.speciesScholarly": "无",
    "magicbees.speciesSheepish": "羊",
    "magicbees.speciesSilicon": "无",
    "magicbees.speciesSilver": "无",
    "magicbees.speciesSkulking": "无",
    "magicbees.speciesSorcerous": "无",
    "magicbees.speciesSoul": "无",
    "magicbees.speciesSpirit": "无",
    "magicbees.speciesSpiteful": "末影",
    "magicbees.speciesSupernatural": "无",
    "magicbees.speciesTEAmped": "生成狂风人",
    "magicbees.speciesTEBlizzy": "冻结",
    "magicbees.speciesTECoal": "无",
    "magicbees.speciesTEDante": "燃烧[林业]",
    "magicbees.speciesTEDestabilized": "无",
    "magicbees.speciesTEEndearing": "无",
    "magicbees.speciesTEGelid": "生成暴雪人",
    "magicbees.speciesTEGrounded": "无",
    "magicbees.speciesTELux": "燃烧[林业]",
    "magicbees.speciesTEPyro": "燃烧[林业]",
    "magicbees.speciesTERocking": "生成岩石人",
    "magicbees.speciesTEShocking": "无",
    "magicbees.speciesTEWinsome": "无",
    "magicbees.speciesTimely": "时光扭曲",
    "magicbees.speciesTin": "无",
    "magicbees.speciesTransmuting": "蜕变",
    "magicbees.speciesUnusual": "无",
    "magicbees.speciesWatery": "无",
    "magicbees.speciesWindy": "无",
    "magicbees.speciesWithering": "凋零[魔法蜜蜂]",
    "gendustry.bee.Tinkerest": "无",
    "gendustry.bee.Serenading": "无",
    "gendustry.bee.Helium": "无",
    "gendustry.bee.Nucleartechnician": "无",
    "gendustry.bee.Fluorine": "无",
    "gendustry.bee.Thermallyexpanded": "无"
} as IData;

static EFFECT_DESCRIPTIONS as IData = {
    "瞬世": "加速附近方块实体的游戏刻。",
    "酸液": "按以下顺序变化方块：泥土/草方块 -> 沙子；石头/圆石 -> 沙砾。",
    "举世皆敌": "伤害附近实体。忽略物品。",
    "铸甲师": "强化附近鲜花坛上盔甲的属性，每件最多加100%。效果应用于所有护甲值，而并非仅影响被强化的盔甲。",
    "刺客": "杀死附近蜂巢中的蜜蜂。可放置在蜜蜂嗡嗡枪中使用。若放置在蜂箱内，会自杀，不产出雄蜂和公主蜂。",
    "古怪": "在附近生成蝙蝠。",
    "皆大欢喜": "给予附近玩家生命恢复效果。",
    "牛群": "在附近生成牛。",
    "燃烧[职业蜜蜂]": "在附近蔓延火焰。",
    "行商": "使用村民交易配方，将相邻容器内的物品交易为绿宝石。",
    "屠夫": "将附近的动物杀到只剩一对。",
    "嚎叫": "在附近生成狼。",
    "野猫": "在附近生成豹猫。但是似乎不起作用。",
    "鸡": "在附近生成鸡。",
    "上发条": "为附近的发条引擎上发条至黄色阶段。",
    "爆炸就是艺术": "被爬行者炸到时伤害玩家。",
    "生成爬行者": "在附近生成爬行者。",
    "崩溃": "按以下顺序变化方块：石头 -> 圆石 -> 苔石；石砖 -> 裂石砖 -> 苔石砖。",
    "碎矿": "将附近鲜花坛上的金属矿物粉碎为2-4个金属粉。",
    "治愈": "移除负面药水效果，并缓慢治疗附近实体。",
    "树皮叮咬者": "从附近的树中获得树皮资源存入蜂箱。",
    "黑暗": "给予附近玩家致盲效果。",
    "梦境": "自动将附近的原木与石头转化为活木与活石。",
    "沉醉": "给予附近玩家反胃效果。",
    "胶化": "在活动范围内的固体方块上生成胶质网。",
    "缠雷": "对附近实体造成类似雷击的伤害。",
    "末影": "伤害附近玩家。",
    "探索": "给予附近玩家经验。",
    "“阻止”爆炸": "生成带有凋零效果的爬行者。没有掉落物。",
    "丰饶": "给予附近方块随机刻，但好像失效了，尽管代码看着没问题。",
    "烟火": "若蜂箱露天，在附近生成烟花。",
    "燃烧[林业]": "点燃附近实体。忽略物品。",
    "时运采掘": "在活动范围内，使用时运 III自动挖掘矿物，无视活动范围的Y轴限制。挖掘速度与蜜蜂工作速度以及产量倍率有关。",
    "冻结": "将附近的水源方块冻结为冰。",
    "募集捐款": "然而并不会为你做什么 :)",
    "幽魂": "在附近生成恶魂。",
    "重力": "移动附近的实体。",
    "生长": "对附近的树苗施加骨粉效果。",
    "勇士": "伤害附近的敌对生物。",
    "蜜釉": "为附近鲜花坛上的食物添加蜜釉强化。根据食物种类和放置在鲜花坛上的时间给予不同强度的伤害吸收效果。",
    "马": "在附近生成马。但是似乎不起作用。",
    "饥饿": "给予附近玩家饥饿效果。",
    "畜牧": "喂食附近动物。",
    "隐身": "给予附近玩家隐身效果。",
    "铁锭蜜化": "将附近鲜花坛上的铁锭转化为蜂巢锭。",
    "废品贩售": "使用村民交易配方，将相邻容器内的绿宝石交易为随机物品。",
    "雷击": "在附近引发雷击。无视天气，会生成火。",
    "石匠": "自动将附近的圆石转化为石头，接着变成石砖。也可将安山岩、花岗岩以及闪长岩变为对应的磨制方块。",
    "流星": "若蜂箱露天，在附近下火焰弹雨。",
    "采掘": "在活动范围内，自动挖掘矿物，无视活动范围的Y轴限制。挖掘速度与蜜蜂工作速度以及产量倍率有关。",
    "蘑菇": "对附近的蘑菇施加骨粉效果。",
    "嗜菇": "随机将附近的草方块变为菌丝，长出蘑菇，将蘑菇变为哞菇。",
    "无": "没有特殊效果！",
    "绘画": "在附近的墙上生成画。",
    "剧毒": "给予附近玩家中毒效果。",
    "治安维持": "攻击附近敌对生物并获取其掉落物，具有很强的抢夺效果。",
    "猪群": "在附近生成猪。",
    "能量": "缓慢充能附近BuildCraft模组的机器。",
    "牧师": "为附近鲜花坛上的物品附魔。附魔等级由书架决定。",
    "辐射": "伤害附近实体。摧毁附近方块。",
    "重生": "若地上存在对应掉落物，生成骷髅、僵尸以及烈焰人。",
    "修复": "自动修复附近鲜花坛上的物品。修复速度与蜜蜂工作速度以及产量倍率有关。",
    "抗拒": "附近的生物会主动远离玩家。",
    "复苏": "若地上存在对应掉落物，生成爬行者、末影人、蜘蛛、洞穴蜘蛛、恶魂以及末影龙。",
    "复职培训": "恢复附近鲜花坛上蜜蜂基因的特殊效果。",
    "RF感生": "为相邻方块生成RF能量。",
    "成熟": "对附近的树叶施加骨粉效果来产出果实。",
    "科学！！！": "在附近产生不影响方块实体的爆炸。",
    "砺刃": "使附加鲜花坛上的剑获得伤害提升，最多5点。",
    "羊": "在附近生成羊。",
    "精准采掘": "在活动范围内，使用精准采集自动挖掘矿物，无视活动范围的Y轴限制。挖掘速度与蜜蜂工作速度以及产量倍率有关。",
    "生成骷髅": null,
    "缓慢": "给予附近玩家缓慢效果。",
    "时光扭曲": "给予附近玩家缓慢效果。但是似乎不起作用。",
    "熔炼": "自动烧炼附近鲜花坛上的物品。",
    "生成岩石人": "在附近生成岩石人。",
    "生成狂风人": "在附近生成狂风人。",
    "生成暴雪人": "在附近生成暴雪人。",
    "征税": "获取附近生物的掉落物，但不会伤害或者杀死它们。",
    "转位": "将相同材料的相邻方块交换位置。忽略方块实体。",
    "蜕变": "在沙漠中，将沙子变为砂岩，在对应群系将石头/圆石变为采掘砖块或深渊砖块。",
    "不稳定": "伤害附近玩家。",
    "蓄水": "向附近的储罐填充水。",
    "凋零[更多蜜蜂]": "给予附近玩家凋零效果。",
    "凋零[魔法蜜蜂]": "给予附近玩家凋零效果。",
    "小小Womble": "收集附近物品存入蜂箱。",
    "嗖嗖，到手了！": "从附近的玩家身上偷取物品。",
    "生成僵尸": "在附近生成僵尸。"
} as IData;





function effectDescription(stack as IItemStack, showDescription as bool, shift as bool) as string {
    if (isNull(stack.tag) || isNull(stack.tag.Genome) || isNull(stack.tag.Genome.Chromosomes)) return null;
    val species as IData = stack.tag.Genome.Chromosomes[0] as IData;
    val dominant as string = species.UID0.asString();
    val recessive as string = species.UID1.asString();

    if (dominant != recessive) return null;

    val effectData as IData = EFFECTS.memberGet(dominant);
    if (isNull(effectData)) {
        if (showDescription) { return null; }
        return "特殊效果：§c缺失 (" + dominant + ")§r";
    }
    val effect as string = effectData.asString();
    
    if (!showDescription) { return "特殊效果：" + effect; }
    if (!shift) { return "§8§o按住Shift键显示特殊效果描述§r"; }

    val descriptionData = EFFECT_DESCRIPTIONS.memberGet(effect);
    if (isNull(descriptionData)) return "§c缺失描述 (" + dominant + ")§r";
    return descriptionData.asString();
}

val beeItems = [<forestry:bee_princess_ge:0>, <forestry:bee_drone_ge:0>, <forestry:bee_queen_ge:0>] as IIngredient[];

for beeItem in beeItems {
    beeItem.addAdvancedTooltip(function(item) { return effectDescription(item, false, false); });
    beeItem.addShiftTooltip(
        function(item) { return effectDescription(item, true, true); }, 
        function(item) { return effectDescription(item, true, false); }
    );
}

/* for beeItem in beeItems {
    beeItem.addAdvancedTooltip(function(item) {   
        val species = item.tag.Genome.Chromosomes[0];
        return species.UID0.asString() + " - " + species.UID1.asString();
    });
} */