<contenttweaker:creeponia_callstone>.addTooltip(format.red("Use in this dimension:  Creeponia"));
<contenttweaker:diabetic_callstone>.addTooltip(format.red("Use in this dimension:  Oi"));
<contenttweaker:stormborn_callstone>.addTooltip(format.red("Use in this dimension:  Twilight Forest"));
<contenttweaker:deeplands_callstone>.addTooltip(format.red("Use in this dimension:  Deeplands"));
<contenttweaker:crystevia_callstone>.addTooltip(format.red("Use in this dimension:  Crystevia"));
<contenttweaker:iromine_callstone>.addTooltip(format.red("Use in this dimension:  Iromine"));
<contenttweaker:betweenlands_callstone_0>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:betweenlands_callstone_1>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:betweenlands_callstone_2>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:betweenlands_callstone_3>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:betweenlands_callstone_4>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:betweenlands_callstone_5>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:betweenlands_callstone_6>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:betweenlands_callstone_7>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:betweenlands_callstone_8>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:key_of_flesh_dominion>.addTooltip(format.red("Use in this dimension:  Abyss"));
<contenttweaker:borean_callstone>.addTooltip(format.red("Use in this dimension:  Borean"));
<contenttweaker:lunalus_callstone>.addTooltip(format.red("Use in this dimension:  Lunalus"));
<contenttweaker:wildwood_callstone>.addTooltip(format.red("Use in this dimension:  Wildwood"));
<contenttweaker:skythern_callstone>.addTooltip(format.red("Use in this dimension:  Skythern"));
<contenttweaker:immortallis_callstone>.addTooltip(format.red("Use in this dimension:  Immortallis"));
<contenttweaker:horrific_callstone>.addTooltip(format.red("Use in this dimension:  Hator"));
<contenttweaker:harbinger_callstone>.addTooltip(format.red("Use in this dimension:  Twilight Forest"));
<contenttweaker:dream_callstone>.addTooltip(format.red("Use in this dimension:  Vethea"));
<contenttweaker:nightmare_callstone>.addTooltip(format.red("Use in this dimension:  Vethea"));
<contenttweaker:sacred_callstone>.addTooltip(format.red("Use in this dimension:  Aether"));
<contenttweaker:call_of_the_haunted>.addTooltip(format.red("Use in this dimension:  Twilight Forest"));
<contenttweaker:recursion_prison_key>.addTooltip(format.red("Use in this dimension:  End"));
<contenttweaker:sticky_callstone>.addTooltip(format.red("Use in this dimension:  Diamerisma"));
<contenttweaker:runic_key>.addTooltip(format.red("Use in this dimension:  Runandor"));
<contenttweaker:skeletal_callstone>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:fluix_callstone>.addTooltip(format.red("Use in this dimension:  End"));
<contenttweaker:tainted_callstone>.addTooltip(format.red("Use in this dimension:  Vibe"));
<contenttweaker:radiating_callstone>.addTooltip(format.red("Use in this dimension:  End"));
<contenttweaker:demonologist_callstone>.addTooltip(format.red("Use in this dimension:  Haumea"));
<contenttweaker:armorer_callstone>.addTooltip(format.red("Use in this dimension:  Osiris"));
<contenttweaker:undead_callstone>.addTooltip(format.red("Use in this dimension:  Dark Realm"));
<contenttweaker:pharos_callstone>.addTooltip(format.red("Use in this dimension:  Ptah"));
<contenttweaker:trinity_callstone>.addTooltip(format.red("Use in this dimension:  Hator"));
<contenttweaker:peaceful_oath_callstone>.addTooltip(format.red("Use in this dimension:  Europa"));
<contenttweaker:gun_devil_callstone>.addTooltip(format.red("Use in this dimension:  Falacer"));
<contenttweaker:unburied_callstone>.addTooltip(format.red("Use in this dimension:  Oi"));
<contenttweaker:anemic_callstone>.addTooltip(format.red("Use in this dimension:  Deep Dark"));
<contenttweaker:orbital_callstone>.addTooltip(format.red("Use in this dimension:  End"));
<contenttweaker:energy_chicken_callstone>.addTooltip(format.red("Use in this dimension:  Sedna"));
<contenttweaker:biome_ritual_callstone>.addTooltip(format.red("Use in this dimension:  Ptah"));
<contenttweaker:hidden_power_callstone>.addTooltip(format.red("Use in this dimension:  Proxima"));
<contenttweaker:thorny_callstone>.addTooltip(format.red("Use in this dimension:  Precasia"));
<contenttweaker:umberstone_callstone>.addTooltip(format.red("Use in this dimension:  Erebus"));
<contenttweaker:cleansing_callstone>.addTooltip(format.red("Use in this dimension:  Abyssal Wasteland"));
<contenttweaker:furnace_callstone>.addTooltip(format.red("Use in this dimension:  Furnace"));
<contenttweaker:grand_magician_callstone>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:rulers_of_terra_callstone>.addTooltip(format.red("Use in this dimension:  Furatto"));
<contenttweaker:nero_callstone>.addTooltip(format.red("Use in this dimension:  Nero"));
<contenttweaker:deep_knowledge_callstone>.addTooltip(format.red("Use in this dimension:  Gardencia"));
<contenttweaker:greenlight_callstone>.addTooltip(format.red("Use in this dimension:  Furnace"));
<contenttweaker:wrought_summoner>.addTooltip(format.red("Use in this dimension:  Deeplands"));
<contenttweaker:akathartos_callstone>.addTooltip(format.red("Use in this dimension:  Akathartos"));
<contenttweaker:anomaly_detector_stage_3>.addTooltip(format.red("Use in this dimension:  Wildwood"));
<contenttweaker:voraceous_worm_callstone>.addTooltip(format.red("Use in this dimension:  Oi"));
<contenttweaker:dreadful_prison_key>.addTooltip(format.red("Use in this dimension:  Iceika"));
<contenttweaker:ancient_wyvern_callstone>.addTooltip(format.red("Use in this dimension:  Lyndenwyrm"));
<contenttweaker:oblivionaire_callstone>.addTooltip(format.red("Use in this dimension:  Abyssal Wasteland"));
<contenttweaker:fluix_historian_callstone>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:whitefire_callstone>.addTooltip(format.red("Use in this dimension:  Furnace"));
<contenttweaker:undead_botanist_callstone>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:forbidden_garden_callstone>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:energetic_prison_key>.addTooltip(format.red("Use in this dimension:  Alkemia"));
<contenttweaker:draconian_prison_key>.addTooltip(format.red("Use in this dimension:  Lyndenwyrm"));
<contenttweaker:soulsucking_callstone>.addTooltip(format.red("Use in this dimension:  Skythern"));
<contenttweaker:crepuscular_callstone>.addTooltip(format.red("Use in this dimension:  Twilight Forest"));
<contenttweaker:zoi_callstone>.addTooltip(format.red("Use in this dimension:  Zoi"));
<contenttweaker:secret_lurker_callstone>.addTooltip(format.red("Use in this dimension:  Myrmex"));
<contenttweaker:eldritch_crab_callstone>.addTooltip(format.red("Use in this dimension:  Emptiness"));
<contenttweaker:tainted_loop_callstone>.addTooltip(format.red("Use in this dimension:  Vibe"));
<contenttweaker:pauram_callstone>.addTooltip(format.red("Use in this dimension:  Pauram"));
<contenttweaker:infernal_furnace_callstone>.addTooltip(format.red("Use in this dimension:  Furnace"));
<contenttweaker:monumental_meatball_callstone>.addTooltip(format.red("Use in this dimension:  Gallifrey"));
<contenttweaker:furnace_secret_callstone>.addTooltip(format.red("Use in this dimension:  Gallifrey"));
<contenttweaker:hidden_errors_callstone>.addTooltip(format.red("Use in this dimension:  Aether"));
<contenttweaker:tarantula_callstone>.addTooltip(format.red("Use in this dimension:  Erebus"));
<contenttweaker:requiem_of_the_arbiter>.addTooltip(format.red("Use in this dimension:  End"));
<contenttweaker:master_of_the_true_tongue_callstone>.addTooltip(format.red("Use in this dimension:  End"));
<contenttweaker:gambling_addiction_prison_key>.addTooltip(format.red("Use in this dimension:  Nether"));
<contenttweaker:lucky_box_aether_bronze>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:lucky_box_aether_silver>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:lucky_box_aether_gold>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:lucky_box_twilight_books>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:lucky_box_twilight_weapons>.addTooltip(format.red("Use in this dimension:  Overworld"));
<contenttweaker:dread_cleansing_callstone>.addTooltip(format.red("Use in this dimension:  Bedrock Dimension"));
<contenttweaker:rites_of_liberation>.addTooltip(format.red("Use in this dimension:  Overworld"));