#loader contenttweaker

import mods.contenttweaker.Color;
import mods.contenttweaker.MaterialSystem;
import mods.contenttweaker.tconstruct.MaterialBuilder;

val realmitetic = mods.contenttweaker.tconstruct.MaterialBuilder.create("realmite");
realmitetic.color = 0xb5682a;
realmitetic.craftable = false;
realmitetic.liquid = <fluid:molten_realmite>;
realmitetic.castable = true;
realmitetic.addItem(<item:divinerpg:realmite_ingot>,1,144);
realmitetic.addItem(<item:divinerpg:realmite_ore>, 1, 288);
realmitetic.representativeItem = <item:divinerpg:realmite_ingot>;
realmitetic.addHeadMaterialStats(250, 3.0f, 2.6f, 4);
realmitetic.addHandleMaterialStats(0.6, 80);
realmitetic.addBowMaterialStats(2.5, 0.7, 1);
realmitetic.addMaterialTrait("discounted");
realmitetic.itemLocalizer = function(thisMaterial, itemName){return "Realmite " + itemName;};
realmitetic.localizedName = "Realmite";
realmitetic.register();

val arlemitetic = mods.contenttweaker.tconstruct.MaterialBuilder.create("arlemite");
arlemitetic.color = 0x30b524;
arlemitetic.craftable = false;
arlemitetic.liquid = <fluid:molten_arlemite>;
arlemitetic.castable = true;
arlemitetic.addItem(<item:divinerpg:arlemite_ingot>,1,144);
arlemitetic.addItem(<item:divinerpg:arlemite_ore>, 1, 288);
arlemitetic.representativeItem = <item:divinerpg:arlemite_ingot>;
arlemitetic.addHeadMaterialStats(190, 3.2f, 2.4f, 4);
arlemitetic.addHandleMaterialStats(0.6, 70);
arlemitetic.addBowMaterialStats(0.65, 1.3, 1);
arlemitetic.addMaterialTrait("discounted");
arlemitetic.itemLocalizer = function(thisMaterial, itemName){return "Arlemite " + itemName;};
arlemitetic.localizedName = "Arlemite";
arlemitetic.register();

val rupeetic = mods.contenttweaker.tconstruct.MaterialBuilder.create("rupee");
rupeetic.color = 0x2441bf;
rupeetic.craftable = false;
rupeetic.liquid = <fluid:molten_rupee>;
rupeetic.castable = true;
rupeetic.addItem(<item:divinerpg:rupee_ingot>,1,144);
rupeetic.addItem(<item:divinerpg:rupee_ore>, 1, 288);
rupeetic.representativeItem = <item:divinerpg:rupee_ingot>;
rupeetic.addHeadMaterialStats(1000, 1.4f, 0.4f, 4);
rupeetic.addHandleMaterialStats(0.6, 900);
rupeetic.addBowMaterialStats(2.6, 1.3, 0);
rupeetic.addMaterialTrait("shocking");
rupeetic.itemLocalizer = function(thisMaterial, itemName){return "Rupee " + itemName;};
rupeetic.localizedName = "Rupee";
rupeetic.register();

val netheritetic = mods.contenttweaker.tconstruct.MaterialBuilder.create("netherite");
netheritetic.color = 0xde241b;
netheritetic.craftable = false;
netheritetic.liquid = <fluid:molten_netherite>;
netheritetic.castable = true;
netheritetic.addItem(<item:divinerpg:netherite_ingot>,1,144);
netheritetic.addItem(<item:divinerpg:netherite_ore>, 1, 288);
netheritetic.representativeItem = <item:divinerpg:netherite_ingot>;
netheritetic.addHeadMaterialStats(200, 2.4f, 2.4f, 15);
netheritetic.addHandleMaterialStats(0.6, 100);
netheritetic.addBowMaterialStats(2.0, 8.4, 0);
netheritetic.addMaterialTrait("blazing");
netheritetic.itemLocalizer = function(thisMaterial, itemName){return "Netherite " + itemName;};
netheritetic.localizedName = "Netherite";
netheritetic.register();

val bloodmastertic = mods.contenttweaker.tconstruct.MaterialBuilder.create("bloodmaster");
bloodmastertic.color = 0x540505;
bloodmastertic.craftable = false;
bloodmastertic.liquid = <fluid:bloodmaster_metal>;
bloodmastertic.castable = true;
bloodmastertic.addItem(<item:contenttweaker:bloodmaster_block>,1,144);
bloodmastertic.representativeItem = <item:contenttweaker:bloodmaster_block>;
bloodmastertic.addHeadMaterialStats(2000, 15.3f, 25.52f, 15);
bloodmastertic.addHandleMaterialStats(3, 5000);
bloodmastertic.addExtraMaterialStats(60);
bloodmastertic.addProjectileMaterialStats();
bloodmastertic.addBowMaterialStats(0.5, 18.4, 15);
bloodmastertic.addMaterialTrait("blazing");
bloodmastertic.itemLocalizer = function(thisMaterial, itemName){return "Bloodmaster " + itemName;};
bloodmastertic.localizedName = "Bloodmaster";
bloodmastertic.register();


val adamantiumtic = mods.contenttweaker.tconstruct.MaterialBuilder.create("adamantium");
adamantiumtic.color = 0x415150;
adamantiumtic.craftable = false;
adamantiumtic.liquid = <fluid:molten_adamantium>;
adamantiumtic.castable = true;
adamantiumtic.addItem(<item:contenttweaker:adamantium_ingot>,1,144);
adamantiumtic.representativeItem = <item:contenttweaker:adamantium_ingot>;
adamantiumtic.addHeadMaterialStats(100000, 55.5f, 2.33f, 15);
adamantiumtic.addHandleMaterialStats(3, 100000);
adamantiumtic.addExtraMaterialStats(100000);
adamantiumtic.addProjectileMaterialStats();
adamantiumtic.addBowMaterialStats(4.5, 18.4, 12);
adamantiumtic.addMaterialTrait("magnetic2");
adamantiumtic.itemLocalizer = function(thisMaterial, itemName){return "Adamantium " + itemName;};
adamantiumtic.localizedName = "Adamantium";
adamantiumtic.register();

// val vibraniumtic = mods.contenttweaker.tconstruct.MaterialBuilder.create("vibranium");
// vibraniumtic.color = 0x3e436b;
// vibraniumtic.craftable = false;
// vibraniumtic.liquid = <fluid:vibranium>;
// vibraniumtic.castable = true;
// vibraniumtic.addItem(<item:materialpart:vibranium:ingot>,1,144);
// vibraniumtic.representativeItem = <item:materialpart:vibranium:ingot>;
// vibraniumtic.addHeadMaterialStats(5000, 30.0f, 60.12f, 3);
// vibraniumtic.addHandleMaterialStats(6, 5000);
// vibraniumtic.addExtraMaterialStats(5000);
// vibraniumtic.addProjectileMaterialStats();
// vibraniumtic.addBowMaterialStats(0.2, 20.0, 18);
// vibraniumtic.addMaterialTrait("vindictive");
// vibraniumtic.itemLocalizer = function(thisMaterial, itemName){return "Vibranium " + itemName;};
// vibraniumtic.localizedName = "Vibranium";
// vibraniumtic.register();

val vibraniumtic = mods.contenttweaker.tconstruct.MaterialBuilder.create("vibranium");
vibraniumtic.color = 0x3e436b;
vibraniumtic.craftable = false;
vibraniumtic.liquid = <fluid:vibranium>;
vibraniumtic.castable = true;
vibraniumtic.addItem(<ore:ingotVibranium>,1,144);
vibraniumtic.addItem(<item:contenttweaker:vibranium_chunk>,1,144);
vibraniumtic.representativeItem = <item:contenttweaker:vibranium_chunk>;
vibraniumtic.addHeadMaterialStats(5000, 60.0f, 30.12f, 3);
vibraniumtic.addHandleMaterialStats(6, 5000);
vibraniumtic.addExtraMaterialStats(5000);
vibraniumtic.addProjectileMaterialStats();
vibraniumtic.addBowMaterialStats(0.2, 20.0, 182);
vibraniumtic.addMaterialTrait("sos");
vibraniumtic.itemLocalizer = function(thisMaterial, itemName){return "Vibranium " + itemName;};
vibraniumtic.localizedName = "Vibranium";
vibraniumtic.register();

// val vibraniumalloytic = mods.contenttweaker.tconstruct.MaterialBuilder.create("vibranium_alloy");
// vibraniumalloytic.color = 0x1e2742;
// vibraniumalloytic.craftable = false;
// vibraniumalloytic.liquid = <fluid:molten_vibranium_alloy>;
// vibraniumalloytic.castable = true;
// vibraniumalloytic.addItem(<item:materialpart:vibranium_alloy:ingot>,1,144);
// vibraniumalloytic.representativeItem = <item:materialpart:vibranium_alloy:ingot>;
// vibraniumalloytic.addHeadMaterialStats(5000, 40.0f, 1.12f, 100);
// vibraniumalloytic.addHandleMaterialStats(1, 5000);
// vibraniumalloytic.addExtraMaterialStats(5000);
// vibraniumalloytic.addProjectileMaterialStats();
// vibraniumalloytic.addBowMaterialStats(0.5, 4.0, 45);
// vibraniumalloytic.addMaterialTrait("prosperous");
// vibraniumalloytic.itemLocalizer = function(thisMaterial, itemName){return "Vibranium Alloy " + itemName;};
// vibraniumalloytic.localizedName = "Vibranium Alloy";
// vibraniumalloytic.register();

val vibraniumalloytic = mods.contenttweaker.tconstruct.MaterialBuilder.create("vibranium_alloy");
vibraniumalloytic.color = 0x1e2742;
vibraniumalloytic.craftable = false;
vibraniumalloytic.liquid = <fluid:molten_vibranium_alloy>;
vibraniumalloytic.castable = true;
vibraniumalloytic.addItem(<ore:ingotVibraniumAlloy>,1,144);
vibraniumalloytic.addItem(<item:contenttweaker:vibraniumalloy_chunk>,1,144);
vibraniumalloytic.representativeItem = <item:contenttweaker:vibraniumalloy_chunk>;
vibraniumalloytic.addHeadMaterialStats(5000, 1.0f, 40.12f, 100);
vibraniumalloytic.addHandleMaterialStats(1, 5000);
vibraniumalloytic.addExtraMaterialStats(5000);
vibraniumalloytic.addProjectileMaterialStats();
vibraniumalloytic.addBowMaterialStats(0.5, 4.0, 45);
vibraniumalloytic.addMaterialTrait("endspeed");
vibraniumalloytic.itemLocalizer = function(thisMaterial, itemName){return "Vibranium Alloy " + itemName;};
vibraniumalloytic.localizedName = "Vibranium Alloy";
vibraniumalloytic.register();

// val enderfeathertic = mods.contenttweaker.tconstruct.MaterialBuilder.create("ender_feather");
// enderfeathertic.color = 0x1e2742;
// enderfeathertic.craftable = true;
// enderfeathertic.castable = false;
// enderfeathertic.addItem(<item:contenttweaker:ender_feather>,1,144);
// enderfeathertic.representativeItem = <item:contenttweaker:ender_feather>;
// enderfeathertic.addHeadMaterialStats(1, 50.0f, 1.12f, 100);
// enderfeathertic.addHandleMaterialStats(0.1f, 1);
// enderfeathertic.addExtraMaterialStats(1);
// enderfeathertic.addProjectileMaterialStats();
// enderfeathertic.addBowMaterialStats(0.1, 6.0, 30);
// enderfeathertic.addFletchingMaterialStats(1.0f, 0.1f);
// enderfeathertic.addArrowShaftMaterialStats(0.1f, 100);
// enderfeathertic.addMaterialTrait("elemental");
// enderfeathertic.itemLocalizer = function(thisMaterial, itemName){return "Ender Feather " + itemName;};
// enderfeathertic.localizedName = "Ender Feather";
// enderfeathertic.register();

val parafrosynium = mods.contenttweaker.tconstruct.MaterialBuilder.create("parafrosynium");
parafrosynium.color = 0x6534d9;
parafrosynium.craftable = false;
parafrosynium.liquid = <fluid:parafrosynium>;
parafrosynium.castable = true;
parafrosynium.addItem(<item:contenttweaker:parafrosynium>,1,144);
parafrosynium.representativeItem = <item:contenttweaker:parafrosynium>;
parafrosynium.addHeadMaterialStats(2000, 0.8f, 5555.0f, 1);
parafrosynium.addHandleMaterialStats(2, 2000);
parafrosynium.addExtraMaterialStats(2000);
parafrosynium.addProjectileMaterialStats();
parafrosynium.addMaterialTrait("darktraveler");
parafrosynium.addMaterialTrait("runic1");
parafrosynium.addMaterialTrait("stalwart");
parafrosynium.itemLocalizer = function(thisMaterial, itemName){return "Parafrosynium " + itemName;};
parafrosynium.localizedName = "Parafrosynium";
parafrosynium.register();

val rosidian = mods.contenttweaker.tconstruct.MaterialBuilder.create("rosidian");
rosidian.color = 0xb82aa7;
rosidian.craftable = false;
rosidian.liquid = <fluid:rosidian>;
rosidian.castable = true;
rosidian.addItem(<item:contenttweaker:rosidian_ingot>,1,144);
rosidian.representativeItem = <item:contenttweaker:rosidian_ingot>;
rosidian.addHeadMaterialStats(300, 2.2f, 85.0f, 3);
rosidian.addHandleMaterialStats(1, 200);
rosidian.addExtraMaterialStats(300);
rosidian.addProjectileMaterialStats();
rosidian.addMaterialTrait("sharp");
rosidian.addMaterialTrait("jaded");
rosidian.addMaterialTrait("natureswrath");
rosidian.itemLocalizer = function(thisMaterial, itemName){return "Rosidian " + itemName;};
rosidian.localizedName = "Rosidian";
rosidian.register();

val phasingalloy = mods.contenttweaker.tconstruct.MaterialBuilder.create("phasing_alloy");
phasingalloy.color = 0x2bffc3;
phasingalloy.craftable = false;
phasingalloy.liquid = <fluid:phasing_alloy>;
phasingalloy.castable = true;
phasingalloy.addItem(<item:contenttweaker:phasing_alloy_plate>,1,144);
phasingalloy.representativeItem = <item:contenttweaker:phasing_alloy_plate>;
phasingalloy.addHeadMaterialStats(4000, 45.2f, 44.2f, 1);
phasingalloy.addHandleMaterialStats(1, 4000);
phasingalloy.addExtraMaterialStats(4000);
phasingalloy.addProjectileMaterialStats();
phasingalloy.addMaterialTrait("reflect");
phasingalloy.addMaterialTrait("exploit");
phasingalloy.addMaterialTrait("portly");
phasingalloy.itemLocalizer = function(thisMaterial, itemName){return "Phasing Alloy " + itemName;};
phasingalloy.localizedName = "Phasing Alloy";
phasingalloy.register();

val wroughtiron = mods.contenttweaker.tconstruct.MaterialBuilder.create("wrought_iron");
wroughtiron.color = 0x636666;
wroughtiron.craftable = false;
wroughtiron.liquid = <fluid:molten_wrought_iron>;
wroughtiron.castable = true;
wroughtiron.addItem(<item:contenttweaker:wrought_iron_plate>,1,144);
wroughtiron.representativeItem = <item:contenttweaker:wrought_iron_plate>;
wroughtiron.addHeadMaterialStats(3000, 0.2f, 46.5f, 1);
wroughtiron.addHandleMaterialStats(1, 3000);
wroughtiron.addExtraMaterialStats(3000);
wroughtiron.addProjectileMaterialStats();
wroughtiron.addMaterialTrait("hailhydra");
wroughtiron.addMaterialTrait("unnamed");
wroughtiron.addMaterialTrait("sharp");
wroughtiron.itemLocalizer = function(thisMaterial, itemName){return "Wrought Iron " + itemName;};
wroughtiron.localizedName = "Wrought Iron";
wroughtiron.register();

val barathosynium = mods.contenttweaker.tconstruct.MaterialBuilder.create("barathosynium");
barathosynium.color = 0xad6432;
barathosynium.craftable = false;
barathosynium.liquid = <fluid:molten_barathosynium>;
barathosynium.castable = true;
barathosynium.addItem(<item:contenttweaker:barathosynium_ingot>,1,144);
barathosynium.representativeItem = <item:contenttweaker:barathosynium_ingot>;
barathosynium.addHeadMaterialStats(200, 4.2f, 31.0f, 4);
barathosynium.addHandleMaterialStats(3, 200);
barathosynium.addExtraMaterialStats(200);
barathosynium.addProjectileMaterialStats();
barathosynium.addMaterialTrait("thunder2");
barathosynium.addMaterialTrait("flame2");
barathosynium.addMaterialTrait("frost2");
barathosynium.itemLocalizer = function(thisMaterial, itemName){return "Barathosynium " + itemName;};
barathosynium.localizedName = "Barathosynium";
barathosynium.register();

val abyssalflesh = mods.contenttweaker.tconstruct.MaterialBuilder.create("abyssal_flesh");
abyssalflesh.color = 0xb3326e;
abyssalflesh.craftable = true;
// abyssalflesh.liquid = <fluid:molten_barathosynium>;
abyssalflesh.castable = false;
abyssalflesh.addItem(<item:contenttweaker:abyssal_flesh>,1,144);
abyssalflesh.representativeItem = <item:contenttweaker:abyssal_flesh>;
abyssalflesh.addHeadMaterialStats(10, 4.2f, 35.0f, 1);
abyssalflesh.addHandleMaterialStats(5, 10);
abyssalflesh.addExtraMaterialStats(10);
abyssalflesh.addProjectileMaterialStats();
abyssalflesh.addMaterialTrait("energyeater");
abyssalflesh.addMaterialTrait("manaeater");
abyssalflesh.addMaterialTrait("dreadpurity");
abyssalflesh.addMaterialTrait("laced");
abyssalflesh.itemLocalizer = function(thisMaterial, itemName){return "Abyssal Flesh " + itemName;};
abyssalflesh.localizedName = "Abyssal Flesh";
abyssalflesh.register();


val ichorium = mods.contenttweaker.tconstruct.MaterialBuilder.create("ichorium");
ichorium.color = 0xa85a00;
ichorium.craftable = false;
ichorium.liquid = <fluid:crystalline_ichorium>;
ichorium.castable = true;
ichorium.addItem(<item:contenttweaker:ichorium_gem>,1,144);
ichorium.representativeItem = <item:contenttweaker:ichorium_gem>;
ichorium.addHeadMaterialStats(5000, 12.0f, 300.0f, 15);
ichorium.addHandleMaterialStats(1, 5000);
ichorium.addExtraMaterialStats(5000);
ichorium.addProjectileMaterialStats();
ichorium.addMaterialTrait("bloodymary");
ichorium.addMaterialTrait("ecological");
ichorium.itemLocalizer = function(thisMaterial, itemName){return "Crystalline Ichorium " + itemName;};
ichorium.localizedName = "Crystalline Ichorium";
ichorium.register();

val kaiyualloy = mods.contenttweaker.tconstruct.MaterialBuilder.create("kaiyu");
kaiyualloy.color = 0xe6c875;
kaiyualloy.craftable = true;
// kaiyualloy.liquid = <fluid:crystalline_ichorium>;
kaiyualloy.castable = false;
kaiyualloy.addItem(<item:contenttweaker:skeletal_kaiyu_bone>,1,144);
kaiyualloy.representativeItem = <item:contenttweaker:skeletal_kaiyu_bone>;
kaiyualloy.addHeadMaterialStats(710, 11.0f, 25.0f, 2);
kaiyualloy.addHandleMaterialStats(2, 800);
kaiyualloy.addExtraMaterialStats(600);
kaiyualloy.addProjectileMaterialStats();
kaiyualloy.addBowMaterialStats(0.5, 8.0, 30);
kaiyualloy.addMaterialTrait("bone_shock");
kaiyualloy.addMaterialTrait("high_in_calcium");
kaiyualloy.itemLocalizer = function(thisMaterial, itemName){return "Kaiyu " + itemName;};
kaiyualloy.localizedName = "Kaiyu";
kaiyualloy.register();


val berserksteel = mods.contenttweaker.tconstruct.MaterialBuilder.create("berserk_steel");
berserksteel.color = 0xa18782;
berserksteel.craftable = false;
berserksteel.liquid = <fluid:berserker_steel>;
berserksteel.castable = true;
berserksteel.addItem(<item:contenttweaker:berserker_steel_ingot>,1,144);
berserksteel.representativeItem = <item:contenttweaker:berserker_steel_ingot>;
berserksteel.addHeadMaterialStats(1000, 12.0f, 310.0f, 10);
berserksteel.addHandleMaterialStats(1, 1000);
berserksteel.addExtraMaterialStats(1000);
berserksteel.addProjectileMaterialStats();
berserksteel.addMaterialTrait("exploit");
berserksteel.addMaterialTrait("payback");
berserksteel.addMaterialTrait("mod_lavacow.unholytouch");
berserksteel.addMaterialTrait("holy");
berserksteel.itemLocalizer = function(thisMaterial, itemName){return "Berserker Steel " + itemName;};
berserksteel.localizedName = "Berserker Steel";
berserksteel.register();


val stoneendlesshunger = mods.contenttweaker.tconstruct.MaterialBuilder.create("stone_endless_hunger");
stoneendlesshunger.color = 0xcc2990;
stoneendlesshunger.craftable = true;
//stoneendlesshunger.liquid = <fluid:berserker_steel>;
stoneendlesshunger.castable = false;
stoneendlesshunger.addItem(<item:contenttweaker:stone_of_endless_hunger>,1,144);
stoneendlesshunger.representativeItem = <item:contenttweaker:stone_of_endless_hunger>;
stoneendlesshunger.addHeadMaterialStats(100, 11.0f, 100.0f, 3);
stoneendlesshunger.addHandleMaterialStats(1, 300);
stoneendlesshunger.addExtraMaterialStats(300);
stoneendlesshunger.addProjectileMaterialStats();
stoneendlesshunger.addMaterialTrait("sentience");
stoneendlesshunger.addMaterialTrait("necrotic");
stoneendlesshunger.addMaterialTrait("mod_lavacow.famine");
stoneendlesshunger.itemLocalizer = function(thisMaterial, itemName){return "Endlessly Hungry " + itemName;};
stoneendlesshunger.localizedName = "Endlessly Hungry";
stoneendlesshunger.register();

val infdreadshard = mods.contenttweaker.tconstruct.MaterialBuilder.create("infused_dread_shard");
infdreadshard.color = 0x67807f;
infdreadshard.craftable = true;
//stoneendlesshunger.liquid = <fluid:berserker_steel>;
infdreadshard.castable = false;
infdreadshard.addItem(<item:contenttweaker:infused_dread_shard>,1,144);
infdreadshard.representativeItem = <item:contenttweaker:infused_dread_shard>;
infdreadshard.addHeadMaterialStats(500, 1.0f, 200.0f, 1);
infdreadshard.addHandleMaterialStats(1, 500);
infdreadshard.addExtraMaterialStats(500);
infdreadshard.addProjectileMaterialStats();
infdreadshard.addMaterialTrait("freezing");
infdreadshard.addMaterialTrait("frost2");
infdreadshard.addMaterialTrait("apocalypse");
infdreadshard.itemLocalizer = function(thisMaterial, itemName){return "Infused Dread " + itemName;};
infdreadshard.localizedName = "Infused Dread";
infdreadshard.register();

val brightsteelalloy = mods.contenttweaker.tconstruct.MaterialBuilder.create("brightsteel_alloy");
brightsteelalloy.color = 0x7330c9;
brightsteelalloy.craftable = false;
brightsteelalloy.liquid = <fluid:brightsteel_alloy>;
brightsteelalloy.castable = true;
brightsteelalloy.addItem(<item:contenttweaker:brightsteel_alloy_ingot>,1,144);
brightsteelalloy.representativeItem = <item:contenttweaker:brightsteel_alloy_ingot>;
brightsteelalloy.addHeadMaterialStats(500, 100.0f, 250.0f, 10);
brightsteelalloy.addHandleMaterialStats(5, 500);
brightsteelalloy.addExtraMaterialStats(500);
brightsteelalloy.addProjectileMaterialStats();
brightsteelalloy.addMaterialTrait("runic2");
brightsteelalloy.addMaterialTrait("flame2");
brightsteelalloy.addMaterialTrait("morganlefay");
brightsteelalloy.addMaterialTrait("baron");
brightsteelalloy.itemLocalizer = function(thisMaterial, itemName){return "Brightsteel Alloy " + itemName;};
brightsteelalloy.localizedName = "Brightsteel Alloy";
brightsteelalloy.register();

val runandium = mods.contenttweaker.tconstruct.MaterialBuilder.create("runandium");
runandium.color = 0x66bdab;
runandium.craftable = false;
runandium.liquid = <fluid:runandium>;
runandium.castable = true;
runandium.addItem(<item:contenttweaker:runandium_ingot>,1,144);
runandium.representativeItem = <item:contenttweaker:runandium_ingot>;
runandium.addHeadMaterialStats(100, 10.0f, 180.0f, 10);
runandium.addHandleMaterialStats(1, 100);
runandium.addExtraMaterialStats(100);
runandium.addProjectileMaterialStats();
runandium.addMaterialTrait("evil_pressure");
runandium.addMaterialTrait("apocalypse");
runandium.addMaterialTrait("laced");
runandium.itemLocalizer = function(thisMaterial, itemName){return "Runandium " + itemName;};
runandium.localizedName = "Runandium";
runandium.register();

val ascendeddracalloy = mods.contenttweaker.tconstruct.MaterialBuilder.create("ascended_draconic_alloy");
ascendeddracalloy.color = 0xff7300;
ascendeddracalloy.craftable = false;
ascendeddracalloy.liquid = <fluid:ascended_draconic_alloy>;
ascendeddracalloy.castable = true;
ascendeddracalloy.addItem(<item:contenttweaker:ascended_draconic_alloy>,1,144);
ascendeddracalloy.representativeItem = <item:contenttweaker:ascended_draconic_alloy>;
ascendeddracalloy.addHeadMaterialStats(100, 10.0f, 250.0f, 10);
ascendeddracalloy.addHandleMaterialStats(2, 100);
ascendeddracalloy.addExtraMaterialStats(100);
ascendeddracalloy.addProjectileMaterialStats();
ascendeddracalloy.addMaterialTrait("spiky");
ascendeddracalloy.addMaterialTrait("prickly");
ascendeddracalloy.addMaterialTrait("ghastly");
ascendeddracalloy.itemLocalizer = function(thisMaterial, itemName){return "Ascended Draconic Alloy " + itemName;};
ascendeddracalloy.localizedName = "Ascended Draconic Alloy";
ascendeddracalloy.register();

val neutronium = mods.contenttweaker.tconstruct.MaterialBuilder.create("neutronium");
neutronium.color = 0x969696;
neutronium.craftable = true;
// neutronium.liquid = <fluid:ascended_draconic_alloy>;
neutronium.castable = false;
neutronium.addItem(<item:avaritia:resource:4>,1,144);
neutronium.representativeItem = <item:avaritia:resource:4>;
neutronium.addHeadMaterialStats(4000, 10.0f, 300.0f, 10);
neutronium.addHandleMaterialStats(1, 5000);
neutronium.addExtraMaterialStats(5000);
neutronium.addProjectileMaterialStats();
neutronium.addMaterialTrait("uplifting");
neutronium.addMaterialTrait("shulking");
neutronium.addMaterialTrait("frost2");
neutronium.itemLocalizer = function(thisMaterial, itemName){return "Neutronium " + itemName;};
neutronium.localizedName = "Neutronium";
neutronium.register();


val hihiirokane = mods.contenttweaker.tconstruct.MaterialBuilder.create("hihi_irokane");
hihiirokane.color = 0x751256;
hihiirokane.craftable = false;
hihiirokane.liquid = <fluid:hihi_irokane>;
hihiirokane.castable = true;
hihiirokane.addItem(<item:contenttweaker:hihi_irokane>,1,144);
hihiirokane.representativeItem = <item:contenttweaker:hihi_irokane>;
hihiirokane.addHeadMaterialStats(2000, 0.8f, 3000.0f, 1);
hihiirokane.addHandleMaterialStats(2, 2000);
hihiirokane.addExtraMaterialStats(2000);
hihiirokane.addProjectileMaterialStats();
hihiirokane.addMaterialTrait("energyeater");
hihiirokane.addMaterialTrait("manaeater");
hihiirokane.addMaterialTrait("necrotic");
hihiirokane.itemLocalizer = function(thisMaterial, itemName){return "Hihi'Irokane " + itemName;};
hihiirokane.localizedName = "Hihi'Irokane";
hihiirokane.register();

val orichalcum = mods.contenttweaker.tconstruct.MaterialBuilder.create("orichalcum");
orichalcum.color = 0x21d9c0;
orichalcum.craftable = false;
orichalcum.liquid = <fluid:orichalcum>;
orichalcum.castable = true;
orichalcum.addItem(<item:contenttweaker:orichalcum>,1,144);
orichalcum.representativeItem = <item:contenttweaker:orichalcum>;
orichalcum.addHeadMaterialStats(9000, 0.8f, 6500.0f, 1);
orichalcum.addHandleMaterialStats(9, 9000);
orichalcum.addExtraMaterialStats(9000);
orichalcum.addProjectileMaterialStats();
orichalcum.addMaterialTrait("mind");
orichalcum.addMaterialTrait("body");
orichalcum.addMaterialTrait("soul1");
orichalcum.addMaterialTrait("thunder2");
orichalcum.addMaterialTrait("flame2");
orichalcum.addMaterialTrait("frost2");
orichalcum.itemLocalizer = function(thisMaterial, itemName){return "Orichalcum " + itemName;};
orichalcum.localizedName = "Orichalcum";
orichalcum.register();