<contenttweaker:enchdesc_coralium>.addTooltip(format.red("Applies Coralium Plague to all hit enemies (like Fire Aspect but for coralium plague instead)"));
<contenttweaker:enchdesc_dread>.addTooltip(format.red("Applies Dread Plague to all hit enemies (like Fire Aspect but for dread plague instead)"));
<contenttweaker:enchdesc_iron_wall>.addTooltip(format.red("Immunity to most knockback effects."));
<contenttweaker:enchdesc_light_pierce>.addTooltip(format.red("Extra damage to Shadow Mobs. +2.5 Damage per Level"));
<contenttweaker:enchdesc_multi_rend>.addTooltip(format.red("Allows the Staff of rending to drain from mobs in a aoe (~5 blocks)"));
<contenttweaker:enchdesc_sapping>.addTooltip(format.red("Makes the Staff of rending charge faster, charges level times faster"));
<contenttweaker:enchdesc_airtight_seal>.addTooltip(format.red("Allows armor pieces to act like spacesuits"));
<contenttweaker:enchdesc_archmage>.addTooltip(format.red("Can be applied to Staves to reduce the rune cost, each level reduces rune cost by 1 (min 1.)"));
<contenttweaker:enchdesc_brace>.addTooltip(format.red("Allows Guns/Shotguns to be used in offhand"));
<contenttweaker:enchdesc_control>.addTooltip(format.red("Reduces recoil from guns, -15% recoil per level"));
<contenttweaker:enchdesc_crush>.addTooltip(format.red("Increases knockback on Mauls, +15% per Level"));
<contenttweaker:enchdesc_curse_of_greed>.addTooltip(format.red("Increases ammo, energy, and rune usage on weapons"));
<contenttweaker:enchdesc_form>.addTooltip(format.red("Reduces shotgun spread, -15% spread per level"));
<contenttweaker:enchdesc_intervention>.addTooltip(format.red("Like Soulbound but has a 20% chance of removing itself"));
<contenttweaker:enchdesc_recharge>.addTooltip(format.red("Reduces the spirit cost of blasters, -7% cost per level"));
<contenttweaker:enchdesc_sever>.addTooltip(format.red("Increases crit damage on greatblades, +15% damage per level"));
<contenttweaker:enchdesc_shell>.addTooltip(format.red("Increases damage on guns, +10% damage per level"));
<contenttweaker:enchdesc_night_vision>.addTooltip(format.red("Grants perm night vision potion effect."));
<contenttweaker:enchdesc_scorching_heat>.addTooltip(format.red("Smelts mined blocks works with fortune."));
<contenttweaker:enchdesc_magic_protection_bewitchment>.addTooltip(format.red("Protection from Magic damage"));
<contenttweaker:enchdesc_eternal_compass>.addTooltip(format.red("Upgrades the atlas to give a compass pointing to grave on death"));
<contenttweaker:enchdesc_reading>.addTooltip(format.red("Lets you read books inside bibliocraft bookshelves"));
<contenttweaker:enchdesc_holding>.addTooltip(format.red("Increases size of inventories and rf storage, adds 9 slots or 50% storage per level"));
<contenttweaker:enchdesc_insight>.addTooltip(format.red("Killing Mobs and breaking blocks drops extra XP orbs, level - level*4 bonus XP"));
<contenttweaker:enchdesc_leech>.addTooltip(format.red("Mob kills restore health, half a heart per level"));
<contenttweaker:enchdesc_multishot>.addTooltip(format.red("Fires additional arrows, 1 extra arrow per level. Needs Bloodmaster stage to use"));
<contenttweaker:enchdesc_smashing>.addTooltip(format.red("Pulverises broken ores, mined ores drop 2 dust"));
<contenttweaker:enchdesc_smelting>.addTooltip(format.red("Smelts mined blocks"));
<contenttweaker:enchdesc_soulbound>.addTooltip(format.red("Items are kept on death, has a 1/(level+1) chance of reducing its level each time"));
<contenttweaker:enchdesc_vorpal>.addTooltip(format.red("Small chance of massive damage and extra chance for head drops, +5% chance for 10x damage and +20% head drop chance per level. Needs Draconic Evolution stage to use."));
<contenttweaker:enchdesc_magic_siphon>.addTooltip(format.red("Grants a chance to absorb positive effects from the target. Needs Divine Stage to use."));
<contenttweaker:enchdesc_plague_bringer>.addTooltip(format.red("Chance to apply negative effects to the target"));
<contenttweaker:enchdesc_shadow_step>.addTooltip(format.red("Lowers detection radius by mobs based on how dark it is"));
<contenttweaker:enchdesc_soulbound_corail_tombstone>.addTooltip(format.red("Items are kept on death"));
<contenttweaker:enchdesc_autosmelt>.addTooltip(format.red("Smelts mined blocks"));
<contenttweaker:enchdesc_excavation>.addTooltip(format.red("Mines identical blocks, Max 26,42,58 blocks and levels 1-3"));
<contenttweaker:enchdesc_experience_boost>.addTooltip(format.red("Killing Mobs and breaking blocks drops extra XP orbs, mobs drop level*8 extra xp, mined blocks drop level*8 times more xp"));
<contenttweaker:enchdesc_lifeleech>.addTooltip(format.red("Gain health when hitting and killing mobs, heal level health with every hit and a bonus of either 0-5 health or up to 20% of the mobs health"));
<contenttweaker:enchdesc_magnet>.addTooltip(format.red("When applied on tools, attracts dropped items and XP orbs. range is level*4 blocks"));
<contenttweaker:enchdesc_multijump>.addTooltip(format.red("Gives extra jumps, upto level extra jumps in a row, 3 second cooldown after spending all jumps"));
<contenttweaker:enchdesc_multishot_cyclic>.addTooltip(format.red("Fires extra arrows, fires 2 arrows horrozontally bonus arrows are vanilla"));
<contenttweaker:enchdesc_quickdraw>.addTooltip(format.red("Draw bows 3x faster."));
<contenttweaker:enchdesc_reach>.addTooltip(format.red("More reach for breaking blocks and mobs, +11 Block Reach (BROKEN?)"));
<contenttweaker:enchdesc_venom>.addTooltip(format.red("Applies poison on the target. level of poison scales with enchant level, poison lasts 3 seconds per level"));
<contenttweaker:enchdesc_waterwalking>.addTooltip(format.red("Lets the player walk ontop of water like a solid block, sneak to swim."));
<contenttweaker:enchdesc_aftershock>.addTooltip(format.red("Weaker Vorpal, gives a 5% chance per level of double damage"));
<contenttweaker:enchdesc_rive>.addTooltip(format.red("Makes tools like a hammer, mines a 3 x 3 x level area"));
<contenttweaker:enchdesc_reaper>.addTooltip(format.red("Boosts chance of mobs dropping Souls, +0.1% chance for mobs per level, +0.125% chance for animals per level. Wyvern sword and bow adds 1 level, Draconic sword and bow adds 2 levels, Staff of power adds 3 levels."));
<contenttweaker:enchdesc_fire_imbuement>.addTooltip(format.red("Temporarily adds extra fire damage and burns mobs, only obtainable from the Flaming weapon spell."));
<contenttweaker:enchdesc_frost_imbuement>.addTooltip(format.red("Temporarily adds extra Frost damage, only obtainable from the Freezing weapon spell."));
<contenttweaker:enchdesc_frost_protection>.addTooltip(format.red("Protection from Frost damage"));
<contenttweaker:enchdesc_imbuement>.addTooltip(format.red("Temporarily adds extra damage like sharpness, only obtainable from the Imbue weapon spell."));
<contenttweaker:enchdesc_magic_protection>.addTooltip(format.red("Protection from Magic damage"));
<contenttweaker:enchdesc_shock_protection>.addTooltip(format.red("Protection from Shock damage"));
<contenttweaker:enchdesc_decay>.addTooltip(format.red("Applied on melee weapons inflicts wither"));
<contenttweaker:enchdesc_repellent>.addTooltip(format.red("Chance to teleport attackers away"));
<contenttweaker:enchdesc_shimmer>.addTooltip(format.red("Does nothing"));
<contenttweaker:enchdesc_soulbound_ender_io>.addTooltip(format.red("Items are kept on death"));
<contenttweaker:enchdesc_withering>.addTooltip(format.red("Applied on bows inflicts wither"));
<contenttweaker:enchdesc_autosmelt_endercore>.addTooltip(format.red("Smelts mined blocks dosent work with fortune."));
<contenttweaker:enchdesc_xp_boost>.addTooltip(format.red("More XP when killing mobs or breaking blocks, approximately ((level+1)*30)% more XP"));
<contenttweaker:enchdesc_kaboomerang>.addTooltip(format.red("Boomerang causes a damage only explosive"));
<contenttweaker:enchdesc_zoomerang>.addTooltip(format.red("Increases base speed by 30% per level and multiplies return speed by level"));
<contenttweaker:enchdesc_burnerang>.addTooltip(format.red("Sets mobs on fire for 5 seconds"));
<contenttweaker:enchdesc_bladerang>.addTooltip(format.red("Increases Boomerang Damage by Level * 4"));
<contenttweaker:enchdesc_boomereaperang>.addTooltip(format.red("Boomerang breaks and collects plants"));
<contenttweaker:enchdesc_corrosive>.addTooltip(format.red("Mobs recieve +20% (+10% for bosses) damage per level"));
<contenttweaker:enchdesc_lifesteal>.addTooltip(format.red("Get Healed (5% * level * damage) when dealing damage."));
<contenttweaker:enchdesc_poisonous>.addTooltip(format.red("Inflicts mobs with poison for 8 seconds, level scales with enchantment level"));
<contenttweaker:enchdesc_flim_flam>.addTooltip(format.red("Does nothing"));
<contenttweaker:enchdesc_last_stand>.addTooltip(format.red("Prevents death at the cost of XP, XP cost is 50 / total levels"));
<contenttweaker:enchdesc_unstable>.addTooltip(format.red("When on boots, prevents fall damages and triggers an explosion by consuming gunpowder"));
<contenttweaker:enchdesc_electric_efficiency>.addTooltip(format.red("Lowers Power usage of Projectred Jetpacks?, 16x less power max"));
<contenttweaker:enchdesc_destruction>.addTooltip(format.red("Makes Crowbars like hammers"));
<contenttweaker:enchdesc_implosion>.addTooltip(format.red("Bane of Creepers but for Crowbars"));
<contenttweaker:enchdesc_smack>.addTooltip(format.red("Makes Crowbars better at hitting minecarts"));
<contenttweaker:enchdesc_wrecking>.addTooltip(format.red("Sharpness but for Crowbars"));
<contenttweaker:enchdesc_magnetic>.addTooltip(format.red("Mined blocks go directly into inventory"));
<contenttweaker:enchdesc_fuel_efficiency>.addTooltip(format.red("Lowers fuel usage by 20% per level"));
<contenttweaker:enchdesc_soul_stealer>.addTooltip(format.red("Collect more souls, each level gives an extra soul per kill"));
<contenttweaker:enchdesc_aqua_affinity>.addTooltip(format.red("Increases underwater mining speed, Removes the 5x speed decrement from mining underwater"));
<contenttweaker:enchdesc_bane_of_arthropods>.addTooltip(format.red("Extra damage to Arthropod Mobs. +2.5 Damage per Level"));
<contenttweaker:enchdesc_blast_protection>.addTooltip(format.red("Reduces explosion damage "));
<contenttweaker:enchdesc_curse_of_binding>.addTooltip(format.red("Equipped items cannot be removed."));
<contenttweaker:enchdesc_depth_strider>.addTooltip(format.red("Move faster in water, each level removes 1/3 of the water speed penalty"));
<contenttweaker:enchdesc_efficiency>.addTooltip(format.red("Increases mining speed, extra (1+(level^2)) mining speed"));
<contenttweaker:enchdesc_feather_falling>.addTooltip(format.red("Reduces fall damage"));
<contenttweaker:enchdesc_fire_aspect>.addTooltip(format.red("Sets mobs on fire, level * 4 seconds of burning"));
<contenttweaker:enchdesc_fire_protection>.addTooltip(format.red("Protection from Fire damage"));
<contenttweaker:enchdesc_flame>.addTooltip(format.red("Sets mobs on fire, 5 seconds of burning"));
<contenttweaker:enchdesc_fortune>.addTooltip(format.red("Chance for multiple drops, ~40% extra drops per level"));
<contenttweaker:enchdesc_frost_walker>.addTooltip(format.red("Freezes water around the player, level+2 range"));
<contenttweaker:enchdesc_infinity>.addTooltip(format.red("Bows don't consume arrows"));
<contenttweaker:enchdesc_knockback>.addTooltip(format.red("Increases knockback."));
<contenttweaker:enchdesc_looting>.addTooltip(format.red("Chance of more loot, increase max amount of common drops by level, rare drop chance increased by 1% per level. also gives a (level/level+1) chance of rare drops if the first dosent succeeed."));
<contenttweaker:enchdesc_luck_of_the_sea>.addTooltip(format.red("More treasure, less fish and junk, +2% treasure chance, -2% junk chance, and -0.15% fish chance"));
<contenttweaker:enchdesc_lure>.addTooltip(format.red("Fish bite faster, +- 1 second on the max and min bite times"));
<contenttweaker:enchdesc_mending>.addTooltip(format.red("Repairs the item using experience."));
<contenttweaker:enchdesc_power>.addTooltip(format.red("Increases arrow damage, level+1*25% extra damage per level"));
<contenttweaker:enchdesc_projectile_protection>.addTooltip(format.red("Protection from Projectile damage"));
<contenttweaker:enchdesc_protection>.addTooltip(format.red("Protection from Most damage types"));
<contenttweaker:enchdesc_punch>.addTooltip(format.red("Increases arrow knockback."));
<contenttweaker:enchdesc_respiration>.addTooltip(format.red("Breath longer underwater, +15 seconds breathing time and (level/(level+1)) chance of not taking drowning damage"));
<contenttweaker:enchdesc_sharpness>.addTooltip(format.red("More Melee Damage, ((Level+1)*0.5) Extra Damage"));
<contenttweaker:enchdesc_silk_touch>.addTooltip(format.red("Mined blocks drop themselves."));
<contenttweaker:enchdesc_smite>.addTooltip(format.red("Extra damage to Undead Mobs. +2.5 Damage per Level"));
<contenttweaker:enchdesc_sweeping_edge>.addTooltip(format.red("Increases the damage dealt by sweeping attacks, damage is (level/(level+1))% of the weapons normal damage"));
<contenttweaker:enchdesc_thorns>.addTooltip(format.red("Damages anything which hits you, has a (level*15)% chance of dealing 1-4 damage, multiple thorns pieces are rolled seperatly armour with thorns has a chance to take extra damage."));
<contenttweaker:enchdesc_unbreaking>.addTooltip(format.red("Reduces durability consumption, on average items last level times as long, armour lasts ~20% longer per level"));
<contenttweaker:enchdesc_curse_of_vanishing>.addTooltip(format.red("Item disappears on death."));
<contenttweaker:enchdesc_manabound>.addTooltip(format.red("Allows item to be repaired with mana."));
<contenttweaker:enchdesc_headhunter>.addTooltip(format.red("Increases chance for a skull to drop."));
<contenttweaker:enchdesc_aerial_affinity>.addTooltip(format.red("Removes the mining speed penalty while in the air or not touching the ground"));
<contenttweaker:enchdesc_blessing>.addTooltip(format.red("Chance to gain a random buff when hit"));
<contenttweaker:enchdesc_curse_bones>.addTooltip(format.red("Chance to gain bone shield when hit"));