#loader contenttweaker

import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Item;

var enchdesc_coralium = VanillaFactory.createItem("enchdesc_coralium");
enchdesc_coralium.register();
var enchdesc_dread = VanillaFactory.createItem("enchdesc_dread");
enchdesc_dread.register();
var enchdesc_iron_wall = VanillaFactory.createItem("enchdesc_iron_wall");
enchdesc_iron_wall.register();
var enchdesc_light_pierce = VanillaFactory.createItem("enchdesc_light_pierce");
enchdesc_light_pierce.register();
var enchdesc_multi_rend = VanillaFactory.createItem("enchdesc_multi_rend");
enchdesc_multi_rend.register();
var enchdesc_sapping = VanillaFactory.createItem("enchdesc_sapping");
enchdesc_sapping.register();
var enchdesc_airtight_seal = VanillaFactory.createItem("enchdesc_airtight_seal");
enchdesc_airtight_seal.register();
var enchdesc_archmage = VanillaFactory.createItem("enchdesc_archmage");
enchdesc_archmage.register();
var enchdesc_brace = VanillaFactory.createItem("enchdesc_brace");
enchdesc_brace.register();
var enchdesc_control = VanillaFactory.createItem("enchdesc_control");
enchdesc_control.register();
var enchdesc_crush = VanillaFactory.createItem("enchdesc_crush");
enchdesc_crush.register();
var enchdesc_curse_of_greed = VanillaFactory.createItem("enchdesc_curse_of_greed");
enchdesc_curse_of_greed.register();
var enchdesc_form = VanillaFactory.createItem("enchdesc_form");
enchdesc_form.register();
var enchdesc_intervention = VanillaFactory.createItem("enchdesc_intervention");
enchdesc_intervention.register();
var enchdesc_recharge = VanillaFactory.createItem("enchdesc_recharge");
enchdesc_recharge.register();
var enchdesc_sever = VanillaFactory.createItem("enchdesc_sever");
enchdesc_sever.register();
var enchdesc_shell = VanillaFactory.createItem("enchdesc_shell");
enchdesc_shell.register();
var enchdesc_night_vision = VanillaFactory.createItem("enchdesc_night_vision");
enchdesc_night_vision.register();
var enchdesc_scorching_heat = VanillaFactory.createItem("enchdesc_scorching_heat");
enchdesc_scorching_heat.register();
var enchdesc_magic_protection_bewitchment = VanillaFactory.createItem("enchdesc_magic_protection_bewitchment");
enchdesc_magic_protection_bewitchment.register();
var enchdesc_eternal_compass = VanillaFactory.createItem("enchdesc_eternal_compass");
enchdesc_eternal_compass.register();
var enchdesc_reading = VanillaFactory.createItem("enchdesc_reading");
enchdesc_reading.register();
var enchdesc_holding = VanillaFactory.createItem("enchdesc_holding");
enchdesc_holding.register();
var enchdesc_insight = VanillaFactory.createItem("enchdesc_insight");
enchdesc_insight.register();
var enchdesc_leech = VanillaFactory.createItem("enchdesc_leech");
enchdesc_leech.register();
var enchdesc_multishot = VanillaFactory.createItem("enchdesc_multishot");
enchdesc_multishot.register();
var enchdesc_smashing = VanillaFactory.createItem("enchdesc_smashing");
enchdesc_smashing.register();
var enchdesc_smelting = VanillaFactory.createItem("enchdesc_smelting");
enchdesc_smelting.register();
var enchdesc_soulbound = VanillaFactory.createItem("enchdesc_soulbound");
enchdesc_soulbound.register();
var enchdesc_vorpal = VanillaFactory.createItem("enchdesc_vorpal");
enchdesc_vorpal.register();
var enchdesc_magic_siphon = VanillaFactory.createItem("enchdesc_magic_siphon");
enchdesc_magic_siphon.register();
var enchdesc_plague_bringer = VanillaFactory.createItem("enchdesc_plague_bringer");
enchdesc_plague_bringer.register();
var enchdesc_shadow_step = VanillaFactory.createItem("enchdesc_shadow_step");
enchdesc_shadow_step.register();
var enchdesc_soulbound_corail_tombstone = VanillaFactory.createItem("enchdesc_soulbound_corail_tombstone");
enchdesc_soulbound_corail_tombstone.register();
var enchdesc_autosmelt = VanillaFactory.createItem("enchdesc_autosmelt");
enchdesc_autosmelt.register();
var enchdesc_excavation = VanillaFactory.createItem("enchdesc_excavation");
enchdesc_excavation.register();
var enchdesc_experience_boost = VanillaFactory.createItem("enchdesc_experience_boost");
enchdesc_experience_boost.register();
var enchdesc_lifeleech = VanillaFactory.createItem("enchdesc_lifeleech");
enchdesc_lifeleech.register();
var enchdesc_magnet = VanillaFactory.createItem("enchdesc_magnet");
enchdesc_magnet.register();
var enchdesc_multijump = VanillaFactory.createItem("enchdesc_multijump");
enchdesc_multijump.register();
var enchdesc_multishot_cyclic = VanillaFactory.createItem("enchdesc_multishot_cyclic");
enchdesc_multishot_cyclic.register();
var enchdesc_quickdraw = VanillaFactory.createItem("enchdesc_quickdraw");
enchdesc_quickdraw.register();
var enchdesc_reach = VanillaFactory.createItem("enchdesc_reach");
enchdesc_reach.register();
var enchdesc_venom = VanillaFactory.createItem("enchdesc_venom");
enchdesc_venom.register();
var enchdesc_waterwalking = VanillaFactory.createItem("enchdesc_waterwalking");
enchdesc_waterwalking.register();
var enchdesc_aftershock = VanillaFactory.createItem("enchdesc_aftershock");
enchdesc_aftershock.register();
var enchdesc_rive = VanillaFactory.createItem("enchdesc_rive");
enchdesc_rive.register();
var enchdesc_reaper = VanillaFactory.createItem("enchdesc_reaper");
enchdesc_reaper.register();
var enchdesc_fire_imbuement = VanillaFactory.createItem("enchdesc_fire_imbuement");
enchdesc_fire_imbuement.register();
var enchdesc_frost_imbuement = VanillaFactory.createItem("enchdesc_frost_imbuement");
enchdesc_frost_imbuement.register();
var enchdesc_frost_protection = VanillaFactory.createItem("enchdesc_frost_protection");
enchdesc_frost_protection.register();
var enchdesc_imbuement = VanillaFactory.createItem("enchdesc_imbuement");
enchdesc_imbuement.register();
var enchdesc_magic_protection = VanillaFactory.createItem("enchdesc_magic_protection");
enchdesc_magic_protection.register();
var enchdesc_shock_protection = VanillaFactory.createItem("enchdesc_shock_protection");
enchdesc_shock_protection.register();
var enchdesc_decay = VanillaFactory.createItem("enchdesc_decay");
enchdesc_decay.register();
var enchdesc_repellent = VanillaFactory.createItem("enchdesc_repellent");
enchdesc_repellent.register();
var enchdesc_shimmer = VanillaFactory.createItem("enchdesc_shimmer");
enchdesc_shimmer.register();
var enchdesc_soulbound_ender_io = VanillaFactory.createItem("enchdesc_soulbound_ender_io");
enchdesc_soulbound_ender_io.register();
var enchdesc_withering = VanillaFactory.createItem("enchdesc_withering");
enchdesc_withering.register();
var enchdesc_autosmelt_endercore = VanillaFactory.createItem("enchdesc_autosmelt_endercore");
enchdesc_autosmelt_endercore.register();
var enchdesc_xp_boost = VanillaFactory.createItem("enchdesc_xp_boost");
enchdesc_xp_boost.register();
var enchdesc_kaboomerang = VanillaFactory.createItem("enchdesc_kaboomerang");
enchdesc_kaboomerang.register();
var enchdesc_zoomerang = VanillaFactory.createItem("enchdesc_zoomerang");
enchdesc_zoomerang.register();
var enchdesc_burnerang = VanillaFactory.createItem("enchdesc_burnerang");
enchdesc_burnerang.register();
var enchdesc_bladerang = VanillaFactory.createItem("enchdesc_bladerang");
enchdesc_bladerang.register();
var enchdesc_boomereaperang = VanillaFactory.createItem("enchdesc_boomereaperang");
enchdesc_boomereaperang.register();
var enchdesc_corrosive = VanillaFactory.createItem("enchdesc_corrosive");
enchdesc_corrosive.register();
var enchdesc_lifesteal = VanillaFactory.createItem("enchdesc_lifesteal");
enchdesc_lifesteal.register();
var enchdesc_poisonous = VanillaFactory.createItem("enchdesc_poisonous");
enchdesc_poisonous.register();
var enchdesc_flim_flam = VanillaFactory.createItem("enchdesc_flim_flam");
enchdesc_flim_flam.register();
var enchdesc_last_stand = VanillaFactory.createItem("enchdesc_last_stand");
enchdesc_last_stand.register();
var enchdesc_unstable = VanillaFactory.createItem("enchdesc_unstable");
enchdesc_unstable.register();
var enchdesc_electric_efficiency = VanillaFactory.createItem("enchdesc_electric_efficiency");
enchdesc_electric_efficiency.register();
var enchdesc_destruction = VanillaFactory.createItem("enchdesc_destruction");
enchdesc_destruction.register();
var enchdesc_implosion = VanillaFactory.createItem("enchdesc_implosion");
enchdesc_implosion.register();
var enchdesc_smack = VanillaFactory.createItem("enchdesc_smack");
enchdesc_smack.register();
var enchdesc_wrecking = VanillaFactory.createItem("enchdesc_wrecking");
enchdesc_wrecking.register();
var enchdesc_magnetic = VanillaFactory.createItem("enchdesc_magnetic");
enchdesc_magnetic.register();
var enchdesc_fuel_efficiency = VanillaFactory.createItem("enchdesc_fuel_efficiency");
enchdesc_fuel_efficiency.register();
var enchdesc_soul_stealer = VanillaFactory.createItem("enchdesc_soul_stealer");
enchdesc_soul_stealer.register();
var enchdesc_aqua_affinity = VanillaFactory.createItem("enchdesc_aqua_affinity");
enchdesc_aqua_affinity.register();
var enchdesc_bane_of_arthropods = VanillaFactory.createItem("enchdesc_bane_of_arthropods");
enchdesc_bane_of_arthropods.register();
var enchdesc_blast_protection = VanillaFactory.createItem("enchdesc_blast_protection");
enchdesc_blast_protection.register();
var enchdesc_curse_of_binding = VanillaFactory.createItem("enchdesc_curse_of_binding");
enchdesc_curse_of_binding.register();
var enchdesc_depth_strider = VanillaFactory.createItem("enchdesc_depth_strider");
enchdesc_depth_strider.register();
var enchdesc_efficiency = VanillaFactory.createItem("enchdesc_efficiency");
enchdesc_efficiency.register();
var enchdesc_feather_falling = VanillaFactory.createItem("enchdesc_feather_falling");
enchdesc_feather_falling.register();
var enchdesc_fire_aspect = VanillaFactory.createItem("enchdesc_fire_aspect");
enchdesc_fire_aspect.register();
var enchdesc_fire_protection = VanillaFactory.createItem("enchdesc_fire_protection");
enchdesc_fire_protection.register();
var enchdesc_flame = VanillaFactory.createItem("enchdesc_flame");
enchdesc_flame.register();
var enchdesc_fortune = VanillaFactory.createItem("enchdesc_fortune");
enchdesc_fortune.register();
var enchdesc_frost_walker = VanillaFactory.createItem("enchdesc_frost_walker");
enchdesc_frost_walker.register();
var enchdesc_infinity = VanillaFactory.createItem("enchdesc_infinity");
enchdesc_infinity.register();
var enchdesc_knockback = VanillaFactory.createItem("enchdesc_knockback");
enchdesc_knockback.register();
var enchdesc_looting = VanillaFactory.createItem("enchdesc_looting");
enchdesc_looting.register();
var enchdesc_luck_of_the_sea = VanillaFactory.createItem("enchdesc_luck_of_the_sea");
enchdesc_luck_of_the_sea.register();
var enchdesc_lure = VanillaFactory.createItem("enchdesc_lure");
enchdesc_lure.register();
var enchdesc_mending = VanillaFactory.createItem("enchdesc_mending");
enchdesc_mending.register();
var enchdesc_power = VanillaFactory.createItem("enchdesc_power");
enchdesc_power.register();
var enchdesc_projectile_protection = VanillaFactory.createItem("enchdesc_projectile_protection");
enchdesc_projectile_protection.register();
var enchdesc_protection = VanillaFactory.createItem("enchdesc_protection");
enchdesc_protection.register();
var enchdesc_punch = VanillaFactory.createItem("enchdesc_punch");
enchdesc_punch.register();
var enchdesc_respiration = VanillaFactory.createItem("enchdesc_respiration");
enchdesc_respiration.register();
var enchdesc_sharpness = VanillaFactory.createItem("enchdesc_sharpness");
enchdesc_sharpness.register();
var enchdesc_silk_touch = VanillaFactory.createItem("enchdesc_silk_touch");
enchdesc_silk_touch.register();
var enchdesc_smite = VanillaFactory.createItem("enchdesc_smite");
enchdesc_smite.register();
var enchdesc_sweeping_edge = VanillaFactory.createItem("enchdesc_sweeping_edge");
enchdesc_sweeping_edge.register();
var enchdesc_thorns = VanillaFactory.createItem("enchdesc_thorns");
enchdesc_thorns.register();
var enchdesc_unbreaking = VanillaFactory.createItem("enchdesc_unbreaking");
enchdesc_unbreaking.register();
var enchdesc_curse_of_vanishing = VanillaFactory.createItem("enchdesc_curse_of_vanishing");
enchdesc_curse_of_vanishing.register();
var enchdesc_manabound = VanillaFactory.createItem("enchdesc_manabound");
enchdesc_manabound.register();
var enchdesc_headhunter = VanillaFactory.createItem("enchdesc_headhunter");
enchdesc_headhunter.register();
var enchdesc_aerial_affinity = VanillaFactory.createItem("enchdesc_aerial_affinity");    
enchdesc_aerial_affinity.register();    