scripts.PuzzleUtil.addPuzzleShapeless("ezmithminiteboii",<contenttweaker:ghoul_spirit>,
[<aoa3:primed_ghoulasm>,
makeVisCrystal(<aspect:mythus> * 1),
makeVisCrystal(<aspect:auram> * 1),
makeVisCrystal(<aspect:vitreus> * 1),
makeVisCrystal(<aspect:potentia> * 1)]);

mods.extendedcrafting.CombinationCrafting.addRecipe(<thaumadditions:mithminite_ingot>, 
300, 
<contenttweaker:ghoul_spirit>, 
[<thaumadditions:adaminite_ingot>, 
<thaumadditions:adaminite_ingot>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:enhanced_chaos_fragment>]);



mods.extendedcrafting.CombinationCrafting.addRecipe(<thaumadditions:mithminite_ingot>*5, 
300, 
<contenttweaker:crimson_ichor>, 
[<thaumadditions:adaminite_ingot>, 
<thaumadditions:adaminite_ingot>, 
<thaumadditions:adaminite_ingot>, 
<thaumadditions:adaminite_ingot>, 
<thaumadditions:adaminite_ingot>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:ghoul_spirit>, 
<contenttweaker:ghoul_spirit>, 
<contenttweaker:ghoul_spirit>, 
<contenttweaker:ghoul_spirit>, 
<contenttweaker:enhanced_chaos_shard>]);

mods.extendedcrafting.CombinationCrafting.addRecipe(<thaumadditions:mithminite_ingot>*10, 
300, 
<contenttweaker:ichorium_void_stone>, 
[<thaumadditions:adaminite_block>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:livermorium_sliver>,
<contenttweaker:ghoul_spirit>, 
<contenttweaker:ghoul_spirit>, 
<contenttweaker:ghoul_spirit>, 
<contenttweaker:ghoul_spirit>, 
<contenttweaker:ghoul_spirit>, 
<contenttweaker:ghoul_spirit>, 
<contenttweaker:ghoul_spirit>, 
<contenttweaker:ghoul_spirit>, 
<contenttweaker:crimson_ichor>,
<contenttweaker:crimson_ichor>,
<contenttweaker:enhanced_chaos_shard>,
<contenttweaker:enhanced_chaos_shard>]);

