import mods.modularmachinery.RecipeBuilder;
import scripts.enchantwrapper.EnchantUtil.EnchantMap;
import scripts.enchantwrapper.EnchantWrapper.SuperEnchantedItem;



mods.extendedcrafting.TableCrafting.addShaped(<contenttweaker:sacred_cinders_log>, 
[[<extratrees:misc:3>, <extratrees:misc:3>, null, <extratrees:misc:3>, <extratrees:misc:3>], 
[<extratrees:misc:3>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <extratrees:misc:3>], 
[null, <contenttweaker:chaos_wood>, <contenttweaker:energy_egg>, <contenttweaker:order_wood>, null], 
[<extratrees:misc:3>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <extratrees:misc:3>], 
[<extratrees:misc:3>, <extratrees:misc:3>, null, <extratrees:misc:3>, <extratrees:misc:3>]]);  

mods.extendedcrafting.TableCrafting.addShaped(<contenttweaker:sacred_cinders_log>*2, 
[[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})], 
[<extratrees:misc:3>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <extratrees:misc:3>], 
[null, <contenttweaker:chaos_wood>, <contenttweaker:energy_egg>, <contenttweaker:order_wood>, null], 
[<extratrees:misc:3>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <extratrees:misc:3>], 
[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <extratrees:misc:3>, null, <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})]]);  


mods.extendedcrafting.TableCrafting.addShaped(<contenttweaker:sacred_cinders_log>*4, 
[[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})], 
[<extratrees:misc:3>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <extratrees:misc:3>], 
[<careerbees:ingredients:1>.withTag({bark: {id: "aoa3:shyre_log", Count: 1, Damage: 0 as short}}), <contenttweaker:chaos_wood>, <contenttweaker:energy_egg>, <contenttweaker:order_wood>, <careerbees:ingredients:1>.withTag({bark: {id: "aoa3:shyre_log", Count: 1, Damage: 0 as short}})], 
[<extratrees:misc:3>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <extratrees:misc:3>], 
[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})]]);  

mods.extendedcrafting.TableCrafting.addShaped(<contenttweaker:sacred_cinders_log>*8, 
[[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "aoa3:shyre_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "aoa3:shyre_log", Count: 1, Damage: 0 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})], 
[<careerbees:ingredients:1>.withTag({bark: {id: "bewitchment:dragons_blood_wood", Count: 1, Damage: 0 as short}}), <twilightforest:cinder_log>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <careerbees:ingredients:1>.withTag({bark: {id: "thaumcraft:log_silverwood", Count: 1, Damage: 0 as short}})], 
[<extratrees:misc:3>, <contenttweaker:chaos_wood>, <contenttweaker:energy_egg>, <contenttweaker:order_wood>, <extratrees:misc:3>], 
[<careerbees:ingredients:1>.withTag({bark: {id: "bewitchment:dragons_blood_wood", Count: 1, Damage: 0 as short}}), <twilightforest:cinder_log>, <twilightforest:cinder_log>, <twilightforest:cinder_log>, <careerbees:ingredients:1>.withTag({bark: {id: "thaumcraft:log_silverwood", Count: 1, Damage: 0 as short}})], 
[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})]]);  

mods.extendedcrafting.TableCrafting.addShaped(<contenttweaker:sacred_cinders_log>*16, 
[[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "aoa3:shyre_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "aoa3:shyre_log", Count: 1, Damage: 0 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})], 
[<careerbees:ingredients:1>.withTag({bark: {id: "bewitchment:dragons_blood_wood", Count: 1, Damage: 0 as short}}), <twilightforest:cinder_log>, <careerbees:ingredients:1>.withTag({bark: {id: "aether_legacy:aether_log", Count: 1, Damage: 0 as short}}), <twilightforest:cinder_log>, <careerbees:ingredients:1>.withTag({bark: {id: "thaumcraft:log_silverwood", Count: 1, Damage: 0 as short}})], 
[<extratrees:misc:3>, <contenttweaker:chaos_wood>, <contenttweaker:energy_egg>, <contenttweaker:order_wood>, <extratrees:misc:3>], 
[<careerbees:ingredients:1>.withTag({bark: {id: "bewitchment:dragons_blood_wood", Count: 1, Damage: 0 as short}}), <twilightforest:cinder_log>, <careerbees:ingredients:1>.withTag({bark: {id: "aether_legacy:aether_log", Count: 1, Damage: 0 as short}}), <twilightforest:cinder_log>, <careerbees:ingredients:1>.withTag({bark: {id: "thaumcraft:log_silverwood", Count: 1, Damage: 0 as short}})], 
[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})]]);  

mods.extendedcrafting.TableCrafting.addShaped(<contenttweaker:sacred_cinders_log>*64, 
[[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "aoa3:shyre_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "aoa3:shyre_log", Count: 1, Damage: 0 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})], 
[<careerbees:ingredients:1>.withTag({bark: {id: "bewitchment:dragons_blood_wood", Count: 1, Damage: 0 as short}}), <contenttweaker:yggdrasil_wood>, <careerbees:ingredients:1>.withTag({bark: {id: "aether_legacy:aether_log", Count: 1, Damage: 0 as short}}), <contenttweaker:yggdrasil_wood>, <careerbees:ingredients:1>.withTag({bark: {id: "thaumcraft:log_silverwood", Count: 1, Damage: 0 as short}})], 
[<extratrees:misc:3>, <contenttweaker:chaos_wood>, <contenttweaker:energy_egg>, <contenttweaker:order_wood>, <extratrees:misc:3>], 
[<careerbees:ingredients:1>.withTag({bark: {id: "bewitchment:dragons_blood_wood", Count: 1, Damage: 0 as short}}), <contenttweaker:yggdrasil_wood>, <careerbees:ingredients:1>.withTag({bark: {id: "aether_legacy:aether_log", Count: 1, Damage: 0 as short}}), <contenttweaker:yggdrasil_wood>, <careerbees:ingredients:1>.withTag({bark: {id: "thaumcraft:log_silverwood", Count: 1, Damage: 0 as short}})], 
[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})]]);  

mods.extendedcrafting.TableCrafting.addShaped(<contenttweaker:sacred_cinders_catalyst>*64, 
[[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "aoa3:shyre_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "aoa3:shyre_log", Count: 1, Damage: 0 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})], 
[<careerbees:ingredients:1>.withTag({bark: {id: "bewitchment:dragons_blood_wood", Count: 1, Damage: 0 as short}}), <contenttweaker:yggdrasil_wood>, <careerbees:ingredients:1>.withTag({bark: {id: "aether_legacy:aether_log", Count: 1, Damage: 0 as short}}), <contenttweaker:yggdrasil_wood>, <careerbees:ingredients:1>.withTag({bark: {id: "thaumcraft:log_silverwood", Count: 1, Damage: 0 as short}})], 
[<extratrees:misc:3>, <contenttweaker:chaos_wood>, <contenttweaker:delicate_flower>, <contenttweaker:order_wood>, <extratrees:misc:3>], 
[<careerbees:ingredients:1>.withTag({bark: {id: "bewitchment:dragons_blood_wood", Count: 1, Damage: 0 as short}}), <contenttweaker:yggdrasil_wood>, <careerbees:ingredients:1>.withTag({bark: {id: "aether_legacy:aether_log", Count: 1, Damage: 0 as short}}), <contenttweaker:yggdrasil_wood>, <careerbees:ingredients:1>.withTag({bark: {id: "thaumcraft:log_silverwood", Count: 1, Damage: 0 as short}})], 
[<careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <extratrees:misc:3>, <careerbees:ingredients:1>.withTag({bark: {id: "divinerpg:mortum_log", Count: 1, Damage: 0 as short}}), <careerbees:ingredients:1>.withTag({bark: {id: "twilightforest:magic_log", Count: 1, Damage: 2 as short}})]]);  

recipes.addShaped(<contenttweaker:sacred_cinders_log>*8,
[[<contenttweaker:quasar_charged_dust>, <contenttweaker:sacred_cinders_catalyst>, <contenttweaker:quasar_charged_dust>],
[<contenttweaker:sacred_cinders_catalyst>, <contenttweaker:energy_egg>, <contenttweaker:sacred_cinders_catalyst>],
[<contenttweaker:quasar_charged_dust>, <contenttweaker:sacred_cinders_catalyst>, <contenttweaker:quasar_charged_dust>]]);


mods.extendedcrafting.CompressionCrafting.addRecipe(<contenttweaker:sacred_cinders_seed>, <contenttweaker:sacred_cinders_log>, 1000, <extendedcrafting:material:11>, 100);

furnace.addRecipe(<contenttweaker:everburning_seed>, <contenttweaker:sacred_cinders_seed>);

recipes.addShaped(<contenttweaker:everburner>,
[[<nuclearcraft:heat_exchanger_tube_thermoconducting>, <contenttweaker:infinity_furnace_bricks>, <nuclearcraft:heat_exchanger_tube_thermoconducting>],
[<contenttweaker:infinity_furnace_bricks>, <contenttweaker:everburning_seed>, <contenttweaker:infinity_furnace_bricks>],
[<nuclearcraft:heat_exchanger_tube_thermoconducting>, <contenttweaker:infinity_furnace_bricks>, <nuclearcraft:heat_exchanger_tube_thermoconducting>]]);




mods.extendedcrafting.TableCrafting.addShaped(<contenttweaker:sacred_cinders_apiary>, 

[[<contenttweaker:sacred_cinders_fruit>, <contenttweaker:sacred_cinders_fruit>, <careerbees:eternalframe>, 
null, <forestry:alveary.hygro>, null, 
<careerbees:eternalframe>, <contenttweaker:sacred_cinders_fruit>, <contenttweaker:sacred_cinders_fruit>], 

[<contenttweaker:sacred_cinders_fruit>, <careerbees:alveary_frame>, null, 
<contenttweaker:shyre_crystal>, <forestry:alveary.swarmer>, <contenttweaker:shyre_crystal>, 
null, <careerbees:alveary_frame>, <contenttweaker:sacred_cinders_fruit>], 

[<careerbees:eternalframe>, null, <forestry:alveary.sieve>, 
null, <extrabees:alveary:3>, null, 
<forestry:alveary.sieve>, null, <careerbees:eternalframe>], 

[null, <contenttweaker:shyre_crystal>, null, 
<forestry:alveary.stabiliser>, <forestry:alveary.plain>, <forestry:alveary.stabiliser>, 
null, <contenttweaker:shyre_crystal>, null], 

[<forestry:alveary.heater>, <forestry:alveary.fan>, <extrabees:alveary:6>, 
<forestry:alveary.plain>, <forestry:alveary.plain>, <forestry:alveary.plain>, 
<extrabees:alveary:6>, <forestry:alveary.fan>, <forestry:alveary.heater>], 

[null, <contenttweaker:shyre_crystal>, null, 
<forestry:alveary.stabiliser>, <forestry:alveary.plain>, <forestry:alveary.stabiliser>, 
null, <contenttweaker:shyre_crystal>, null], 

[<careerbees:eternalframe>, null, <forestry:alveary.sieve>, 
null, <extrabees:alveary:3>, null, 
<forestry:alveary.sieve>, null, <careerbees:eternalframe>], 

[<contenttweaker:sacred_cinders_fruit>, <careerbees:alveary_frame>, null, 
<contenttweaker:shyre_crystal>, <forestry:alveary.swarmer>, <contenttweaker:shyre_crystal>, 
null, <careerbees:alveary_frame>, <contenttweaker:sacred_cinders_fruit>], 

[<contenttweaker:sacred_cinders_fruit>, <contenttweaker:sacred_cinders_fruit>, <careerbees:eternalframe>, 
null, <forestry:alveary.hygro>, null, 
<careerbees:eternalframe>, <contenttweaker:sacred_cinders_fruit>, <contenttweaker:sacred_cinders_fruit>]]);  



val superbee_desolate = RecipeBuilder.newBuilder("superbee_desolate","sacred_cinders_apiary",10);	superbee_desolate.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.desolate", UID0: "extrabees.species.desolate"}]}}));	superbee_desolate.setChance(0.0);	superbee_desolate.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_desolate.addItemOutput(<extrabees:honey_comb:0>*64);	superbee_desolate.addItemOutput(<forestry:bee_combs:0>*64);	superbee_desolate.build();
val superbee_rotten = RecipeBuilder.newBuilder("superbee_rotten","sacred_cinders_apiary",10);	superbee_rotten.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.rotten", UID0: "extrabees.species.rotten"}]}}));	superbee_rotten.setChance(0.0);	superbee_rotten.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_rotten.addItemOutput(<extrabees:honey_comb:1>*64);	superbee_rotten.addItemOutput(<forestry:bee_combs:0>*64);	superbee_rotten.build();
val superbee_skeletal = RecipeBuilder.newBuilder("superbee_skeletal","sacred_cinders_apiary",10);	superbee_skeletal.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.bone", UID0: "extrabees.species.bone"}]}}));	superbee_skeletal.setChance(0.0);	superbee_skeletal.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_skeletal.addItemOutput(<extrabees:honey_comb:2>*64);	superbee_skeletal.addItemOutput(<forestry:bee_combs:0>*64);	superbee_skeletal.build();
val superbee_refined = RecipeBuilder.newBuilder("superbee_refined","sacred_cinders_apiary",10);	superbee_refined.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.fuel", UID0: "extrabees.species.fuel"}]}}));	superbee_refined.setChance(0.0);	superbee_refined.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_refined.addItemOutput(<extrabees:honey_comb:3>*64);	superbee_refined.addItemOutput(<forestry:bee_combs:0>*64);	superbee_refined.build();
val superbee_tarry = RecipeBuilder.newBuilder("superbee_tarry","sacred_cinders_apiary",10);	superbee_tarry.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.creosote", UID0: "extrabees.species.creosote"}]}}));	superbee_tarry.setChance(0.0);	superbee_tarry.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_tarry.addItemOutput(<extrabees:honey_comb:4>*64);	superbee_tarry.addItemOutput(<forestry:bee_combs:0>*64);	superbee_tarry.build();
val superbee_water = RecipeBuilder.newBuilder("superbee_water","sacred_cinders_apiary",10);	superbee_water.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.water", UID0: "extrabees.species.water"}]}}));	superbee_water.setChance(0.0);	superbee_water.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_water.addItemOutput(<extrabees:honey_comb:6>*64);	superbee_water.addItemOutput(<forestry:bee_combs:14>*64);	superbee_water.build();
val superbee_fruity = RecipeBuilder.newBuilder("superbee_fruity","sacred_cinders_apiary",10);	superbee_fruity.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.fruit", UID0: "extrabees.species.fruit"}]}}));	superbee_fruity.setChance(0.0);	superbee_fruity.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_fruity.addItemOutput(<extrabees:honey_comb:8>*64);	superbee_fruity.addItemOutput(<forestry:bee_combs:0>*64);	superbee_fruity.build();
val superbee_farmed = RecipeBuilder.newBuilder("superbee_farmed","sacred_cinders_apiary",10);	superbee_farmed.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.farm", UID0: "extrabees.species.farm"}]}}));	superbee_farmed.setChance(0.0);	superbee_farmed.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_farmed.addItemOutput(<extrabees:honey_comb:9>*64);	superbee_farmed.addItemOutput(<forestry:bee_combs:14>*64);	superbee_farmed.build();
val superbee_river = RecipeBuilder.newBuilder("superbee_river","sacred_cinders_apiary",10);	superbee_river.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.river", UID0: "extrabees.species.river"}]}}));	superbee_river.setChance(0.0);	superbee_river.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_river.addItemOutput(<extrabees:honey_comb:6>*64);	superbee_river.addItemOutput(<extrabees:honey_comb:22>*64);	superbee_river.build();
val superbee_fermented = RecipeBuilder.newBuilder("superbee_fermented","sacred_cinders_apiary",10);	superbee_fermented.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.alcohol", UID0: "extrabees.species.alcohol"}]}}));	superbee_fermented.setChance(0.0);	superbee_fermented.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_fermented.addItemOutput(<forestry:bee_combs:14>*64);	superbee_fermented.addItemOutput(<extrabees:honey_comb:10>*64);	superbee_fermented.build();
val superbee_rocky = RecipeBuilder.newBuilder("superbee_rocky","sacred_cinders_apiary",10);	superbee_rocky.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.rock", UID0: "extrabees.species.rock"}]}}));	superbee_rocky.setChance(0.0);	superbee_rocky.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_rocky.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_rocky.addItemOutput(<forestry:bee_combs:0>*64);	superbee_rocky.build();
val superbee_energetic = RecipeBuilder.newBuilder("superbee_energetic","sacred_cinders_apiary",10);	superbee_energetic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.energetic", UID0: "extrabees.species.energetic"}]}}));	superbee_energetic.setChance(0.0);	superbee_energetic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_energetic.addItemOutput(<extrabees:honey_comb:12>*64);	superbee_energetic.addItemOutput(<forestry:bee_combs:0>*64);	superbee_energetic.build();
val superbee_ecstatic = RecipeBuilder.newBuilder("superbee_ecstatic","sacred_cinders_apiary",10);	superbee_ecstatic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.ecstatic", UID0: "extrabees.species.ecstatic"}]}}));	superbee_ecstatic.setChance(0.0);	superbee_ecstatic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_ecstatic.addItemOutput(<extrabees:honey_comb:12>*64);	superbee_ecstatic.addItemOutput(<extrabees:honey_comb:14>*64);	superbee_ecstatic.build();
val superbee_rusty = RecipeBuilder.newBuilder("superbee_rusty","sacred_cinders_apiary",10);	superbee_rusty.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.iron", UID0: "extrabees.species.iron"}]}}));	superbee_rusty.setChance(0.0);	superbee_rusty.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_rusty.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_rusty.addItemOutput(<extrabees:honey_comb:15>*64);	superbee_rusty.build();
val superbee_glittering = RecipeBuilder.newBuilder("superbee_glittering","sacred_cinders_apiary",10);	superbee_glittering.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.gold", UID0: "extrabees.species.gold"}]}}));	superbee_glittering.setChance(0.0);	superbee_glittering.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_glittering.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_glittering.addItemOutput(<extrabees:honey_comb:16>*64);	superbee_glittering.build();
val superbee_corroded = RecipeBuilder.newBuilder("superbee_corroded","sacred_cinders_apiary",10);	superbee_corroded.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.copper", UID0: "extrabees.species.copper"}]}}));	superbee_corroded.setChance(0.0);	superbee_corroded.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_corroded.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_corroded.addItemOutput(<extrabees:honey_comb:17>*64);	superbee_corroded.build();
val superbee_tarnished = RecipeBuilder.newBuilder("superbee_tarnished","sacred_cinders_apiary",10);	superbee_tarnished.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.tin", UID0: "extrabees.species.tin"}]}}));	superbee_tarnished.setChance(0.0);	superbee_tarnished.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_tarnished.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_tarnished.addItemOutput(<extrabees:honey_comb:18>*64);	superbee_tarnished.build();
val superbee_shining = RecipeBuilder.newBuilder("superbee_shining","sacred_cinders_apiary",10);	superbee_shining.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.silver", UID0: "extrabees.species.silver"}]}}));	superbee_shining.setChance(0.0);	superbee_shining.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_shining.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_shining.addItemOutput(<extrabees:honey_comb:19>*64);	superbee_shining.build();
val superbee_radioactive = RecipeBuilder.newBuilder("superbee_radioactive","sacred_cinders_apiary",10);	superbee_radioactive.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.radioactive", UID0: "extrabees.species.radioactive"}]}}));	superbee_radioactive.setChance(0.0);	superbee_radioactive.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_radioactive.addItemOutput(<extrabees:honey_comb:0>*64);	superbee_radioactive.addItemOutput(<extrabees:honey_comb:21>*64);	superbee_radioactive.build();
val superbee_relic = RecipeBuilder.newBuilder("superbee_relic","sacred_cinders_apiary",10);	superbee_relic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.relic", UID0: "extrabees.species.relic"}]}}));	superbee_relic.setChance(0.0);	superbee_relic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_relic.addItemOutput(<extrabees:honey_comb:23>*64);	superbee_relic.addItemOutput(<forestry:bee_combs:0>*64);	superbee_relic.build();
val superbee_fungal = RecipeBuilder.newBuilder("superbee_fungal","sacred_cinders_apiary",10);	superbee_fungal.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.fungal", UID0: "extrabees.species.fungal"}]}}));	superbee_fungal.setChance(0.0);	superbee_fungal.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_fungal.addItemOutput(<extrabees:honey_comb:24>*64);	superbee_fungal.addItemOutput(<forestry:bee_combs:15>*64);	superbee_fungal.build();
val superbee_elastic = RecipeBuilder.newBuilder("superbee_elastic","sacred_cinders_apiary",10);	superbee_elastic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.latex", UID0: "extrabees.species.latex"}]}}));	superbee_elastic.setChance(0.0);	superbee_elastic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_elastic.addItemOutput(<extrabees:honey_comb:26>*64);	superbee_elastic.addItemOutput(<forestry:bee_combs:0>*64);	superbee_elastic.build();
val superbee_acidic = RecipeBuilder.newBuilder("superbee_acidic","sacred_cinders_apiary",10);	superbee_acidic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.acidic", UID0: "extrabees.species.acidic"}]}}));	superbee_acidic.setChance(0.0);	superbee_acidic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_acidic.addItemOutput(<extrabees:honey_comb:27>*64);	superbee_acidic.addItemOutput(<forestry:bee_combs:6>*64);	superbee_acidic.build();
val superbee_virulent = RecipeBuilder.newBuilder("superbee_virulent","sacred_cinders_apiary",10);	superbee_virulent.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.virulent", UID0: "extrabees.species.virulent"}]}}));	superbee_virulent.setChance(0.0);	superbee_virulent.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_virulent.addItemOutput(<extrabees:honey_comb:28>*64);	superbee_virulent.addItemOutput(<forestry:bee_combs:6>*64);	superbee_virulent.build();
val superbee_sticky = RecipeBuilder.newBuilder("superbee_sticky","sacred_cinders_apiary",10);	superbee_sticky.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.sticky", UID0: "extrabees.species.sticky"}]}}));	superbee_sticky.setChance(0.0);	superbee_sticky.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_sticky.addItemOutput(<extrabees:honey_comb:29>*64);	superbee_sticky.addItemOutput(<forestry:bee_combs:6>*64);	superbee_sticky.build();
val superbee_volcanic = RecipeBuilder.newBuilder("superbee_volcanic","sacred_cinders_apiary",10);	superbee_volcanic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.volcanic", UID0: "extrabees.species.volcanic"}]}}));	superbee_volcanic.setChance(0.0);	superbee_volcanic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_volcanic.addItemOutput(<extrabees:honey_comb:30>*64);	superbee_volcanic.addItemOutput(<forestry:bee_combs:2>*64);	superbee_volcanic.build();
val superbee_glacial = RecipeBuilder.newBuilder("superbee_glacial","sacred_cinders_apiary",10);	superbee_glacial.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.freezing", UID0: "extrabees.species.freezing"}]}}));	superbee_glacial.setChance(0.0);	superbee_glacial.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_glacial.addItemOutput(<extrabees:honey_comb:32>*64);	superbee_glacial.addItemOutput(<forestry:bee_combs:4>*64);	superbee_glacial.build();
val superbee_abyssal = RecipeBuilder.newBuilder("superbee_abyssal","sacred_cinders_apiary",10);	superbee_abyssal.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.abyss", UID0: "extrabees.species.abyss"}]}}));	superbee_abyssal.setChance(0.0);	superbee_abyssal.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_abyssal.addItemOutput(<extrabees:honey_comb:36>*64);	superbee_abyssal.addItemOutput(<forestry:bee_combs:0>*64);	superbee_abyssal.build();
val superbee_leaden = RecipeBuilder.newBuilder("superbee_leaden","sacred_cinders_apiary",10);	superbee_leaden.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.lead", UID0: "extrabees.species.lead"}]}}));	superbee_leaden.setChance(0.0);	superbee_leaden.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_leaden.addItemOutput(<extrabees:honey_comb:37>*64);	superbee_leaden.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_leaden.build();
val superbee_galvanized = RecipeBuilder.newBuilder("superbee_galvanized","sacred_cinders_apiary",10);	superbee_galvanized.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.zinc", UID0: "extrabees.species.zinc"}]}}));	superbee_galvanized.setChance(0.0);	superbee_galvanized.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_galvanized.addItemOutput(<extrabees:honey_comb:40>*64);	superbee_galvanized.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_galvanized.build();
val superbee_impregnable = RecipeBuilder.newBuilder("superbee_impregnable","sacred_cinders_apiary",10);	superbee_impregnable.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.titanium", UID0: "extrabees.species.titanium"}]}}));	superbee_impregnable.setChance(0.0);	superbee_impregnable.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_impregnable.addItemOutput(<extrabees:honey_comb:41>*64);	superbee_impregnable.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_impregnable.build();
val superbee_invincible = RecipeBuilder.newBuilder("superbee_invincible","sacred_cinders_apiary",10);	superbee_invincible.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.tungstate", UID0: "extrabees.species.tungstate"}]}}));	superbee_invincible.setChance(0.0);	superbee_invincible.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_invincible.addItemOutput(<extrabees:honey_comb:42>*64);	superbee_invincible.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_invincible.build();
val superbee_valuable = RecipeBuilder.newBuilder("superbee_valuable","sacred_cinders_apiary",10);	superbee_valuable.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.platinum", UID0: "extrabees.species.platinum"}]}}));	superbee_valuable.setChance(0.0);	superbee_valuable.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_valuable.addItemOutput(<extrabees:honey_comb:45>*64);	superbee_valuable.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_valuable.build();
val superbee_lapis = RecipeBuilder.newBuilder("superbee_lapis","sacred_cinders_apiary",10);	superbee_lapis.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.lapis", UID0: "extrabees.species.lapis"}]}}));	superbee_lapis.setChance(0.0);	superbee_lapis.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_lapis.addItemOutput(<extrabees:honey_comb:46>*64);	superbee_lapis.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_lapis.build();
val superbee_sodalite = RecipeBuilder.newBuilder("superbee_sodalite","sacred_cinders_apiary",10);	superbee_sodalite.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.sodalite", UID0: "extrabees.species.sodalite"}]}}));	superbee_sodalite.setChance(0.0);	superbee_sodalite.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_sodalite.addItemOutput(<extrabees:honey_comb:47>*64);	superbee_sodalite.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_sodalite.build();
val superbee_pyrite = RecipeBuilder.newBuilder("superbee_pyrite","sacred_cinders_apiary",10);	superbee_pyrite.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.pyrite", UID0: "extrabees.species.pyrite"}]}}));	superbee_pyrite.setChance(0.0);	superbee_pyrite.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_pyrite.addItemOutput(<extrabees:honey_comb:48>*64);	superbee_pyrite.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_pyrite.build();
val superbee_bauxite = RecipeBuilder.newBuilder("superbee_bauxite","sacred_cinders_apiary",10);	superbee_bauxite.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.bauxite", UID0: "extrabees.species.bauxite"}]}}));	superbee_bauxite.setChance(0.0);	superbee_bauxite.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_bauxite.addItemOutput(<extrabees:honey_comb:49>*64);	superbee_bauxite.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_bauxite.build();
val superbee_cinnabar = RecipeBuilder.newBuilder("superbee_cinnabar","sacred_cinders_apiary",10);	superbee_cinnabar.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.cinnabar", UID0: "extrabees.species.cinnabar"}]}}));	superbee_cinnabar.setChance(0.0);	superbee_cinnabar.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_cinnabar.addItemOutput(<extrabees:honey_comb:50>*64);	superbee_cinnabar.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_cinnabar.build();
val superbee_sphalerite = RecipeBuilder.newBuilder("superbee_sphalerite","sacred_cinders_apiary",10);	superbee_sphalerite.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.sphalerite", UID0: "extrabees.species.sphalerite"}]}}));	superbee_sphalerite.setChance(0.0);	superbee_sphalerite.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_sphalerite.addItemOutput(<extrabees:honey_comb:51>*64);	superbee_sphalerite.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_sphalerite.build();
val superbee_emerald = RecipeBuilder.newBuilder("superbee_emerald","sacred_cinders_apiary",10);	superbee_emerald.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.emerald", UID0: "extrabees.species.emerald"}]}}));	superbee_emerald.setChance(0.0);	superbee_emerald.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_emerald.addItemOutput(<extrabees:honey_comb:52>*64);	superbee_emerald.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_emerald.build();
val superbee_ruby = RecipeBuilder.newBuilder("superbee_ruby","sacred_cinders_apiary",10);	superbee_ruby.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.ruby", UID0: "extrabees.species.ruby"}]}}));	superbee_ruby.setChance(0.0);	superbee_ruby.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_ruby.addItemOutput(<extrabees:honey_comb:53>*64);	superbee_ruby.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_ruby.build();
val superbee_sapphire = RecipeBuilder.newBuilder("superbee_sapphire","sacred_cinders_apiary",10);	superbee_sapphire.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.sapphire", UID0: "extrabees.species.sapphire"}]}}));	superbee_sapphire.setChance(0.0);	superbee_sapphire.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_sapphire.addItemOutput(<extrabees:honey_comb:54>*64);	superbee_sapphire.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_sapphire.build();
val superbee_diamond = RecipeBuilder.newBuilder("superbee_diamond","sacred_cinders_apiary",10);	superbee_diamond.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.diamond", UID0: "extrabees.species.diamond"}]}}));	superbee_diamond.setChance(0.0);	superbee_diamond.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_diamond.addItemOutput(<extrabees:honey_comb:56>*64);	superbee_diamond.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_diamond.build();
val superbee_maroon = RecipeBuilder.newBuilder("superbee_maroon","sacred_cinders_apiary",10);	superbee_maroon.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.red", UID0: "extrabees.species.red"}]}}));	superbee_maroon.setChance(0.0);	superbee_maroon.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_maroon.addItemOutput(<extrabees:honey_comb:57>*64);	superbee_maroon.addItemOutput(<forestry:bee_combs:0>*64);	superbee_maroon.build();
val superbee_saffron = RecipeBuilder.newBuilder("superbee_saffron","sacred_cinders_apiary",10);	superbee_saffron.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.yellow", UID0: "extrabees.species.yellow"}]}}));	superbee_saffron.setChance(0.0);	superbee_saffron.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_saffron.addItemOutput(<extrabees:honey_comb:58>*64);	superbee_saffron.addItemOutput(<forestry:bee_combs:0>*64);	superbee_saffron.build();
val superbee_prussian = RecipeBuilder.newBuilder("superbee_prussian","sacred_cinders_apiary",10);	superbee_prussian.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.blue", UID0: "extrabees.species.blue"}]}}));	superbee_prussian.setChance(0.0);	superbee_prussian.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_prussian.addItemOutput(<extrabees:honey_comb:59>*64);	superbee_prussian.addItemOutput(<forestry:bee_combs:0>*64);	superbee_prussian.build();
val superbee_natural = RecipeBuilder.newBuilder("superbee_natural","sacred_cinders_apiary",10);	superbee_natural.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.green", UID0: "extrabees.species.green"}]}}));	superbee_natural.setChance(0.0);	superbee_natural.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_natural.addItemOutput(<extrabees:honey_comb:60>*64);	superbee_natural.addItemOutput(<forestry:bee_combs:0>*64);	superbee_natural.build();
val superbee_ebony = RecipeBuilder.newBuilder("superbee_ebony","sacred_cinders_apiary",10);	superbee_ebony.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.black", UID0: "extrabees.species.black"}]}}));	superbee_ebony.setChance(0.0);	superbee_ebony.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_ebony.addItemOutput(<extrabees:honey_comb:61>*64);	superbee_ebony.addItemOutput(<forestry:bee_combs:0>*64);	superbee_ebony.build();
val superbee_bleached = RecipeBuilder.newBuilder("superbee_bleached","sacred_cinders_apiary",10);	superbee_bleached.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.white", UID0: "extrabees.species.white"}]}}));	superbee_bleached.setChance(0.0);	superbee_bleached.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_bleached.addItemOutput(<extrabees:honey_comb:62>*64);	superbee_bleached.addItemOutput(<forestry:bee_combs:0>*64);	superbee_bleached.build();
val superbee_sepia = RecipeBuilder.newBuilder("superbee_sepia","sacred_cinders_apiary",10);	superbee_sepia.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.brown", UID0: "extrabees.species.brown"}]}}));	superbee_sepia.setChance(0.0);	superbee_sepia.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_sepia.addItemOutput(<extrabees:honey_comb:63>*64);	superbee_sepia.addItemOutput(<forestry:bee_combs:0>*64);	superbee_sepia.build();
val superbee_amber = RecipeBuilder.newBuilder("superbee_amber","sacred_cinders_apiary",10);	superbee_amber.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.orange", UID0: "extrabees.species.orange"}]}}));	superbee_amber.setChance(0.0);	superbee_amber.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_amber.addItemOutput(<extrabees:honey_comb:64>*64);	superbee_amber.addItemOutput(<forestry:bee_combs:0>*64);	superbee_amber.build();
val superbee_turquoise = RecipeBuilder.newBuilder("superbee_turquoise","sacred_cinders_apiary",10);	superbee_turquoise.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.cyan", UID0: "extrabees.species.cyan"}]}}));	superbee_turquoise.setChance(0.0);	superbee_turquoise.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_turquoise.addItemOutput(<extrabees:honey_comb:65>*64);	superbee_turquoise.addItemOutput(<forestry:bee_combs:0>*64);	superbee_turquoise.build();
val superbee_indigo = RecipeBuilder.newBuilder("superbee_indigo","sacred_cinders_apiary",10);	superbee_indigo.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.purple", UID0: "extrabees.species.purple"}]}}));	superbee_indigo.setChance(0.0);	superbee_indigo.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_indigo.addItemOutput(<extrabees:honey_comb:66>*64);	superbee_indigo.addItemOutput(<forestry:bee_combs:0>*64);	superbee_indigo.build();
val superbee_slate = RecipeBuilder.newBuilder("superbee_slate","sacred_cinders_apiary",10);	superbee_slate.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.gray", UID0: "extrabees.species.gray"}]}}));	superbee_slate.setChance(0.0);	superbee_slate.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_slate.addItemOutput(<extrabees:honey_comb:67>*64);	superbee_slate.addItemOutput(<forestry:bee_combs:0>*64);	superbee_slate.build();
val superbee_azure = RecipeBuilder.newBuilder("superbee_azure","sacred_cinders_apiary",10);	superbee_azure.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.lightblue", UID0: "extrabees.species.lightblue"}]}}));	superbee_azure.setChance(0.0);	superbee_azure.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_azure.addItemOutput(<extrabees:honey_comb:68>*64);	superbee_azure.addItemOutput(<forestry:bee_combs:0>*64);	superbee_azure.build();
val superbee_lavender = RecipeBuilder.newBuilder("superbee_lavender","sacred_cinders_apiary",10);	superbee_lavender.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.pink", UID0: "extrabees.species.pink"}]}}));	superbee_lavender.setChance(0.0);	superbee_lavender.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_lavender.addItemOutput(<extrabees:honey_comb:69>*64);	superbee_lavender.addItemOutput(<forestry:bee_combs:0>*64);	superbee_lavender.build();
val superbee_lime = RecipeBuilder.newBuilder("superbee_lime","sacred_cinders_apiary",10);	superbee_lime.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.limegreen", UID0: "extrabees.species.limegreen"}]}}));	superbee_lime.setChance(0.0);	superbee_lime.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_lime.addItemOutput(<extrabees:honey_comb:70>*64);	superbee_lime.addItemOutput(<forestry:bee_combs:0>*64);	superbee_lime.build();
val superbee_fuchsia = RecipeBuilder.newBuilder("superbee_fuchsia","sacred_cinders_apiary",10);	superbee_fuchsia.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.magenta", UID0: "extrabees.species.magenta"}]}}));	superbee_fuchsia.setChance(0.0);	superbee_fuchsia.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_fuchsia.addItemOutput(<extrabees:honey_comb:71>*64);	superbee_fuchsia.addItemOutput(<forestry:bee_combs:0>*64);	superbee_fuchsia.build();
val superbee_ashen = RecipeBuilder.newBuilder("superbee_ashen","sacred_cinders_apiary",10);	superbee_ashen.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.lightgray", UID0: "extrabees.species.lightgray"}]}}));	superbee_ashen.setChance(0.0);	superbee_ashen.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_ashen.addItemOutput(<extrabees:honey_comb:72>*64);	superbee_ashen.addItemOutput(<forestry:bee_combs:0>*64);	superbee_ashen.build();
val superbee_lustered = RecipeBuilder.newBuilder("superbee_lustered","sacred_cinders_apiary",10);	superbee_lustered.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.nickel", UID0: "extrabees.species.nickel"}]}}));	superbee_lustered.setChance(0.0);	superbee_lustered.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_lustered.addItemOutput(<extrabees:honey_comb:73>*64);	superbee_lustered.addItemOutput(<extrabees:honey_comb:11>*64);	superbee_lustered.build();
val superbee_glowering = RecipeBuilder.newBuilder("superbee_glowering","sacred_cinders_apiary",10);	superbee_glowering.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.glowstone", UID0: "extrabees.species.glowstone"}]}}));	superbee_glowering.setChance(0.0);	superbee_glowering.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_glowering.addItemOutput(<extrabees:honey_comb:75>*64);	superbee_glowering.addItemOutput(<forestry:bee_combs:0>*64);	superbee_glowering.build();
val superbee_hazardous = RecipeBuilder.newBuilder("superbee_hazardous","sacred_cinders_apiary",10);	superbee_hazardous.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.hazardous", UID0: "extrabees.species.hazardous"}]}}));	superbee_hazardous.setChance(0.0);	superbee_hazardous.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_hazardous.addItemOutput(<extrabees:honey_comb:76>*64);	superbee_hazardous.addItemOutput(<forestry:bee_combs:0>*64);	superbee_hazardous.build();
val superbee_decomposing = RecipeBuilder.newBuilder("superbee_decomposing","sacred_cinders_apiary",10);	superbee_decomposing.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.decomposing", UID0: "extrabees.species.decomposing"}]}}));	superbee_decomposing.setChance(0.0);	superbee_decomposing.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_decomposing.addItemOutput(<extrabees:honey_comb:79>*64);	superbee_decomposing.addItemOutput(<extrabees:honey_comb:0>*64);	superbee_decomposing.build();
val superbee_quantum = RecipeBuilder.newBuilder("superbee_quantum","sacred_cinders_apiary",10);	superbee_quantum.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.quantum", UID0: "extrabees.species.quantum"}]}}));	superbee_quantum.setChance(0.0);	superbee_quantum.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_quantum.addItemOutput(<extrabees:honey_comb:81>*64);	superbee_quantum.addItemOutput(<extrabees:honey_comb:82>*64);	superbee_quantum.build();
val superbee_spatial = RecipeBuilder.newBuilder("superbee_spatial","sacred_cinders_apiary",10);	superbee_spatial.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.spatial", UID0: "extrabees.species.spatial"}]}}));	superbee_spatial.setChance(0.0);	superbee_spatial.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_spatial.addItemOutput(<extrabees:honey_comb:81>*64);	superbee_spatial.addItemOutput(<forestry:bee_combs:16>*64);	superbee_spatial.build();
val superbee_yellorium = RecipeBuilder.newBuilder("superbee_yellorium","sacred_cinders_apiary",10);	superbee_yellorium.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.yellorium", UID0: "extrabees.species.yellorium"}]}}));	superbee_yellorium.setChance(0.0);	superbee_yellorium.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_yellorium.addItemOutput(<extrabees:honey_comb:83>*64);	superbee_yellorium.addItemOutput(<extrabees:honey_comb:0>*64);	superbee_yellorium.build();
val superbee_cyanite = RecipeBuilder.newBuilder("superbee_cyanite","sacred_cinders_apiary",10);	superbee_cyanite.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.cyanite", UID0: "extrabees.species.cyanite"}]}}));	superbee_cyanite.setChance(0.0);	superbee_cyanite.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_cyanite.addItemOutput(<extrabees:honey_comb:84>*64);	superbee_cyanite.addItemOutput(<extrabees:honey_comb:0>*64);	superbee_cyanite.build();
val superbee_blutonium = RecipeBuilder.newBuilder("superbee_blutonium","sacred_cinders_apiary",10);	superbee_blutonium.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.blutonium", UID0: "extrabees.species.blutonium"}]}}));	superbee_blutonium.setChance(0.0);	superbee_blutonium.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_blutonium.addItemOutput(<extrabees:honey_comb:85>*64);	superbee_blutonium.addItemOutput(<extrabees:honey_comb:0>*64);	superbee_blutonium.build();
val superbee_forest = RecipeBuilder.newBuilder("superbee_forest","sacred_cinders_apiary",10);	superbee_forest.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesForest", UID0: "forestry.speciesForest"}]}}));	superbee_forest.setChance(0.0);	superbee_forest.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_forest.addItemOutput(<forestry:bee_combs:0>*64);	superbee_forest.addItemOutput(<forestry:bee_combs:0>*64);	superbee_forest.build();
val superbee_meadows = RecipeBuilder.newBuilder("superbee_meadows","sacred_cinders_apiary",10);	superbee_meadows.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesMeadows", UID0: "forestry.speciesMeadows"}]}}));	superbee_meadows.setChance(0.0);	superbee_meadows.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_meadows.addItemOutput(<forestry:bee_combs:0>*64);	superbee_meadows.addItemOutput(<forestry:bee_combs:0>*64);	superbee_meadows.build();
val superbee_demonic = RecipeBuilder.newBuilder("superbee_demonic","sacred_cinders_apiary",10);	superbee_demonic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesDemonic", UID0: "forestry.speciesDemonic"}]}}));	superbee_demonic.setChance(0.0);	superbee_demonic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_demonic.addItemOutput(<forestry:bee_combs:2>*64);	superbee_demonic.addItemOutput(<forestry:bee_combs:2>*64);	superbee_demonic.build();
val superbee_industrious = RecipeBuilder.newBuilder("superbee_industrious","sacred_cinders_apiary",10);	superbee_industrious.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesIndustrious", UID0: "forestry.speciesIndustrious"}]}}));	superbee_industrious.setChance(0.0);	superbee_industrious.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_industrious.addItemOutput(<forestry:bee_combs:3>*64);	superbee_industrious.addItemOutput(<forestry:pollen:0>*64);	superbee_industrious.build();
val superbee_absolute = RecipeBuilder.newBuilder("superbee_absolute","sacred_cinders_apiary",10);	superbee_absolute.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.freezing", UID0: "extrabees.species.freezing"}]}}));	superbee_absolute.setChance(0.0);	superbee_absolute.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_absolute.addItemOutput(<forestry:bee_combs:4>*64);	superbee_absolute.addItemOutput(<extrabees:honey_comb:32>*64);	superbee_absolute.build();
val superbee_imperial = RecipeBuilder.newBuilder("superbee_imperial","sacred_cinders_apiary",10);	superbee_imperial.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesImperial", UID0: "forestry.speciesImperial"}]}}));	superbee_imperial.setChance(0.0);	superbee_imperial.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_imperial.addItemOutput(<forestry:bee_combs:5>*64);	superbee_imperial.addItemOutput(<forestry:royal_jelly>*64);	superbee_imperial.build();
val superbee_edenic = RecipeBuilder.newBuilder("superbee_edenic","sacred_cinders_apiary",10);	superbee_edenic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesEdenic", UID0: "forestry.speciesEdenic"}]}}));	superbee_edenic.setChance(0.0);	superbee_edenic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_edenic.addItemOutput(<forestry:bee_combs:6>*64);	superbee_edenic.addItemOutput(<forestry:bee_combs:6>*64);	superbee_edenic.build();
val superbee_austere = RecipeBuilder.newBuilder("superbee_austere","sacred_cinders_apiary",10);	superbee_austere.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesAustere", UID0: "forestry.speciesAustere"}]}}));	superbee_austere.setChance(0.0);	superbee_austere.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_austere.addItemOutput(<forestry:bee_combs:7>*64);	superbee_austere.addItemOutput(<forestry:bee_combs:10>*64);	superbee_austere.build();
val superbee_boggy = RecipeBuilder.newBuilder("superbee_boggy","sacred_cinders_apiary",10);	superbee_boggy.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesBoggy", UID0: "forestry.speciesBoggy"}]}}));	superbee_boggy.setChance(0.0);	superbee_boggy.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_boggy.addItemOutput(<forestry:bee_combs:15>*64);	superbee_boggy.addItemOutput(<forestry:peat>*64);	superbee_boggy.build();
val superbee_hermitic = RecipeBuilder.newBuilder("superbee_hermitic","sacred_cinders_apiary",10);	superbee_hermitic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesHermitic", UID0: "forestry.speciesHermitic"}]}}));	superbee_hermitic.setChance(0.0);	superbee_hermitic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_hermitic.addItemOutput(<forestry:bee_combs:16>*64);	superbee_hermitic.addItemOutput(<forestry:bee_combs:16>*64);	superbee_hermitic.build();
val superbee_monastic = RecipeBuilder.newBuilder("superbee_monastic","sacred_cinders_apiary",10);	superbee_monastic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesMonastic", UID0: "forestry.speciesMonastic"}]}}));	superbee_monastic.setChance(0.0);	superbee_monastic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_monastic.addItemOutput(<forestry:bee_combs:16>*64);	superbee_monastic.addItemOutput(<forestry:bee_combs:14>*64);	superbee_monastic.build();
val superbee_springwater = RecipeBuilder.newBuilder("superbee_springwater","sacred_cinders_apiary",10);	superbee_springwater.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Springwater", UID0: "gendustry.bee.Springwater"}]}}));	superbee_springwater.setChance(0.0);	superbee_springwater.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_springwater.addItemOutput(<gendustry:honey_comb:13331>*64);	superbee_springwater.addItemOutput(<forestry:bee_combs:0>*64);	superbee_springwater.build();
val superbee_meatball = RecipeBuilder.newBuilder("superbee_meatball","sacred_cinders_apiary",10);	superbee_meatball.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Meatball", UID0: "gendustry.bee.Meatball"}]}}));	superbee_meatball.setChance(0.0);	superbee_meatball.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_meatball.addItemOutput(<gendustry:honey_comb:13337>*64);	superbee_meatball.addItemOutput(<contenttweaker:meatball>*64);	superbee_meatball.build();
val superbee_trinity = RecipeBuilder.newBuilder("superbee_trinity","sacred_cinders_apiary",10);	superbee_trinity.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Trinity", UID0: "gendustry.bee.Trinity"}]}}));	superbee_trinity.setChance(0.0);	superbee_trinity.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_trinity.addItemOutput(<gendustry:honey_comb:13338>*64);	superbee_trinity.addItemOutput(<gendustry:honey_comb:13338>*64);	superbee_trinity.build();
val superbee_formic = RecipeBuilder.newBuilder("superbee_formic","sacred_cinders_apiary",10);	superbee_formic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Formic", UID0: "gendustry.bee.Formic"}]}}));	superbee_formic.setChance(0.0);	superbee_formic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_formic.addItemOutput(<gendustry:honey_comb:13340>*64);	superbee_formic.addItemOutput(<forestry:bee_combs:0>*64);	superbee_formic.build();
val superbee_gorgon = RecipeBuilder.newBuilder("superbee_gorgon","sacred_cinders_apiary",10);	superbee_gorgon.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Gorgon", UID0: "gendustry.bee.Gorgon"}]}}));	superbee_gorgon.setChance(0.0);	superbee_gorgon.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_gorgon.addItemOutput(<gendustry:honey_comb:13341>*64);	superbee_gorgon.addItemOutput(<forestry:bee_combs:0>*64);	superbee_gorgon.build();
val superbee_balanced = RecipeBuilder.newBuilder("superbee_balanced","sacred_cinders_apiary",10);	superbee_balanced.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Balanced", UID0: "gendustry.bee.Balanced"}]}}));	superbee_balanced.setChance(0.0);	superbee_balanced.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_balanced.addItemOutput(<gendustry:honey_comb:13349>*64);	superbee_balanced.addItemOutput(<minecraft:clay_ball>*64);	superbee_balanced.build();
val superbee_radiant = RecipeBuilder.newBuilder("superbee_radiant","sacred_cinders_apiary",10);	superbee_radiant.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Radiant", UID0: "gendustry.bee.Radiant"}]}}));	superbee_radiant.setChance(0.0);	superbee_radiant.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_radiant.addItemOutput(<gendustry:honey_comb:13369>*64);	superbee_radiant.addItemOutput(<gendustry:honey_comb:13369>*64);	superbee_radiant.build();
val superbee_shyreempire = RecipeBuilder.newBuilder("superbee_shyreempire","sacred_cinders_apiary",10);	superbee_shyreempire.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Shyre", UID0: "gendustry.bee.Shyre"}]}}));	superbee_shyreempire.setChance(0.0);	superbee_shyreempire.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_shyreempire.addItemOutput(<gendustry:honey_comb:13370>*64);	superbee_shyreempire.addItemOutput(<forestry:bee_combs:0>*64);	superbee_shyreempire.build();
val superbee_twilighthorde = RecipeBuilder.newBuilder("superbee_twilighthorde","sacred_cinders_apiary",10);	superbee_twilighthorde.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Twilight", UID0: "gendustry.bee.Twilight"}]}}));	superbee_twilighthorde.setChance(0.0);	superbee_twilighthorde.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_twilighthorde.addItemOutput(<gendustry:honey_comb:13371>*64);	superbee_twilighthorde.addItemOutput(<gendustry:honey_comb:13379>*64);	superbee_twilighthorde.build();
val superbee_uraniumrad = RecipeBuilder.newBuilder("superbee_uraniumrad","sacred_cinders_apiary",10);	superbee_uraniumrad.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Uranium", UID0: "gendustry.bee.Uranium"}]}}));	superbee_uraniumrad.setChance(0.0);	superbee_uraniumrad.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_uraniumrad.addItemOutput(<gendustry:honey_comb:14001>*64);	superbee_uraniumrad.addItemOutput(<gendustry:honey_comb:14001>*64);	superbee_uraniumrad.build();
val superbee_thoriumrad = RecipeBuilder.newBuilder("superbee_thoriumrad","sacred_cinders_apiary",10);	superbee_thoriumrad.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Thorium", UID0: "gendustry.bee.Thorium"}]}}));	superbee_thoriumrad.setChance(0.0);	superbee_thoriumrad.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_thoriumrad.addItemOutput(<gendustry:honey_comb:14002>*64);	superbee_thoriumrad.addItemOutput(<gendustry:honey_comb:14002>*64);	superbee_thoriumrad.build();
val superbee_oxygenrad = RecipeBuilder.newBuilder("superbee_oxygenrad","sacred_cinders_apiary",10);	superbee_oxygenrad.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Oxygen", UID0: "gendustry.bee.Oxygen"}]}}));	superbee_oxygenrad.setChance(0.0);	superbee_oxygenrad.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_oxygenrad.addItemOutput(<gendustry:honey_comb:14003>*64);	superbee_oxygenrad.addItemOutput(<forestry:bee_combs:0>*64);	superbee_oxygenrad.build();
val superbee_embee = RecipeBuilder.newBuilder("superbee_embee","sacred_cinders_apiary",10);	superbee_embee.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Alchemical", UID0: "gendustry.bee.Alchemical"}]}}));	superbee_embee.setChance(0.0);	superbee_embee.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_embee.addItemOutput(<gendustry:honey_comb:14004>*64);	superbee_embee.addItemOutput(<gendustry:honey_comb:14004>*64);	superbee_embee.build();
val superbee_sniper = RecipeBuilder.newBuilder("superbee_sniper","sacred_cinders_apiary",10);	superbee_sniper.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Sniper", UID0: "gendustry.bee.Sniper"}]}}));	superbee_sniper.setChance(0.0);	superbee_sniper.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_sniper.addItemOutput(<gendustry:honey_comb:14005>*64);	superbee_sniper.addItemOutput(<forestry:bee_combs:0>*64);	superbee_sniper.build();
val superbee_gunman = RecipeBuilder.newBuilder("superbee_gunman","sacred_cinders_apiary",10);	superbee_gunman.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Gunman", UID0: "gendustry.bee.Gunman"}]}}));	superbee_gunman.setChance(0.0);	superbee_gunman.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_gunman.addItemOutput(<gendustry:honey_comb:14006>*64);	superbee_gunman.addItemOutput(<forestry:bee_combs:0>*64);	superbee_gunman.build();
val superbee_artillery = RecipeBuilder.newBuilder("superbee_artillery","sacred_cinders_apiary",10);	superbee_artillery.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Artillery", UID0: "gendustry.bee.Artillery"}]}}));	superbee_artillery.setChance(0.0);	superbee_artillery.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_artillery.addItemOutput(<gendustry:honey_comb:14007>*64);	superbee_artillery.addItemOutput(<forestry:bee_combs:0>*64);	superbee_artillery.build();
val superbee_bomber = RecipeBuilder.newBuilder("superbee_bomber","sacred_cinders_apiary",10);	superbee_bomber.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Bomber", UID0: "gendustry.bee.Bomber"}]}}));	superbee_bomber.setChance(0.0);	superbee_bomber.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_bomber.addItemOutput(<gendustry:honey_comb:14008>*64);	superbee_bomber.addItemOutput(<forestry:bee_combs:0>*64);	superbee_bomber.build();
val superbee_gravity = RecipeBuilder.newBuilder("superbee_gravity","sacred_cinders_apiary",10);	superbee_gravity.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Gravity", UID0: "gendustry.bee.Gravity"}]}}));	superbee_gravity.setChance(0.0);	superbee_gravity.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_gravity.addItemOutput(<gendustry:honey_comb:14009>*64);	superbee_gravity.addItemOutput(<contenttweaker:dense_gravitite_ore>*64);	superbee_gravity.build();
val superbee_necronomibee = RecipeBuilder.newBuilder("superbee_necronomibee","sacred_cinders_apiary",10);	superbee_necronomibee.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Necronomibee", UID0: "gendustry.bee.Necronomibee"}]}}));	superbee_necronomibee.setChance(0.0);	superbee_necronomibee.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_necronomibee.addItemOutput(<gendustry:honey_comb:14010>*64);	superbee_necronomibee.addItemOutput(<gendustry:honey_comb:14010>*64);	superbee_necronomibee.build();
val superbee_agricultural = RecipeBuilder.newBuilder("superbee_agricultural","sacred_cinders_apiary",10);	superbee_agricultural.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Agricultural", UID0: "gendustry.bee.Agricultural"}]}}));	superbee_agricultural.setChance(0.0);	superbee_agricultural.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_agricultural.addItemOutput(<gendustry:honey_comb:14012>*64);	superbee_agricultural.addItemOutput(<gendustry:honey_comb:14012>*64);	superbee_agricultural.build();
val superbee_heraldry = RecipeBuilder.newBuilder("superbee_heraldry","sacred_cinders_apiary",10);	superbee_heraldry.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Heraldry", UID0: "gendustry.bee.Heraldry"}]}}));	superbee_heraldry.setChance(0.0);	superbee_heraldry.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_heraldry.addItemOutput(<gendustry:honey_comb:14013>*64);	superbee_heraldry.addItemOutput(<gendustry:honey_comb:14013>*64);	superbee_heraldry.build();
val superbee_helplessness = RecipeBuilder.newBuilder("superbee_helplessness","sacred_cinders_apiary",10);	superbee_helplessness.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Helplessness", UID0: "gendustry.bee.Helplessness"}]}}));	superbee_helplessness.setChance(0.0);	superbee_helplessness.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_helplessness.addItemOutput(<gendustry:honey_comb:14014>*64);	superbee_helplessness.addItemOutput(<forestry:bee_combs:0>*64);	superbee_helplessness.build();
val superbee_darkness = RecipeBuilder.newBuilder("superbee_darkness","sacred_cinders_apiary",10);	superbee_darkness.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Darkness", UID0: "gendustry.bee.Darkness"}]}}));	superbee_darkness.setChance(0.0);	superbee_darkness.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_darkness.addItemOutput(<gendustry:honey_comb:14015>*64);	superbee_darkness.addItemOutput(<forestry:bee_combs:0>*64);	superbee_darkness.build();
val superbee_fear = RecipeBuilder.newBuilder("superbee_fear","sacred_cinders_apiary",10);	superbee_fear.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Fear", UID0: "gendustry.bee.Fear"}]}}));	superbee_fear.setChance(0.0);	superbee_fear.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_fear.addItemOutput(<gendustry:honey_comb:14016>*64);	superbee_fear.addItemOutput(<forestry:bee_combs:0>*64);	superbee_fear.build();
val superbee_solitude = RecipeBuilder.newBuilder("superbee_solitude","sacred_cinders_apiary",10);	superbee_solitude.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Solitude", UID0: "gendustry.bee.Solitude"}]}}));	superbee_solitude.setChance(0.0);	superbee_solitude.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_solitude.addItemOutput(<gendustry:honey_comb:14017>*64);	superbee_solitude.addItemOutput(<forestry:bee_combs:0>*64);	superbee_solitude.build();
val superbee_deeplearner = RecipeBuilder.newBuilder("superbee_deeplearner","sacred_cinders_apiary",10);	superbee_deeplearner.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Deeplearner", UID0: "gendustry.bee.Deeplearner"}]}}));	superbee_deeplearner.setChance(0.0);	superbee_deeplearner.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_deeplearner.addItemOutput(<gendustry:honey_comb:14018>*64);	superbee_deeplearner.addItemOutput(<gendustry:honey_comb:14018>*64);	superbee_deeplearner.build();
val superbee_apothecary = RecipeBuilder.newBuilder("superbee_apothecary","sacred_cinders_apiary",10);	superbee_apothecary.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Apothecary", UID0: "gendustry.bee.Apothecary"}]}}));	superbee_apothecary.setChance(0.0);	superbee_apothecary.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_apothecary.addItemOutput(<gendustry:honey_comb:14019>*64);	superbee_apothecary.addItemOutput(<forestry:bee_combs:0>*64);	superbee_apothecary.build();
val superbee_soulsucking = RecipeBuilder.newBuilder("superbee_soulsucking","sacred_cinders_apiary",10);	superbee_soulsucking.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Soulsucking", UID0: "gendustry.bee.Soulsucking"}]}}));	superbee_soulsucking.setChance(0.0);	superbee_soulsucking.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_soulsucking.addItemOutput(<gendustry:honey_comb:14020>*64);	superbee_soulsucking.addItemOutput(<gendustry:honey_comb:14020>*64);	superbee_soulsucking.build();
val superbee_isekai = RecipeBuilder.newBuilder("superbee_isekai","sacred_cinders_apiary",10);	superbee_isekai.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Isekai", UID0: "gendustry.bee.Isekai"}]}}));	superbee_isekai.setChance(0.0);	superbee_isekai.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_isekai.addItemOutput(<gendustry:honey_comb:14021>*64);	superbee_isekai.addItemOutput(<gendustry:honey_comb:14021>*64);	superbee_isekai.build();
val superbee_warrior = RecipeBuilder.newBuilder("superbee_warrior","sacred_cinders_apiary",10);	superbee_warrior.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Warrior", UID0: "gendustry.bee.Warrior"}]}}));	superbee_warrior.setChance(0.0);	superbee_warrior.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_warrior.addItemOutput(<gendustry:honey_comb:14022>*64);	superbee_warrior.addItemOutput(<gendustry:honey_comb:14022>*64);	superbee_warrior.build();
val superbee_tinkerest = RecipeBuilder.newBuilder("superbee_tinkerest","sacred_cinders_apiary",10);	superbee_tinkerest.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Tinkerest", UID0: "gendustry.bee.Tinkerest"}]}}));	superbee_tinkerest.setChance(0.0);	superbee_tinkerest.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_tinkerest.addItemOutput(<gendustry:honey_comb:14023>*64);	superbee_tinkerest.addItemOutput(<gendustry:honey_comb:14023>*64);	superbee_tinkerest.build();
val superbee_mystical = RecipeBuilder.newBuilder("superbee_mystical","sacred_cinders_apiary",10);	superbee_mystical.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesMystical", UID0: "magicbees.speciesMystical"}]}}));	superbee_mystical.setChance(0.0);	superbee_mystical.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_mystical.addItemOutput(<magicbees:beecomb:0>*64);	superbee_mystical.addItemOutput(<magicbees:beecomb:0>*64);	superbee_mystical.build();
val superbee_unusual = RecipeBuilder.newBuilder("superbee_unusual","sacred_cinders_apiary",10);	superbee_unusual.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesUnusual", UID0: "magicbees.speciesUnusual"}]}}));	superbee_unusual.setChance(0.0);	superbee_unusual.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_unusual.addItemOutput(<magicbees:beecomb:0>*64);	superbee_unusual.addItemOutput(<magicbees:beecomb:0>*64);	superbee_unusual.build();
val superbee_botanic = RecipeBuilder.newBuilder("superbee_botanic","sacred_cinders_apiary",10);	superbee_botanic.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesBOTBotanic", UID0: "magicbees.speciesBOTBotanic"}]}}));	superbee_botanic.setChance(0.0);	superbee_botanic.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_botanic.addItemOutput(<magicbees:beecomb:0>*64);	superbee_botanic.addItemOutput(<magicbees:beecomb:4>*64);	superbee_botanic.build();
val superbee_blossom = RecipeBuilder.newBuilder("superbee_blossom","sacred_cinders_apiary",10);	superbee_blossom.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesBOTBlossom", UID0: "magicbees.speciesBOTBlossom"}]}}));	superbee_blossom.setChance(0.0);	superbee_blossom.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_blossom.addItemOutput(<magicbees:beecomb:0>*64);	superbee_blossom.addItemOutput(<magicbees:beecomb:4>*64);	superbee_blossom.build();
val superbee_floral = RecipeBuilder.newBuilder("superbee_floral","sacred_cinders_apiary",10);	superbee_floral.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesBOTFloral", UID0: "magicbees.speciesBOTFloral"}]}}));	superbee_floral.setChance(0.0);	superbee_floral.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_floral.addItemOutput(<magicbees:beecomb:0>*64);	superbee_floral.addItemOutput(<magicbees:beecomb:4>*64);	superbee_floral.build();
val superbee_spiteful = RecipeBuilder.newBuilder("superbee_spiteful","sacred_cinders_apiary",10);	superbee_spiteful.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesSpiteful", UID0: "magicbees.speciesSpiteful"}]}}));	superbee_spiteful.setChance(0.0);	superbee_spiteful.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_spiteful.addItemOutput(<magicbees:beecomb:1>*64);	superbee_spiteful.addItemOutput(<magicbees:beecomb:1>*64);	superbee_spiteful.build();
val superbee_smouldering = RecipeBuilder.newBuilder("superbee_smouldering","sacred_cinders_apiary",10);	superbee_smouldering.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesSmouldering", UID0: "magicbees.speciesSmouldering"}]}}));	superbee_smouldering.setChance(0.0);	superbee_smouldering.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_smouldering.addItemOutput(<magicbees:beecomb:1>*64);	superbee_smouldering.addItemOutput(<magicbees:beecomb:7>*64);	superbee_smouldering.build();
val superbee_arcane = RecipeBuilder.newBuilder("superbee_arcane","sacred_cinders_apiary",10);	superbee_arcane.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesArcane", UID0: "magicbees.speciesArcane"}]}}));	superbee_arcane.setChance(0.0);	superbee_arcane.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_arcane.addItemOutput(<magicbees:beecomb:2>*64);	superbee_arcane.addItemOutput(<magicbees:drop:0>*64);	superbee_arcane.build();
val superbee_ethereal = RecipeBuilder.newBuilder("superbee_ethereal","sacred_cinders_apiary",10);	superbee_ethereal.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesEthereal", UID0: "magicbees.speciesEthereal"}]}}));	superbee_ethereal.setChance(0.0);	superbee_ethereal.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_ethereal.addItemOutput(<magicbees:beecomb:2>*64);	superbee_ethereal.addItemOutput(<magicbees:beecomb:3>*64);	superbee_ethereal.build();
val superbee_supernatural = RecipeBuilder.newBuilder("superbee_supernatural","sacred_cinders_apiary",10);	superbee_supernatural.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesSupernatural", UID0: "magicbees.speciesSupernatural"}]}}));	superbee_supernatural.setChance(0.0);	superbee_supernatural.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_supernatural.addItemOutput(<magicbees:beecomb:3>*64);	superbee_supernatural.addItemOutput(<magicbees:beecomb:3>*64);	superbee_supernatural.build();
val superbee_mutable = RecipeBuilder.newBuilder("superbee_mutable","sacred_cinders_apiary",10);	superbee_mutable.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesMutable", UID0: "magicbees.speciesMutable"}]}}));	superbee_mutable.setChance(0.0);	superbee_mutable.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_mutable.addItemOutput(<magicbees:beecomb:7>*64);	superbee_mutable.addItemOutput(<magicbees:beecomb:4>*64);	superbee_mutable.build();
val superbee_transmuting = RecipeBuilder.newBuilder("superbee_transmuting","sacred_cinders_apiary",10);	superbee_transmuting.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesTransmuting", UID0: "magicbees.speciesTransmuting"}]}}));	superbee_transmuting.setChance(0.0);	superbee_transmuting.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_transmuting.addItemOutput(<magicbees:beecomb:6>*64);	superbee_transmuting.addItemOutput(<magicbees:beecomb:7>*64);	superbee_transmuting.build();
val superbee_crumbling = RecipeBuilder.newBuilder("superbee_crumbling","sacred_cinders_apiary",10);	superbee_crumbling.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesCrumbling", UID0: "magicbees.speciesCrumbling"}]}}));	superbee_crumbling.setChance(0.0);	superbee_crumbling.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_crumbling.addItemOutput(<forestry:bee_combs:1>*64);	superbee_crumbling.addItemOutput(<forestry:bee_combs:10>*64);	superbee_crumbling.build();
val superbee_savant = RecipeBuilder.newBuilder("superbee_savant","sacred_cinders_apiary",10);	superbee_savant.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesSavant", UID0: "magicbees.speciesSavant"}]}}));	superbee_savant.setChance(0.0);	superbee_savant.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_savant.addItemOutput(<magicbees:beecomb:5>*64);	superbee_savant.addItemOutput(<forestry:bee_combs:0>*64);	superbee_savant.build();
val superbee_soul = RecipeBuilder.newBuilder("superbee_soul","sacred_cinders_apiary",10);	superbee_soul.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesSoul", UID0: "magicbees.speciesSoul"}]}}));	superbee_soul.setChance(0.0);	superbee_soul.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_soul.addItemOutput(<magicbees:beecomb:8>*64);	superbee_soul.addItemOutput(<magicbees:beecomb:6>*64);	superbee_soul.build();
val superbee_vazbee = RecipeBuilder.newBuilder("superbee_vazbee","sacred_cinders_apiary",10);	superbee_vazbee.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesBOTVazbee", UID0: "magicbees.speciesBOTVazbee"}]}}));	superbee_vazbee.setChance(0.0);	superbee_vazbee.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_vazbee.addItemOutput(<magicbees:beecomb:4>*64);	superbee_vazbee.addItemOutput(<minecraft:dye:9>*64);	superbee_vazbee.build();
val superbee_amped = RecipeBuilder.newBuilder("superbee_amped","sacred_cinders_apiary",10);	superbee_amped.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesTEAmped", UID0: "magicbees.speciesTEAmped"}]}}));	superbee_amped.setChance(0.0);	superbee_amped.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_amped.addItemOutput(<magicbees:beecomb:11>*64);	superbee_amped.addItemOutput(<thermalfoundation:material:1026>*64);	superbee_amped.build();
val superbee_firey = RecipeBuilder.newBuilder("superbee_firey","sacred_cinders_apiary",10);	superbee_firey.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesFirey", UID0: "magicbees.speciesFirey"}]}}));	superbee_firey.setChance(0.0);	superbee_firey.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_firey.addItemOutput(<magicbees:beecomb:12>*64);	superbee_firey.addItemOutput(<forestry:bee_combs:0>*64);	superbee_firey.build();
val superbee_rockin = RecipeBuilder.newBuilder("superbee_rockin","sacred_cinders_apiary",10);	superbee_rockin.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesTERocking", UID0: "magicbees.speciesTERocking"}]}}));	superbee_rockin.setChance(0.0);	superbee_rockin.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_rockin.addItemOutput(<magicbees:beecomb:14>*64);	superbee_rockin.addItemOutput(<thermalfoundation:material:1027>*64);	superbee_rockin.build();
val superbee_watery = RecipeBuilder.newBuilder("superbee_watery","sacred_cinders_apiary",10);	superbee_watery.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesWatery", UID0: "magicbees.speciesWatery"}]}}));	superbee_watery.setChance(0.0);	superbee_watery.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_watery.addItemOutput(<magicbees:beecomb:13>*64);	superbee_watery.addItemOutput(<forestry:bee_combs:0>*64);	superbee_watery.build();
val superbee_gelid = RecipeBuilder.newBuilder("superbee_gelid","sacred_cinders_apiary",10);	superbee_gelid.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesTEGelid", UID0: "magicbees.speciesTEGelid"}]}}));	superbee_gelid.setChance(0.0);	superbee_gelid.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_gelid.addItemOutput(<forestry:bee_combs:4>*64);	superbee_gelid.addItemOutput(<thermalfoundation:material:1025>*64);	superbee_gelid.build();
val superbee_pyro = RecipeBuilder.newBuilder("superbee_pyro","sacred_cinders_apiary",10);	superbee_pyro.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesTEPyro", UID0: "magicbees.speciesTEPyro"}]}}));	superbee_pyro.setChance(0.0);	superbee_pyro.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_pyro.addItemOutput(<magicbees:beecomb:1>*64);	superbee_pyro.addItemOutput(<thermalfoundation:material:1024>*64);	superbee_pyro.build();
val superbee_fluorine = RecipeBuilder.newBuilder("superbee_fluorine","sacred_cinders_apiary",10);	superbee_fluorine.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Fluorine", UID0: "gendustry.bee.Fluorine"}]}}));	superbee_fluorine.setChance(0.0);	superbee_fluorine.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_fluorine.addItemOutput(<gendustry:honey_comb:14027>*64);	superbee_fluorine.addItemOutput(<forestry:bee_combs:0>*64);	superbee_fluorine.build();
val superbee_helium = RecipeBuilder.newBuilder("superbee_helium","sacred_cinders_apiary",10);	superbee_helium.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Helium", UID0: "gendustry.bee.Helium"}]}}));	superbee_helium.setChance(0.0);	superbee_helium.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_helium.addItemOutput(<gendustry:honey_comb:14028>*64);	superbee_helium.addItemOutput(<forestry:bee_combs:0>*64);	superbee_helium.build();
val superbee_flux = RecipeBuilder.newBuilder("superbee_flux","sacred_cinders_apiary",10);	superbee_flux.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Flux", UID0: "gendustry.bee.Flux"}]}}));	superbee_flux.setChance(0.0);	superbee_flux.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_flux.addItemOutput(<fluxnetworks:flux>*64);	superbee_flux.addItemOutput(<fluxnetworks:flux>*64);	superbee_flux.build();
val superbee_forlorn = RecipeBuilder.newBuilder("superbee_forlorn","sacred_cinders_apiary",10);	superbee_forlorn.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesForlorn", UID0: "magicbees.speciesForlorn"}]}}));	superbee_forlorn.setChance(0.0);	superbee_forlorn.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_forlorn.addItemOutput(<magicbees:beecomb:10>*64);	superbee_forlorn.addItemOutput(<magicbees:beecomb:10>*64);	superbee_forlorn.build();

val superbee_cosmicconstellation = RecipeBuilder.newBuilder("superbee_cosmicconstellation","sacred_cinders_apiary",10);	superbee_cosmicconstellation.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.UniversalConstellation", UID0: "gendustry.bee.UniversalConstellation"}]}}));	superbee_cosmicconstellation.setChance(0.0);	superbee_cosmicconstellation.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_cosmicconstellation.addItemOutput(<contenttweaker:universal_constellation>*64);	superbee_cosmicconstellation.addItemOutput(<contenttweaker:universal_constellation>*64);	superbee_cosmicconstellation.build();

val superbee_treeoflife = RecipeBuilder.newBuilder("superbee_treeoflife","sacred_cinders_apiary",10);	superbee_treeoflife.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.TreeOfLife", UID0: "gendustry.bee.TreeOfLife"}]}}));	superbee_treeoflife.setChance(0.0);	superbee_treeoflife.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_treeoflife.addItemOutput(<contenttweaker:order_wood>*64);	superbee_treeoflife.addItemOutput(<contenttweaker:chaos_wood>*64);	superbee_treeoflife.build();

val superbee_gallifreyan = RecipeBuilder.newBuilder("superbee_gallifreyan","sacred_cinders_apiary",10);	superbee_gallifreyan.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Gallifreyan", UID0: "gendustry.bee.Gallifreyan"}]}}));	superbee_gallifreyan.setChance(0.0);	superbee_gallifreyan.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_gallifreyan.addItemOutput(<contenttweaker:strange_stone_essence>*64);	superbee_gallifreyan.addItemOutput(<contenttweaker:strange_stone_essence>*64);	superbee_gallifreyan.build();


val superbee_experienced = RecipeBuilder.newBuilder("superbee_experienced","sacred_cinders_apiary",10);	superbee_experienced.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Experienced", UID0: "gendustry.bee.Experienced"}]}}));	superbee_experienced.setChance(0.0);	superbee_experienced.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_experienced.addItemOutput(<contenttweaker:condensed_essence>*64);	superbee_experienced.addItemOutput(<contenttweaker:condensed_essence>*64);	superbee_experienced.build();

val superbee_phantasmal = RecipeBuilder.newBuilder("superbee_phantasmal","sacred_cinders_apiary",10);	superbee_phantasmal.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesPhantasmal", UID0: "forestry.speciesPhantasmal"}]}}));	superbee_phantasmal.setChance(0.0);	superbee_phantasmal.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_phantasmal.addItemOutput(<forestry:bee_combs:8>*64);	superbee_phantasmal.addItemOutput(<forestry:bee_combs:8>*64);	superbee_phantasmal.build();


val superbee_jaded = RecipeBuilder.newBuilder("superbee_jaded","sacred_cinders_apiary",10);	superbee_jaded.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.jaded", UID0: "extrabees.species.jaded"}]}}));	superbee_jaded.setChance(0.0);	superbee_jaded.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_jaded.addItemOutput(<forestry:bee_combs:0>*64);	superbee_jaded.addItemOutput(<forestry:pollen:0>*64);	superbee_jaded.build();


val superbee_lux = RecipeBuilder.newBuilder("superbee_lux","sacred_cinders_apiary",10);	superbee_lux.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesTELux", UID0: "magicbees.speciesTELux"}]}}));	superbee_lux.setChance(0.0);	superbee_lux.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_lux.addItemOutput(<magicbees:beecomb:2>*64);	superbee_lux.addItemOutput(<magicbees:beecomb:17>*64);	superbee_lux.build();

val superbee_destabilized = RecipeBuilder.newBuilder("superbee_destabilized","sacred_cinders_apiary",10);	superbee_destabilized.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesTEDestabilized", UID0: "magicbees.speciesTEDestabilized"}]}}));	superbee_destabilized.setChance(0.0);	superbee_destabilized.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_destabilized.addItemOutput(<magicbees:beecomb:2>*64);	superbee_destabilized.addItemOutput(<magicbees:beecomb:15>*64);	superbee_destabilized.build();

val superbee_endearing = RecipeBuilder.newBuilder("superbee_endearing","sacred_cinders_apiary",10);	superbee_endearing.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "magicbees.speciesTEEndearing", UID0: "magicbees.speciesTEEndearing"}]}}));	superbee_endearing.setChance(0.0);	superbee_endearing.addFluidInput(<fluid:liquid_sunshine>*25);	superbee_endearing.addItemOutput(<thermalfoundation:material:167>*64);	superbee_endearing.addItemOutput(<magicbees:beecomb:18>*64);	superbee_endearing.build();





val superbee_deeplands = RecipeBuilder.newBuilder("superbee_deeplands","sacred_cinders_apiary",10);	
superbee_deeplands.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Deeplands", UID0: "gendustry.bee.Deeplands"}]}}));	
superbee_deeplands.setChance(0.0);	
superbee_deeplands.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_deeplands.addItemOutput(<contenttweaker:deep_dark_matter>*64);	
superbee_deeplands.addItemOutput(<contenttweaker:deep_dark_matter>*64);	
superbee_deeplands.build();


val superbee_ascendant = RecipeBuilder.newBuilder("superbee_ascendant","sacred_cinders_apiary",10);	
superbee_ascendant.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Ascendant", UID0: "gendustry.bee.Ascendant"}]}}));	
superbee_ascendant.setChance(0.0);	
superbee_ascendant.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_ascendant.addItemOutput(<contenttweaker:opalescent_matter>*64);	
superbee_ascendant.addItemOutput(<contenttweaker:opalescent_matter>*64);	
superbee_ascendant.build();

val superbee_honeysmeltest = RecipeBuilder.newBuilder("superbee_honeysmeltest","sacred_cinders_apiary",10);	
superbee_honeysmeltest.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Honeysmeltest", UID0: "gendustry.bee.Honeysmeltest"}]}}));	
superbee_honeysmeltest.setChance(0.0);	
superbee_honeysmeltest.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_honeysmeltest.addItemOutput(<gendustry:honey_comb:14029>*64);	
superbee_honeysmeltest.addItemOutput(<gendustry:honey_comb:14029>*64);	
superbee_honeysmeltest.build();

val superbee_salty = RecipeBuilder.newBuilder("superbee_salty","sacred_cinders_apiary",10);	
superbee_salty.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Salty", UID0: "gendustry.bee.Salty"}]}}));	
superbee_salty.setChance(0.0);	
superbee_salty.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_salty.addItemOutput(<contenttweaker:polar_catalyst>*64);	
superbee_salty.addItemOutput(<contenttweaker:polar_catalyst>*64);	
superbee_salty.build();

val superbee_pyramid = RecipeBuilder.newBuilder("superbee_pyramid","sacred_cinders_apiary",10);	
superbee_pyramid.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Pyramid", UID0: "gendustry.bee.Pyramid"}]}}));	
superbee_pyramid.setChance(0.0);	
superbee_pyramid.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_pyramid.addItemOutput(<contenttweaker:stargate_sand>*64);	
superbee_pyramid.addItemOutput(<contenttweaker:stargate_sand>*64);	
superbee_pyramid.build();

val superbee_buried = RecipeBuilder.newBuilder("superbee_buried","sacred_cinders_apiary",10);	
superbee_buried.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Buried", UID0: "gendustry.bee.Buried"}]}}));	
superbee_buried.setChance(0.0);	
superbee_buried.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_buried.addItemOutput(<contenttweaker:stargate_hieroglyphs>*64);	
superbee_buried.addItemOutput(<contenttweaker:stargate_hieroglyphs>*64);	
superbee_buried.build();

val superbee_chevron = RecipeBuilder.newBuilder("superbee_chevron","sacred_cinders_apiary",10);	
superbee_chevron.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Chevron", UID0: "gendustry.bee.Chevron"}]}}));	
superbee_chevron.setChance(0.0);	
superbee_chevron.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_chevron.addItemOutput(<contenttweaker:stargate_chevron>*64);	
superbee_chevron.addItemOutput(<contenttweaker:stargate_chevron>*64);	
superbee_chevron.build();

val superbee_stargazer = RecipeBuilder.newBuilder("superbee_stargazer","sacred_cinders_apiary",10);	
superbee_stargazer.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Stargazer", UID0: "gendustry.bee.Stargazer"}]}}));	
superbee_stargazer.setChance(0.0);	
superbee_stargazer.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_stargazer.addItemOutput(<contenttweaker:sideral_steel>*64);	
superbee_stargazer.addItemOutput(<contenttweaker:sideral_steel>*64);	
superbee_stargazer.build();

val superbee_ringbearer = RecipeBuilder.newBuilder("superbee_ringbearer","sacred_cinders_apiary",10);	
superbee_ringbearer.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Ringbearer", UID0: "gendustry.bee.Ringbearer"}]}}));	
superbee_ringbearer.setChance(0.0);	
superbee_ringbearer.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_ringbearer.addItemOutput(<contenttweaker:stargate_ring>*64);	
superbee_ringbearer.addItemOutput(<contenttweaker:stargate_ring>*64);	
superbee_ringbearer.build();

val superbee_controller = RecipeBuilder.newBuilder("superbee_controller","sacred_cinders_apiary",10);	
superbee_controller.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Controller", UID0: "gendustry.bee.Controller"}]}}));	
superbee_controller.setChance(0.0);	
superbee_controller.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_controller.addItemOutput(<contenttweaker:stargate_controller>*64);	
superbee_controller.addItemOutput(<contenttweaker:stargate_controller>*64);	
superbee_controller.build();

val superbee_stormborn = RecipeBuilder.newBuilder("superbee_stormborn","sacred_cinders_apiary",10);	
superbee_stormborn.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Stormborn", UID0: "gendustry.bee.Stormborn"}]}}));	
superbee_stormborn.setChance(0.0);	
superbee_stormborn.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_stormborn.addItemOutput(<contenttweaker:stormlight_fragment>*64);	
superbee_stormborn.addItemOutput(<contenttweaker:stormlight_fragment>*64);	
superbee_stormborn.build();

val superbee_ryleyan = RecipeBuilder.newBuilder("superbee_ryleyan","sacred_cinders_apiary",10);	
superbee_ryleyan.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Ryleyan", UID0: "gendustry.bee.Ryleyan"}]}}));	
superbee_ryleyan.setChance(0.0);	
superbee_ryleyan.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_ryleyan.addItemOutput(<contenttweaker:stone_of_the_sleeping_city>*64);	
superbee_ryleyan.addItemOutput(<contenttweaker:stone_of_the_sleeping_city>*64);	
superbee_ryleyan.build();

val superbee_fissile = RecipeBuilder.newBuilder("superbee_fissile","sacred_cinders_apiary",10);	
superbee_fissile.addItemInput(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "gendustry.bee.Fissile", UID0: "gendustry.bee.Fissile"}]}}));	
superbee_fissile.setChance(0.0);	
superbee_fissile.addFluidInput(<fluid:liquid_sunshine>*25);	
superbee_fissile.addItemOutput(<contenttweaker:heuf_fuel>*64);	
superbee_fissile.addItemOutput(<contenttweaker:heuf_fuel>*64);	
superbee_fissile.build();
