import mods.modularmachinery.RecipeBuilder;


val creation1 = RecipeBuilder.newBuilder("creation1","creation_altar",1600);
creation1.addEnergyPerTickInput(400000);
creation1.addFluidInput(<fluid:lifeessence>*20000);
creation1.addFluidInput(<fluid:astralsorcery.liquidstarlight>*20000);
creation1.addFluidInput(<fluid:liquid_death>*20000);
creation1.addFluidInput(<fluid:liquid_pe>*20000);
creation1.addFluidInput(<fluid:liquid_lp>*20000);
creation1.addFluidInput(<fluid:californium_250>*20000);
creation1.addItemInput(<abyssalcraft:crystalcluster:12>);
creation1.addItemInput(<abyssalcraft:crystalcluster:14>);
creation1.addItemInput(<contenttweaker:ice_construct>);
creation1.addItemInput(<contenttweaker:fire_construct>);
creation1.addItemInput(<botania:rune:14>);
creation1.addItemInput(<botania:rune:15>);
creation1.addItemInput(<bloodmagic:blood_shard:0>);
creation1.addItemInput(<bloodmagic:blood_shard:1>);
creation1.addItemInput(<bewitchment:gold_moloch_idol>);
creation1.addItemInput(<bewitchment:gold_lilith_idol>);
creation1.addItemInput(<ebwizardry:melee_upgrade>);
creation1.addItemInput(<ebwizardry:attunement_upgrade>);
creation1.addItemInput(<extrautils2:angelring:0>);
creation1.addItemOutput(<contenttweaker:proxima_artifact>);
creation1.build();

val creation2 = RecipeBuilder.newBuilder("creation2","creation_altar",1600);
creation2.addEnergyPerTickInput(400000);
creation2.addFluidInput(<fluid:lifeessence>*25000);
creation2.addFluidInput(<fluid:astralsorcery.liquidstarlight>*25000);
creation2.addFluidInput(<fluid:liquid_death>*25000);
creation2.addFluidInput(<fluid:liquid_pe>*25000);
creation2.addFluidInput(<fluid:liquid_lp>*25000);
creation2.addFluidInput(<fluid:californium_250>*25000);
creation2.addItemInput(<contenttweaker:unidentified_body>*4);
creation2.addItemInput(<materialpart:lunastone:ingot>*2);
creation2.addItemInput(<materialpart:chalcedony:ingot>*2);
creation2.addItemInput(<materialpart:brightsteel:ingot>*2);
creation2.addItemInput(<materialpart:demonic_steel:ingot>*2);
creation2.addItemInput(<materialpart:corrosive_steel:ingot>*2);
creation2.addItemInput(<materialpart:destructive_steel:ingot>*2);
creation2.addItemInput(<materialpart:vengeful_steel:ingot>*2);
creation2.addItemInput(<materialpart:steadfast_steel:ingot>*2);
creation2.addItemInput(<materialpart:dreaded_steel:ingot>*2);
creation2.addItemInput(<materialpart:sednanite:ingot>*2);
creation2.addItemInput(<materialpart:myrmitite:ingot>*2);
creation2.addItemInput(<materialpart:ogerite:ingot>*2);
creation2.addItemInput(<thebetweenlands:octine_ingot>*2);
creation2.addItemOutput(<contenttweaker:unidentified_ingot>);
creation2.build();

val creation3 = RecipeBuilder.newBuilder("creation3","creation_altar",100);
creation3.addEnergyPerTickInput(400000);
creation3.addFluidInput(<fluid:lifeessence>*100);
creation3.addFluidInput(<fluid:astralsorcery.liquidstarlight>*100);
creation3.addFluidInput(<fluid:liquid_death>*100);
creation3.addFluidInput(<fluid:liquid_pe>*100);
creation3.addFluidInput(<fluid:liquid_lp>*100);
creation3.addFluidInput(<fluid:californium_250>*100);
creation3.addItemInput(<bloodmagic:item_demon_crystal:0>);
creation3.addItemInput(<bloodmagic:item_demon_crystal:1>);
creation3.addItemInput(<bloodmagic:item_demon_crystal:2>);
creation3.addItemInput(<bloodmagic:item_demon_crystal:3>);
creation3.addItemInput(<bloodmagic:item_demon_crystal:4>);
creation3.addItemOutput(<contenttweaker:bloodmaster_block>*8);
creation3.build();