import crafttweaker.item.IItemCondition;


<contenttweaker:trait_alien>.addTooltip(format.red("Gain random amounts of durability, speed, and damage over time."));
<contenttweaker:trait_antiair>.addTooltip(format.red("Extra damage to flying entities"));
<contenttweaker:trait_anticorrosion>.addTooltip(format.red("Chance every tick to cure poison"));
<contenttweaker:trait_apocalypse>.addTooltip(format.red("Adds increasing levels of Wither to foe"));
<contenttweaker:trait_aquadynamic>.addTooltip(format.red("Makes you mine at normal speed underwater and let you mine faster when raining"));
<contenttweaker:trait_aridiculous>.addTooltip(format.red("Mining speed and damage increases based on biome temperature"));
<contenttweaker:trait_autosmelt>.addTooltip(format.red("If the dropped block / item is smeltable, it will drop it smelted"));
<contenttweaker:trait_baconlicious>.addTooltip(format.red("5% chance when hitting a mob or 0.5% when mining a block to get a bacon"));
<contenttweaker:trait_baron>.addTooltip(format.red("20% chance to deal an additional 3 damage"));
<contenttweaker:trait_blazing>.addTooltip(format.red("Sets target on fire"));
<contenttweaker:trait_blind_bandit>.addTooltip(format.red("Sometimes spawns “Blind Bandit” who uses armor-piercing attacks on hostile mobs"));
<contenttweaker:trait_blizzard>.addTooltip(format.red("Ice dragon frost damage for 15 seconds"));
<contenttweaker:trait_bloodlust>.addTooltip(format.red("Mobs have an extra chance of dropping bloodlusts"));
<contenttweaker:trait_body>.addTooltip(format.red("Higher durability"));
<contenttweaker:trait_bone_shock>.addTooltip(format.red("Deals additional damage to non-arthropod creatures"));
<contenttweaker:trait_botanical>.addTooltip(format.red("Modifier slots increase greatly per level"));
<contenttweaker:trait_broodmother>.addTooltip(format.red("Spawn a vespa larva while hitting or mining"));
<contenttweaker:trait_brown_magic>.addTooltip(format.red("Allows to set portals and teleport"));
<contenttweaker:trait_chad_thunder>.addTooltip(format.red("When you use this tool, lightning happens all around you. When attacking an enemy, lightning strikes it."));
<contenttweaker:trait_cheap>.addTooltip(format.red("Bonus durability when repairing"));
<contenttweaker:trait_cheapskate>.addTooltip(format.red("Reduced durability"));
<contenttweaker:trait_chunky>.addTooltip(format.red("Chance to drop mob chunks"));
<contenttweaker:trait_coldblooded>.addTooltip(format.red("Extra damage if target is at full health"));
<contenttweaker:trait_coraliumplagued>.addTooltip(format.red("Gives the coralium plague"));
<contenttweaker:trait_counterweight>.addTooltip(format.red("Increases tool efficiency when not touching the ground"));
<contenttweaker:trait_critikill>.addTooltip(format.red("Always Crit!!"));
<contenttweaker:trait_crude>.addTooltip(format.red("Extra damage against mobs with no armor"));
<contenttweaker:trait_crumbling>.addTooltip(format.red("The tool breaks non-specific blocks faster (axe breaks stone fast), and stacks with mining speed."));
<contenttweaker:trait_dark_traveler>.addTooltip(format.red("Mobs nearby have a chance of taking damage"));
<contenttweaker:trait_darkness>.addTooltip(format.red("Gives blindness and wither to hit enemies"));
<contenttweaker:trait_democratic_peoples_republic_of_korea>.addTooltip(format.red("Supreme leaders mobs will explode nearby enemies on hit"));
<contenttweaker:trait_dense>.addTooltip(format.red("Chance to use less durability. Chance exponentially increases as the tool gets more damaged"));
<contenttweaker:trait_devils_strength>.addTooltip(format.red("Bonus damage to non-overworld mobs"));
<contenttweaker:trait_direct>.addTooltip(format.red("Mined items are teleported in your inventory"));
<contenttweaker:trait_discounted>.addTooltip(format.red("Increases durability gained while repairing"));
<contenttweaker:trait_dreadplagued>.addTooltip(format.red("Gives the dread plague"));
<contenttweaker:trait_duritae>.addTooltip(format.red("10% chance to use double durability, 40% chance to use no durability."));
<contenttweaker:trait_ecological>.addTooltip(format.red("1% chance every second to restore 1 durability. 1% chance on use to deal armor-piercing damage to the wearer."));
<contenttweaker:trait_elemental>.addTooltip(format.red("Breaks all gravity blocks above the block you just mined"));
<contenttweaker:trait_enderference>.addTooltip(format.red("Prevent an enderman from teleporting for 5 seconds after hitting it."));
<contenttweaker:trait_endspeed>.addTooltip(format.red("Projectiles hit instantly (it can be laggy if you shoot fast)"));
<contenttweaker:trait_energy_eater>.addTooltip(format.red("Increases efficiency and damage consuming energy"));
<contenttweaker:trait_energy_repair>.addTooltip(format.red("Consumes energy to gain durability"));
<contenttweaker:trait_ethereal_miner>.addTooltip(format.red("Prevents gravity blocks from falling"));
<contenttweaker:trait_evil_aura>.addTooltip(format.red("Gives bad luck"));
<contenttweaker:trait_evil_pressure>.addTooltip(format.red("Each hit has a chance to amplify negative effects present on mob"));
<contenttweaker:trait_experience_boost>.addTooltip(format.red("Bonux XP when mining and killing mobs"));
<contenttweaker:trait_famine>.addTooltip(format.red("Gives hunger, restores 1 hunger when mining blocks and hitting non-undead mobs"));
<contenttweaker:trait_flaming_fury>.addTooltip(format.red("Additional damage if target is on fire"));
<contenttweaker:trait_flammable>.addTooltip(format.red("Sets attackers on fire while blocking."));
<contenttweaker:trait_fractured>.addTooltip(format.red("Bonus 1.5 damage."));
<contenttweaker:trait_freezing>.addTooltip(format.red("Slows hit mobs, effect stacks the more you hit them"));
<contenttweaker:trait_fruit_salad>.addTooltip(format.red("Can store fruits (up to 5)"));
<contenttweaker:trait_ghastly>.addTooltip(format.red("If a mob damages you while you are sneaking, it gets slowness"));
<contenttweaker:trait_glitch>.addTooltip(format.red("Chance of dropping glitch hearts"));
<contenttweaker:trait_global_traveler>.addTooltip(format.red("Unlock the ability to transfer items to a block with an inventory. Shift-right click the chosen block with the item with this trait in order to bind it"));
<contenttweaker:trait_glowing>.addTooltip(format.red("Exclusive to boots. When the user is in the darkness, the trait automatically places a glowing slime ball. "));
<contenttweaker:trait_glowing>.addTooltip(format.red("Thanks to Luctor for writing some of these!"));
<contenttweaker:trait_hail_hydra>.addTooltip(format.red("Explosions on nearby mobs, with a chance of healing you"));
<contenttweaker:trait_he_who_must_not_be_named>.addTooltip(format.red("If a mob is nearby others of the same type, it gets extra damage"));
<contenttweaker:trait_healer>.addTooltip(format.red("Heals mobs instead of hurting them"));
<contenttweaker:trait_heavy>.addTooltip(format.red("Prevents the player from getting knocked back"));
<contenttweaker:trait_hellish>.addTooltip(format.red("Adds +2 damage (1 heart) against non-nether enities."));
<contenttweaker:trait_high_in_calcium>.addTooltip(format.red("Drops bones and bonemeal while breaking blocks"));
<contenttweaker:trait_hive_defender>.addTooltip(format.red("Bonus 4 damage against non-arthropods, 8 damage against death worms"));
<contenttweaker:trait_holy>.addTooltip(format.red("Inflicts weakness and extra damage against undeads"));
<contenttweaker:trait_illuminati>.addTooltip(format.red("Makes you invisible and gives glowing to nearby mobs"));
<contenttweaker:trait_im_a_superstar>.addTooltip(format.red("Increased attunement effects"));
<contenttweaker:trait_infernal_energy>.addTooltip(format.red("Much faster mining speed when you are on fire"));
<contenttweaker:trait_inferno>.addTooltip(format.red("Dragon fire damage for 15 seconds"));
<contenttweaker:trait_insatiable>.addTooltip(format.red("Using the tool adds a level of insatiable for 15 seconds, limited to 10 levels. Increases speed and damage by (level / 3)."));
<contenttweaker:trait_instakill>.addTooltip(format.red("Has a small chance of instantly killing either you or your enemy"));
<contenttweaker:trait_jaded>.addTooltip(format.red("Stops the natural healing of enemies for a few seconds"));
<contenttweaker:trait_jagged>.addTooltip(format.red("Gains bonus damage when tool is damaged. The more damaged it is (difference, not percentage), the more damage it deals."));
<contenttweaker:trait_laced>.addTooltip(format.red("Poisons creatures when hit"));
<contenttweaker:trait_launch>.addTooltip(format.red("Hit enemies have a chance of being launched upwards"));
<contenttweaker:trait_lightweight>.addTooltip(format.red("Bonus 10% mining speed, attack speed, bow draw speed."));
<contenttweaker:trait_living>.addTooltip(format.red("Repairs itself from soul network"));
<contenttweaker:trait_magically_brittle>.addTooltip(format.red("Random chance of breaking"));
<contenttweaker:trait_magically_modifiable>.addTooltip(format.red("Adds 3 extra modifiers"));
<contenttweaker:trait_magnetic>.addTooltip(format.red("Pulls in items from ~2 blocks away when used."));
<contenttweaker:trait_mana>.addTooltip(format.red("Consumes mana instead of durability"));
<contenttweaker:trait_mana_eater>.addTooltip(format.red("Higher efficiency and damage consuming mana"));
<contenttweaker:trait_mana_repair>.addTooltip(format.red("Consumes mana to gain durability"));
<contenttweaker:trait_mind>.addTooltip(format.red("Higher efficiency"));
<contenttweaker:trait_mirabile_visu>.addTooltip(format.red("Turns stone into diamond and gold ores"));
<contenttweaker:trait_moldable>.addTooltip(format.red("Extra modifier slot"));
<contenttweaker:trait_momentum>.addTooltip(format.red("When tool is used, increases tool's mining speed up to 40%. Momentum is lost when tool stops being used."));
<contenttweaker:trait_morgan_le_fay>.addTooltip(format.red("Bonus magic damage, up to 5"));
<contenttweaker:trait_music_of_the_spheres>.addTooltip(format.red("Tool plays music"));
<contenttweaker:trait_natures_blessing>.addTooltip(format.red("Chance of healing you and dropping bread after killing enemies"));
<contenttweaker:trait_natures_power>.addTooltip(format.red("Chance of seeting enemy on fire, give you speed, or strength"));
<contenttweaker:trait_natures_wrath>.addTooltip(format.red("Chance of healing you and setting enemy on fire"));
<contenttweaker:trait_overflow>.addTooltip(format.red("25% chance to half an enemy's health"));
<contenttweaker:trait_payback>.addTooltip(format.red("Higher damage the more health you are missing"));
<contenttweaker:trait_petramor>.addTooltip(format.red("10% chance to consume mined stone-type blocks to restore 5 durability."));
<contenttweaker:trait_poisonous>.addTooltip(format.red("Applies poison for 5 seconds on damage."));
<contenttweaker:trait_portly_gentleman>.addTooltip(format.red("Lets you capture mobs using shift + right click"));
<contenttweaker:trait_power_of_the_sun>.addTooltip(format.red("Higher damage and efficiency with higher light level"));
<contenttweaker:trait_precipitate>.addTooltip(format.red("Higher speed the less health you have"));
<contenttweaker:trait_prickly>.addTooltip(format.red("Deals armor-piercing damage to enemies hit and to player when mining."));
<contenttweaker:trait_prosperous>.addTooltip(format.red("Random chance of dropping prosperity shards"));
<contenttweaker:trait_psi_eater>.addTooltip(format.red("Increases damage and efficiency consuming psi"));
<contenttweaker:trait_psi_repair>.addTooltip(format.red("Consumes psi to gain durability"));
<contenttweaker:trait_purified>.addTooltip(format.red("Deals 25% mode damage to dread-plagued enemies"));
<contenttweaker:trait_radioactive>.addTooltip(format.red("Generate radiation"));
<contenttweaker:trait_reflect>.addTooltip(format.red("Thorns while tool is in hotbar"));
<contenttweaker:trait_rude_awakening>.addTooltip(format.red("Armor-piercing damage"));
<contenttweaker:trait_runic>.addTooltip(format.red("Converts part of your damage into magic damage"));
<contenttweaker:trait_shadow>.addTooltip(format.red("Uses mana to repair, summon dark pixies when attacking"));
<contenttweaker:trait_sharp>.addTooltip(format.red("Applies bleeding for 6 seconds."));
<contenttweaker:trait_shock>.addTooltip(format.red("Chance of enemies being struck by lightning"));
<contenttweaker:trait_shocking>.addTooltip(format.red("Builds electric charge as you move. Deals 5 bonus damage and gives haste when fully charged."));
<contenttweaker:trait_shyre_synthesis>.addTooltip(format.red("Toll will not lose durability under sunlight"));
<contenttweaker:trait_slashing>.addTooltip(format.red("Crits do 20% more damage"));
<contenttweaker:trait_slimey>.addTooltip(format.red("0.3% chance to summon a small slime corresponding to the color of the tool part"));
<contenttweaker:trait_slingshot>.addTooltip(format.red("Lets you launch other entities"));
<contenttweaker:trait_sos>.addTooltip(format.red("Consumes all durability to fully heal you if you are about to die"));
<contenttweaker:trait_soul>.addTooltip(format.red("Adds 3 modifiers"));
<contenttweaker:trait_soul_harvest>.addTooltip(format.red("Regenerates soul power while mining"));
<contenttweaker:trait_soul_sap>.addTooltip(format.red("Regenerates soul power based on damage dealt"));
<contenttweaker:trait_spades>.addTooltip(format.red("The lower your health, the higher your damage"));
<contenttweaker:trait_spiky>.addTooltip(format.red("Enemies that touch you while blocking take damage."));
<contenttweaker:trait_splinters>.addTooltip(format.red("Attacks apply a level of 'Splintering', up to 5 levels. Deal +0.3 bonus damage per level of Splintering."));
<contenttweaker:trait_squeaky>.addTooltip(format.red("Tool has silk touch but doesn't do damage."));
<contenttweaker:trait_stalwart>.addTooltip(format.red("Randomly gives strength"));
<contenttweaker:trait_starfishy>.addTooltip(format.red("Lets you set a portal, will consume 32 enori crystals and teleport you there if you are about to die"));
<contenttweaker:trait_stiff>.addTooltip(format.red("Makes blocking even more effective"));
<contenttweaker:trait_stonebound>.addTooltip(format.red("Mines faster the lower the durability"));
<contenttweaker:trait_stop_being_selfish>.addTooltip(format.red("Extra damage if other players are nearby"));
<contenttweaker:trait_superheat>.addTooltip(format.red("Bonus damage to enemies on fire"));
<contenttweaker:trait_tasty>.addTooltip(format.red("Tool has chance of losing durability and restore hunger, bacon can drop from broken blocks and hit mobs"));
<contenttweaker:trait_terrafirma>.addTooltip(format.red("Extra healing while holding tool in hand"));
<contenttweaker:trait_thaumic>.addTooltip(format.red("Extra modifiers based on the number of other thaumic parts"));
<contenttweaker:trait_thermal_inversion>.addTooltip(format.red("Applies slowness in hot biomes, or burning in cold biomes"));
<contenttweaker:trait_toxic>.addTooltip(format.red("Releases a toxic cloud when critically-hitting enemies"));
<contenttweaker:trait_tweeting>.addTooltip(format.red("Tool makes charger sounds"));
<contenttweaker:trait_twilit>.addTooltip(format.red("Higher speed and damage in the twilight forest"));
<contenttweaker:trait_unholy_touch>.addTooltip(format.red("Applies weakness and extra damage to non-undead mobs"));
<contenttweaker:trait_unnatural>.addTooltip(format.red("Mines blocks with lower mining level exponentially faster"));
<contenttweaker:trait_uplifting>.addTooltip(format.red("Chance of healing you"));
<contenttweaker:trait_vanishing>.addTooltip(format.red("Chance to teleport enemies away"));
<contenttweaker:trait_vile>.addTooltip(format.red("Extra kills into your soul shards"));
<contenttweaker:trait_vindictive>.addTooltip(format.red("Bonus damage against players"));
<contenttweaker:trait_weeee>.addTooltip(format.red("Breaks all blocks quickly"));
<contenttweaker:trait_wellestablished>.addTooltip(format.red("25% bonus experience"));
<contenttweaker:trait_whispering>.addTooltip(format.red("Sends weird messages in chat"));
<contenttweaker:trait_withering>.addTooltip(format.red("Applies wither"));
<contenttweaker:trait_writable>.addTooltip(format.red("Bonus 1 modifier. If the whole tool is made of paper, you gain 2 modifiers."));
<contenttweaker:trait_bloody_mary>.addTooltip(format.red("Deals more damage based on a mob's missing HP"));
<contenttweaker:trait_synergy>.addTooltip(format.red("Auto repairs tool consuming steeleaves from hotbar"));
<contenttweaker:trait_antigravity>.addTooltip(format.red("Projectiles will not be effected by gravity"));
<contenttweaker:trait_ingarage>.addTooltip(format.red("Extra five damage when in the shadow"));
<contenttweaker:trait_undone>.addTooltip(format.red("Chance of removing an armor piece on critical hits"));
<contenttweaker:trait_surfwaxmurica>.addTooltip(format.red("Extra five damage while riding a mount"));
<contenttweaker:trait_thunder>.addTooltip(format.red("Enemies are hit by lightning strikes"));
<contenttweaker:trait_necrotic>.addTooltip(format.red("Life-steal"));
<contenttweaker:trait_sentience>.addTooltip(format.red("Mobs drop will"));

